import type { Attrs, IdentityId, NpcId, Track } from './types'
import { ATTR_KEYS, playYear, type AttrKey } from './types'
import { gradeUnlocked, roleOffered, type RoleTier } from './rank'

export type ScriptGrade = 'C' | 'B' | 'A' | 'S'
export type ScriptHype = 'quiet' | 'trade' | 'ip' | 'award'
export type ScriptHighlight = 'fame' | 'director' | 'cast' | 'hype'
export type ScriptUnlock = 'broker' | 'liangshi' | 'guyan'

export type ScriptDef = {
  id: string
  title: string
  type: string
  track: Track
  tags: string[]
  theme: string
  keywords: string[]
  grade: ScriptGrade
  company: string
  director: string
  writer: string
  roleKind: string
  roleName: string
  role: string
  roleTier: RoleTier
  hype: ScriptHype
  awardTrack: boolean
  outline: string
  roleBio: string
  plot: string
  /** 圈内、原著、选角新闻。通告和手机里会轮到。 */
  press: string[]
  leads: string[]
  supporting: string[]
  need: Partial<Attrs>
  weights: Partial<Attrs>
  shootNeed: number
  deadlineDays: number
  promoNeed: number
  promoDays: number
  pay: number
  deposit: number
  recognition: number
  random?: boolean
  meetNpc?: NpcId
  sceneAt?: number
  sceneEvent?: string
  investor?: NpcId
  unlock?: ScriptUnlock
  unlockFavor?: number
  highlights?: ScriptHighlight[]
  /** 第几年开始出现。第一年的本后面仍可接。 */
  fromYear: number
}

export const GRADE_LABEL: Record<ScriptGrade, string> = {
  C: 'C · 小制作',
  B: 'B · 常规项目',
  A: 'A · 重点项目',
  S: 'S · 行业盯着',
}

export const GRADE_MULT: Record<ScriptGrade, number> = { C: 1, B: 1.45, A: 2.2, S: 3.4 }

export const NEED_NAME: Record<AttrKey, string> = {
  looks: '容貌',
  acting: '演技',
  talent: '才艺',
  speech: '口才',
  poise: '气质',
  fashion: '时尚',
  wit: '智慧',
  fitness: '体能',
  confidence: '自信',
}

export function workWindow(need: number): number {
  return need * 3 + 6
}

function inferRole(kind: string): RoleTier {
  if (/女主/.test(kind)) return 'lead'
  if (/女二/.test(kind)) return 'second'
  if (/女三/.test(kind)) return 'third'
  if (/客串/.test(kind)) return 'cameo'
  return 'support'
}

function inferHype(s: { grade: ScriptGrade; tags?: string[]; type: string }): ScriptHype {
  if (s.tags?.some((t) => /大 IP/.test(t))) return 'ip'
  if (s.grade === 'S' && /电影/.test(s.type)) return 'award'
  if (s.grade === 'S' || s.grade === 'A') return 'trade'
  return 'quiet'
}

function S(
  s: Omit<ScriptDef, 'tags' | 'deposit' | 'promoNeed' | 'promoDays' | 'track' | 'deadlineDays' | 'roleTier' | 'hype' | 'awardTrack' | 'press' | 'fromYear'> & {
    tags?: string[]
    deposit?: number
    promoNeed?: number
    promoDays?: number
    deadlineDays?: number
    track?: Track
    roleTier?: RoleTier
    hype?: ScriptHype
    awardTrack?: boolean
    press?: string[]
    fromYear?: number
  },
): ScriptDef {
  const promoNeed = s.promoNeed ?? 2
  const roleTier = s.roleTier ?? inferRole(s.roleKind)
  const hype = s.hype ?? inferHype(s)
  return {
    ...s,
    track: s.track ?? 'film',
    tags: s.tags ?? [s.type],
    press: s.press ?? [],
    fromYear: s.fromYear ?? 1,
    deposit: s.deposit ?? Math.round(s.pay * 0.2),
    promoNeed,
    deadlineDays: s.deadlineDays ?? workWindow(s.shootNeed),
    promoDays: s.promoDays ?? workWindow(promoNeed),
    roleTier,
    hype,
    awardTrack: s.awardTrack ?? false,
  }
}

export const SCRIPTS: ScriptDef[] = [
  S({
    id: 'store',
    title: '夜班便利店',
    type: '网剧',
    tags: ['网络剧'],
    theme: '都市深夜',
    keywords: ['便利店', '夜班', '沉默', '都市'],
    grade: 'C',
    company: '浪潮时代',
    director: '陈麦',
    writer: '许晚',
    roleKind: '女配角',
    roleName: '小周',
    role: '女配 · 夜班店员',
    outline: '凌晨三点的便利店。夜班店员小周先后遇见离家出走的女孩、刚下夜班的护士和不肯回家的醉汉。天快亮时，她也做了一个关于自己的决定。',
    roleBio: '小周二十四岁，在这家店做了半年。她不爱打听，却很会听人说话。台词不多，大部分情绪都在找零、热饭和短暂的停顿里。',
    plot: '导演想拍得自然，不要刻意煽情。中间有一场临时加戏，会和同组演员正面抢镜头。',
    leads: ['何朗', '江惜'],
    supporting: ['许宁'],
    need: { acting: 46, looks: 42 },
    weights: { acting: 3, looks: 2, speech: 1 },
    shootNeed: 6,
    pay: 6000,
    recognition: 4,
    meetNpc: 'xuning',
    sceneAt: 3,
    sceneEvent: 'scene-store',
  }),
  S({
    id: 'dialogue',
    title: '对白练习',
    type: '毕业短片',
    tags: ['短片', '学院'],
    theme: '校园',
    keywords: ['分手', '对白', '教室'],
    grade: 'C',
    company: '学院工作室',
    director: '韩向秋',
    writer: '韩向秋',
    roleKind: '女配角',
    roleName: '被留下的人',
    role: '女主同学 · 一场对手戏',
    outline: '一间空教室，一对已经决定分手的恋人。两个人都说得很客气，真正想问的话却一句也没说出口。',
    roleBio: '角色没有名字。她明明想挽留，嘴上却只说“路上小心”。这场戏从头到尾都不能哭。',
    plot: '韩老师现场执导，要求很细。拍摄时全班都会在旁边看。',
    leads: ['韩向秋'],
    supporting: [],
    need: { acting: 48, poise: 40 },
    weights: { acting: 4, confidence: 2, poise: 1 },
    shootNeed: 4,
    promoNeed: 1,
    pay: 0,
    deposit: 0,
    recognition: 6,
    sceneAt: 4,
    sceneEvent: 'scene-dialogue',
  }),
  S({
    id: 'vitamin',
    title: '维C广告女配',
    type: '广告',
    tags: ['广告'],
    theme: '商业',
    keywords: ['饮料', '邻家', '干净'],
    grade: 'C',
    company: '星汉文化',
    director: '广告组',
    writer: '品牌部',
    roleKind: '女配角',
    roleName: '回头的那个',
    role: '喝饮料回头的那个',
    outline: '十五秒的饮料广告。你和朋友从便利店出来，喝一口饮料，听见有人叫你，再回头对镜头笑。',
    roleBio: '没有角色名。你是氛围。妆面和走路比台词重要。品牌方坐在监视器后面，会说「再甜一点」，也会说「太甜了」。',
    plot: '品牌要自然、清爽，不能有太重的表演感。拍摄时间不长，但一个回头可能会反复拍很多次。',
    leads: ['顾辞晚'],
    supporting: [],
    need: { looks: 56, fashion: 50 },
    weights: { looks: 4, fashion: 3, confidence: 1 },
    shootNeed: 3,
    pay: 14000,
    recognition: 2,
  }),
  S({
    id: 'lipstick',
    title: '口红色号 08',
    type: '广告',
    tags: ['广告'],
    theme: '美妆',
    keywords: ['口红', '特写', '时尚'],
    grade: 'C',
    company: '星汉文化',
    director: '品牌影像组',
    writer: '策划',
    roleKind: '女配角',
    roleName: '08 号色',
    role: '涂口红的侧脸',
    outline: '只有嘴和锁骨入镜。品牌不要明星脸，要「像会买这支的人」。',
    roleBio: '没有台词，只有侧脸和唇部特写。妆面、眼神和拿口红的动作都要配合镜头。',
    plot: '棚拍一天，现场会试很多种灯光和角度。定金随合同先结。',
    leads: [],
    supporting: [],
    need: { looks: 62, fashion: 56, confidence: 44 },
    weights: { looks: 4, fashion: 4 },
    shootNeed: 2,
    promoNeed: 1,
    pay: 22000,
    recognition: 2,
    random: true,
  }),
  S({
    id: 'summer',
    title: '盛夏未完',
    type: '网剧',
    tags: ['网络剧'],
    theme: '青春',
    keywords: ['音乐学院', '室友', '选秀', '夏天'],
    grade: 'B',
    company: '浪潮时代',
    director: '陆深',
    writer: '乔南',
    roleKind: '女二',
    roleName: '林夏',
    role: '女二 林夏',
    outline: '县城女生考进音乐学院，夏天很长，选拔一场接一场。林夏是女主的室友：白天帮她记词，夜里自己加练。不是恶毒女二，是那种不敢先示弱、选秀里却不肯让的人。',
    roleBio: '林夏十九岁，来自小县城，嘴硬又敏感。室友发烧她会去买药，第二天的名额却一点不让。她怕被落下，比怕被讨厌更厉害。',
    plot: '有一场女主忘词。你伸不伸手，会改林夏的人设，也会改片场关系。学院礼堂、琴房加练、夏夜天台，都是这部要反复拍的地方。',
    press: [
      '网剧《盛夏未完》还在选女二。音乐学院、室友、选秀三件事绑在一起。夏天看完会反复重播的那种青春。',
      '《盛夏未完》选秀段落先卡人。女二林夏要能唱，也要演得过「帮完忙转身就赢」那场。',
      '《盛夏未完》路透出了琴房加练。原声还是后期，评论已经吵开了。',
    ],
    leads: ['周棠'],
    supporting: ['梁时'],
    need: { acting: 72, talent: 66, looks: 60, confidence: 62 },
    weights: { acting: 3, talent: 3, looks: 2, confidence: 1 },
    shootNeed: 12,
    promoNeed: 4,
    pay: 86000,
    recognition: 18,
    hype: 'trade',
    meetNpc: 'liangshi',
    sceneAt: 6,
    sceneEvent: 'scene-summer',
  }),
  S({
    id: 'nightstudy',
    title: '晚自习以后',
    type: '校园网剧',
    tags: ['网络剧', '校园'],
    theme: '校园',
    keywords: ['高考', '天台', '课代表', '家长群'],
    grade: 'B',
    company: '嘉尚影业',
    director: '闵秋',
    writer: '沈纸',
    roleKind: '女配角',
    roleName: '课代表',
    role: '女配 · 课代表',
    outline: '高三。晚自习后的天台，家长群比卷子响。课代表收卷子时能看见别人的崩溃，自己一句不说。她不是女主的闺蜜，是成绩好、话少、大家不敢靠近的那种同学。',
    roleBio: '话少，成绩好。不是严厉的班干部，只是太习惯把自己的事放到最后。久而久之，大家都以为她什么也不需要。',
    plot: '教室、天台、家访，都要拍得像真的高三，不能演成鸡汤。家长群那几场，弹幕会比正片先到。',
    press: [
      '校园剧《晚自习以后》还在补课代表。家长群、模拟考、晚自习后的天台，不是甜宠校园。',
      '《晚自习以后》家访那场先传开了。有人说像自家，有人说太真，看着累。',
    ],
    leads: ['安青', '裴渡'],
    supporting: ['阮清'],
    need: { acting: 68, poise: 62, wit: 48 },
    weights: { acting: 3, poise: 3, wit: 2 },
    shootNeed: 10,
    promoNeed: 3,
    pay: 24000,
    recognition: 9,
    meetNpc: 'ruanqing',
    sceneAt: 5,
    sceneEvent: 'scene-nightstudy',
  }),
  S({
    id: 'uncle',
    title: '我的二舅爷',
    type: '上星剧',
    tags: ['上星剧', '网络剧'],
    theme: '当代乡村',
    keywords: ['农村', '基建', '通水', '回乡'],
    grade: 'B',
    company: '天奇影视',
    director: '邢伟',
    writer: '葛大运',
    roleKind: '女配角',
    roleName: '黄三珍',
    role: '女配 · 黄三珍',
    outline: '西北村子从灾年走到通水通路。村长黄万福带着人开会、挖渠，把不肯回来的年轻人一个个劝回家。黄三珍是他女儿，去城里学了美容，最后把手艺带回来——戏不在哭，在她怎么把城里那点傲气收住。',
    roleBio: '黄三珍叛逆，但孝顺。城里学的是美容，回来面对的是还没通上的水和不肯认她的邻居。她不是女主，镜头却总在她进村那一次。',
    plot: '剧组会在乡下拍很久。人物要接地气，但不能故意把农村生活演得土气或可怜。开会、挖渠、婚宴，都得像真的村子。',
    press: [
      '上星剧《我的二舅爷》还在补黄三珍。不是女主，镜头却不少。通水通路、开会挖渠那种当代乡村，不是土味短剧。',
      '《我的二舅爷》在村里实拍。盒饭、尘、停电都是真的，演员化妆得往土里靠，不能往精修靠。',
      '《我的二舅爷》预告出了通水那天。弹幕在刷「我们县也是这样过来的」。',
    ],
    leads: ['龙武山', '徐开荣'],
    supporting: ['严宣', '王一芸'],
    need: { acting: 70, poise: 56, speech: 50 },
    weights: { acting: 3, poise: 2, speech: 2, looks: 1 },
    shootNeed: 16,
    promoNeed: 4,
    pay: 42000,
    recognition: 12,
    hype: 'trade',
    random: true,
  }),
  S({
    id: 'sweet',
    title: '请你偏爱',
    type: '甜宠网剧',
    tags: ['网络剧'],
    theme: '都市甜宠',
    keywords: ['联姻', '退婚', '宴会', '女三'],
    grade: 'B',
    company: '浪潮时代',
    director: '赵浅',
    writer: '米柚',
    roleKind: '女三',
    roleName: '许晚宁',
    role: '女三 · 被退掉的联姻',
    outline: '财阀联姻宴会上，男主当众把婚约从她手里改到女主手上。她把戒指摘下来，笑着敬下一杯。不是因为爱而砸场，是第一次发现有人可以当众不选她。后面还有几场「前任」戏，切片会比正片先火。',
    roleBio: '许晚宁从小被家里安排好一切：学校、衣服、婚约。她不是恶毒女三，是那种笑着把场子圆完、回车上才把脸卸下来的人。',
    plot: '宴会退婚是全网先传的那场。笑要得体，走要干脆，不能演成泼妇，也不能演成白莲。通告密，档期一撞，片方不等。',
    press: [
      '甜宠《请你偏爱》女三许晚宁还在换人。宴会上被退婚那场已经传开，切片号在等「摘戒指」那一下。',
      '《请你偏爱》超前点播预告只剪退婚。原著粉说女三后面还有戏，路人说「不就是恶毒女三」。',
      '《请你偏爱》女三通告排得很满。片方要的是能撑宴会、也能撑「前任」几场的人，不是路过哭一下。',
    ],
    leads: ['盛宴', '姜棠'],
    supporting: ['宋晚'],
    need: { looks: 78, confidence: 68, acting: 62, fashion: 64 },
    weights: { looks: 3, confidence: 3, acting: 2, fashion: 2 },
    shootNeed: 10,
    promoNeed: 4,
    pay: 52000,
    recognition: 14,
    random: true,
    meetNpc: 'songwan',
    sceneAt: 4,
    sceneEvent: 'scene-sweet',
  }),
  S({
    id: 'rain',
    title: '回南天',
    type: '微电影',
    tags: ['电影', '短片'],
    theme: '家庭',
    keywords: ['回南天', '父亲', '返乡', '沉默'],
    grade: 'B',
    company: '星汉文化',
    director: '沈照',
    writer: '无名氏',
    roleKind: '女配角',
    roleName: '女儿',
    role: '女配 · 沉默的女儿',
    outline: '回南天，墙上在滴水。父亲的旧收音机怎么调都是杂音。女儿不解释为什么从城里回来，只把窗一遍遍擦干。几乎没有台词，靠的是停顿和呼吸。',
    roleBio: '她不是来和解的，也不是来决裂的。她把窗擦干，把饭热上，把该说的话留在喉咙里。导演不喜欢哭戏。',
    plot: '全片台词很少。沈照不讲情绪，只会告诉你哪里不对。回南天的水、旧收音机、擦窗，都要拍很多遍。',
    press: [
      '沈照短片《回南天》还在找不怎么说话的女儿。返乡、旧物、不解释的那种家庭沉默片。',
      '《回南天》几乎没有对白。圈里有人说评委会看，也有人说「现在谁看这个」。',
    ],
    leads: ['老周'],
    supporting: [],
    need: { acting: 72, poise: 66 },
    weights: { acting: 4, poise: 3, looks: 1 },
    shootNeed: 12,
    promoNeed: 3,
    pay: 16000,
    recognition: 16,
    hype: 'award',
    meetNpc: 'shenzhao',
    sceneAt: 10,
    sceneEvent: 'scene-rain',
  }),
  S({
    id: 'blade',
    title: '西市夜',
    type: '古装网剧',
    tags: ['网络剧', '古装'],
    theme: '古装',
    keywords: ['客串', '夜市', '刀马', '西市'],
    grade: 'B',
    company: '嘉尚影业',
    director: '裴横',
    writer: '方简',
    roleKind: '客串',
    roleName: '刀马旦',
    role: '客串 · 夜市上的刀马旦',
    outline: '西市夜市。刀马旦在棚上唱一句、翻一个跟头，女主路过，扔来钱袋。没有名字，只有这一场。戏班的锣鼓、夜市的灯，要比人先入镜。',
    roleBio: '夜市戏班里的刀马旦。唱一句，翻一个跟头，再接住女主扔来的钱袋。出场很短，动作必须干净。',
    plot: '角色只有一场戏，唱腔和动作都要提前准备。剧组不会为客串延长档期。',
    press: [
      '古装《西市夜》还空一场夜市客串。刀马旦、扔钱袋、一眼。长安夜市过场，短，但要干净。',
    ],
    leads: ['沈照'],
    supporting: [],
    need: { talent: 62, fitness: 58, poise: 50 },
    weights: { talent: 3, fitness: 3, poise: 2 },
    shootNeed: 5,
    promoNeed: 1,
    pay: 12000,
    recognition: 7,
    random: true,
    meetNpc: 'shenzhao',
  }),
  S({
    id: 'whitenoise',
    title: '白噪音',
    type: '都市剧',
    tags: ['上星剧'],
    theme: '都市心理',
    keywords: ['心理门诊', '前台', '中产', '秘密'],
    grade: 'A',
    company: '嘉尚影业',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女配角',
    roleName: '前台',
    role: '女配 · 心理门诊前台',
    outline: '写字楼里一家心理门诊。客人把出轨、裁员、不肯回家的孩子留在诊室，前台把下一杯水递出去。她每天听见中产的秘密，自己的约会却记不住。戏看起来闲，其实每场都在听别人的人生。',
    roleBio: '前台不是工具人。她记得每个预约，却不记得自己的约会。真正难演的是职业性的体贴，而不是热心。',
    plot: '她每天听见很多秘密，却从不参与任何人的人生。叫号、倒水、送客，都是戏。闻疏说，叫号也要有停顿。',
    press: [
      '上星剧《白噪音》前台还没定。闻疏说叫号也是戏。写字楼心理门诊，听的是中产不肯带回家的那些事。',
      '《白噪音》剧本围读流出几页。没有血腥，全是谈话。有人说像纪实，有人说「现在谁看心理」。',
      '《白噪音》男主沈照、梁时都定了。前台那栏空着，片方要能把「闲」演满的人。',
    ],
    leads: ['沈照', '梁时'],
    supporting: ['许宁'],
    need: { acting: 118, speech: 102, wit: 96 },
    weights: { acting: 3, speech: 3, wit: 3, poise: 2 },
    shootNeed: 18,
    promoNeed: 5,
    pay: 62000,
    recognition: 20,
    meetNpc: 'xuning',
    investor: 'guyan',
  }),
  S({
    id: 'intern',
    title: '白大褂',
    type: '医疗剧',
    tags: ['上星剧'],
    theme: '医疗',
    keywords: ['急诊', '实习', '夜班', '术语'],
    grade: 'A',
    company: '嘉尚影业',
    director: '齐衡',
    writer: '医科顾问组',
    roleKind: '女配角',
    roleName: '实习医师 陈慈',
    role: '女配 · 实习医生',
    outline: '三甲急诊。走廊里有人被喊去推床，术语不能错，交接班写在白板上。陈慈不是女主，是刚轮转过来、说每句话都很慢的那一个。忙起来以后，反而成了最稳的那个。',
    roleBio: '陈慈刚轮转到急诊。她怕出错，所以说得很慢；真正忙起来，手比嘴先到。台词少，病历和口型不能错。',
    plot: '走廊、夜班、抢救。齐衡不爱重来。医顾问组盯口型，术语错一个，整条作废。',
    press: [
      '医疗剧《白大褂》还在补实习医生陈慈。齐衡的组，术语不能错。急诊走廊，不是谈恋爱的白大褂。',
      '《白大褂》医顾问组已经进组。口型、病历、推床路线都要过。有人说这是「看病的剧」，有人说太累。',
      '《白大褂》夜班戏连拍。盒饭、绿光、真正的交接班白板，花絮先于正片传出。',
    ],
    leads: ['何朗', '白疏影'],
    supporting: ['陈慈'],
    need: { acting: 116, wit: 110, speech: 82, poise: 78 },
    weights: { wit: 4, acting: 3, speech: 2 },
    shootNeed: 14,
    promoNeed: 4,
    pay: 58000,
    recognition: 18,
    random: true,
  }),
  S({
    id: 'snowcourt',
    title: '庭前雪',
    type: '古装网剧',
    tags: ['网络剧', '古装'],
    theme: '古装权谋',
    keywords: ['联姻', '宴席', '仪态', '世家'],
    grade: 'A',
    company: '浪潮时代',
    director: '邢未',
    writer: '顾辞',
    roleKind: '女三',
    roleName: '小郡主',
    role: '女三 · 小郡主',
    outline: '北地小郡主被送去联姻。宴席上笑要得体，怒不能露，落座先后能改两家结盟。不是宫斗女主本，是那些把仪态演满的郡主戏：表面守礼，真正的态度藏在看人和敬酒的顺序里。',
    roleBio: '小郡主被人说花瓶。你要让观众觉得她不是。她不是来抢女主的，是被安排在席面上、一句话也不能说错的人。',
    plot: '戏集中在几场宴席。动作戏不多，仪态一场接一场。服化道会先被骂，成片才见人。',
    press: [
      '《庭前雪》小郡主还在选。原著是男频权谋改的女向，宴席上那张脸，片方要重新看。',
      '江晚宁《庭前雪》海报顺序又改了一版。片方说按合同，原著粉说按人气。小郡主那栏还空着。',
      '《庭前雪》服化道路透。头面比人先出圈，妆造连夜发长文，说「成片为准」。',
      '《庭前雪》围读传出联姻宴席那场。女三没有拔剑，只有敬酒和落座。有人说难演，有人说没戏。',
    ],
    leads: ['陈晚秋', '陆承宴'],
    supporting: ['小郡主'],
    need: { acting: 126, poise: 122, looks: 105, fitness: 76 },
    weights: { acting: 3, poise: 3, looks: 3, fashion: 1, fitness: 1 },
    shootNeed: 23,
    promoNeed: 6,
    pay: 128000,
    recognition: 26,
    hype: 'trade',
  }),
  S({
    id: 'musicdoc',
    title: '隔音未满',
    type: '音综纪录',
    track: 'variety',
    tags: ['综艺', '纪录'],
    theme: '音乐',
    keywords: ['唱歌', '排练室', '同期', '真人'],
    grade: 'A',
    company: '星汉文化',
    director: '节目组',
    writer: '剪辑台',
    roleKind: '选手',
    roleName: '自己',
    role: '选手 · 自己',
    outline: '一档把排练室、抢麦、选歌都拍下来的音综。镜头会跟到练声，也会跟到大家累到不想说话的时候。没有角色可以躲，观众很容易看出谁在经营人设。',
    roleBio: '没有角色可以躲。节目组想看真实反应：抢排练室、选歌吵起来、唱砸了以后的脸。',
    plot: '舞台表现和采访同样重要。唱得好会留下完整舞台，失误也可能被单独剪出来。',
    press: [
      '音综《隔音未满》还在补选手。拍的是排练室和生活，不是只拍舞台。有人拿它跟「把乐队关进一栋楼」那种节目比。',
      '《隔音未满》预告先出抢排练室。弹幕在猜谁会红，谁会在采访里翻车。',
    ],
    leads: ['裴予'],
    supporting: [],
    need: { talent: 112, speech: 88, fitness: 82 },
    weights: { talent: 5, speech: 2, confidence: 2, looks: 1 },
    shootNeed: 16,
    promoNeed: 6,
    pay: 42000,
    recognition: 16,
    meetNpc: 'peiyu',
  }),
  S({
    id: 'watch',
    title: '观察室',
    type: '真人秀',
    track: 'variety',
    tags: ['综艺'],
    theme: '观察',
    keywords: ['点评', '观察室', '恋爱综艺'],
    grade: 'A',
    company: '星汉文化',
    director: '总导演',
    writer: '环节组',
    roleKind: '观察员',
    roleName: '自己',
    role: '飞行观察员',
    outline: '恋爱综艺的飞行观察员。你不进别墅，只在演播室看片段、聊天、猜嘉宾下一步会选谁。回答太圆滑会显得无聊，随口一句说重了，播出后就是争议。',
    roleBio: '你演自己。观察室里的人要会看、会接话，也要知道哪句不能说完。',
    plot: '录制多在晚上，环节和话题会临时调整。镜头会切到你听完沉默的那一秒。',
    press: [
      '《观察室》还在找飞行观察员。不进别墅，只在演播室猜。节目组要能接话、也敢把话说满的人。',
      '《观察室》观察室物料先出。有人靠一句点评上了热搜，有人靠一句口误。',
    ],
    leads: [],
    supporting: ['许宁'],
    need: { speech: 112, confidence: 98, looks: 88 },
    weights: { speech: 4, confidence: 3, looks: 2 },
    shootNeed: 8,
    promoNeed: 3,
    pay: 48000,
    recognition: 15,
    random: true,
    meetNpc: 'xuning',
  }),
  S({
    id: 'unnamed',
    title: '未命名',
    type: '文艺电影',
    tags: ['电影'],
    theme: '文艺',
    keywords: ['书店', '无对白', '退货', '等待'],
    grade: 'S',
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女配角',
    roleName: '店员',
    role: '女配 · 书店店员',
    outline: '旧书店。退货的书要一本本重新上架，几乎没有对白。店员每天等一个不会回来的人。沈照不说戏，只说「再安静一点」。圈里当冲奖看，也有人觉得这是在浪费档期。',
    roleBio: '店员没有名字，独自在旧书店工作。她把退回来的书重新上架，也在等一个已经不会回来的人。戏在手指、脚步和停顿里。',
    plot: '行业里会有人因为这部片才正眼看你，也会有人觉得你在浪费时间。金桂奖偶尔会看这种角色，但几乎轮不到新人。关门拍，探班的站姐等不到人。',
    press: [
      '沈照新片《未命名》还在找书店那个女人。几乎没有对白，退货上架，等一个不回来的人。圈里当冲奖看。',
      '《未命名》关门拍。探班的站姐在酒店走廊等到天亮，只拍到一箱退货的书。',
      '影评号把《未命名》写成「今年会盯的配角」。也有人说，现在谁还进电影院看书店。',
      '《未命名》选角极慢。沈照看了很多人，只说「再安静一点」。片酬一般，档期却要让。',
    ],
    leads: ['何朗'],
    supporting: [],
    need: { acting: 168, poise: 158, wit: 118 },
    weights: { acting: 5, poise: 4, wit: 2, looks: 1 },
    shootNeed: 23,
    promoNeed: 6,
    pay: 92000,
    recognition: 44,
    hype: 'award',
    awardTrack: true,
    meetNpc: 'shenzhao',
    sceneAt: 18,
    sceneEvent: 'scene-rain',
  }),
  S({
    id: 'starriver',
    title: '星河渡',
    type: '大 IP 网剧',
    tags: ['网络剧', '大 IP'],
    theme: '仙侠',
    keywords: ['女二', '联姻', '天界', '粉籍'],
    grade: 'S',
    company: '嘉尚影业',
    director: '裴衡',
    writer: '原著改编',
    roleKind: '女二',
    roleName: '反派侧',
    role: '女二 · 反派侧',
    outline: '上神渡劫，小仙误入天界。原著连载时订阅过千万，讲的是一场用三百年换一次回头的姻缘。女二不是女主的影子：她是魔尊侧送来联姻的人，清楚自己在用感情换一个位置。粉籍会撕，资本会盯番位。',
    roleBio: '她爱得难看，但每一笔都算过。演飘了就会被写成「恶毒女二」；演收了，原著粉才会承认这是原著里那个把命押上去的人。',
    plot: '这是个很容易被演成普通反派的角色。她真正的野心、感情和不甘必须同时成立。超前点播预告、海报顺序、服化道路透，都会先于正片吵完。',
    press: [
      '原著《星河渡》连载时订阅过千万：上神渡劫，小仙入天界。女二是魔尊侧联姻的那个人，还没定。裴衡看了几轮，粉籍已经按人设在骂名字。',
      '《星河渡》选角名单泄漏。江晚宁女主、陆承宴上神，女二那栏空着。原著粉连夜列「不能碰的三件事」。',
      '《星河渡》超前点播预告先出女二那一眼。一半说「原著就是这样」，一半说「又改成恶毒女二」。',
      '《星河渡》服化道路透。头套边缘出戏，妆造连夜发长文。番位海报又改了一版，片方说按合同。',
    ],
    leads: ['江晚宁', '陆承宴'],
    supporting: ['许宁'],
    need: { acting: 158, looks: 142, confidence: 136, speech: 112 },
    weights: { acting: 4, looks: 3, confidence: 2, speech: 2 },
    shootNeed: 23,
    promoNeed: 8,
    pay: 480000,
    recognition: 32,
    hype: 'ip',
    meetNpc: 'xuning',
  }),
  S({
    id: 'northstation',
    title: '北站',
    type: '电影',
    tags: ['电影'],
    theme: '现实主义',
    keywords: ['春运', '广播', '延误', '车站'],
    grade: 'S',
    company: '嘉尚影业',
    director: '老钱',
    writer: '老钱',
    roleKind: '女配角',
    roleName: '广播员',
    role: '女配 · 站台广播员',
    outline: '春运。广播室里通宵念延误、重连、请旅客不要拥挤。电影不靠你赢，但有一场你对着空麦克风把通知念完，剪进预告就会被人记住。正脸不多，声音和停顿是戏。',
    roleBio: '广播员不露脸太多。她把通知念完，把哭声隔在玻璃外面。导演希望观众先记住她的声音，再记住她的人。',
    plot: '有一段很长的独白。春运是真的人流，剧组要赶点，广播词不能念成朗诵。',
    press: [
      '老钱《北站》广播员还在试。春运那场对着空麦把通知念完，有人说能进预告。',
      '《北站》在车站实拍。春运是真的，群演是真的，广播词改了十一稿。',
      '《北站》预告先出广播。有人听完说像回家，有人说「又是春运苦情」。',
    ],
    leads: ['何朗'],
    supporting: ['广播员'],
    need: { acting: 148, speech: 128, poise: 118 },
    weights: { acting: 4, speech: 4, poise: 2 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 98000,
    recognition: 40,
    hype: 'award',
  }),
  S({
    id: 'coverclip',
    title: '未发布的翻唱',
    type: '翻唱企划',
    track: 'music',
    tags: ['翻唱'],
    theme: '翻唱',
    keywords: ['翻唱', '短视频', '原曲'],
    grade: 'C',
    company: '北声厂牌',
    director: '企划',
    writer: '原曲',
    roleKind: '歌手',
    roleName: '自己',
    role: '翻唱 · 自己',
    outline: '厂牌要一条能发出去的翻唱。不是发行，是试你的声音能不能站住。棚很小，耳机漏音。',
    roleBio: '你唱别人的歌，要保留原曲的味道，也得让人听出这是你的声音。',
    plot: '录音棚很小，制作人会从头听到尾。最终版本是否上线，要等录完以后再决定。',
    leads: [],
    supporting: [],
    need: { talent: 44, speech: 32 },
    weights: { talent: 5, speech: 1 },
    shootNeed: 3,
    promoNeed: 2,
    pay: 3500,
    recognition: 3,
  }),
  S({
    id: 'ostdemo',
    title: '未署名插曲',
    type: '剧宣曲',
    track: 'music',
    tags: ['剧宣曲'],
    theme: '剧集宣传',
    keywords: ['插曲', '不署名', '副歌'],
    grade: 'C',
    company: '北声厂牌',
    director: '配乐组',
    writer: '词作者未署名',
    roleKind: '声部',
    roleName: '未署名',
    role: '插曲声部',
    outline: '剧要一首插曲，名字不出现在片尾。副歌只给你两句。棚里先对气口，再谈钱。',
    roleBio: '没有名字。声音贴上了，片尾也不写你。',
    plot: '只有两句副歌，但要贴合剧里的人物情绪。录得合适，可能会用进预告。',
    leads: [],
    supporting: [],
    need: { talent: 50, poise: 40 },
    weights: { talent: 4, poise: 2 },
    shootNeed: 4,
    promoNeed: 2,
    pay: 7000,
    recognition: 4,
  }),
  S({
    id: 'nightsingle',
    title: '夜班以后',
    type: '独立单曲',
    track: 'music',
    tags: ['单曲'],
    theme: '独立发行',
    keywords: ['单曲', '夜', '发行'],
    grade: 'B',
    company: '海潮唱片',
    director: '制作人阿白',
    writer: '阿白',
    roleKind: '歌手',
    roleName: '自己',
    role: '独唱',
    outline: '一张要上架的单曲。封面、词、发行日都已经定了，差一个敢把副歌唱满的人。',
    roleBio: '这回有名字。发行日不能拖。',
    plot: '除了录歌，还要拍封面和跑发行采访。第一次以自己的名字发歌，每个环节都得本人出现。',
    leads: [],
    supporting: [],
    need: { talent: 72, speech: 54, looks: 54 },
    weights: { talent: 5, speech: 2, looks: 2 },
    shootNeed: 6,
    promoNeed: 4,
    pay: 28000,
    recognition: 12,
    roleTier: 'second',
  }),
  S({
    id: 'nighttalk',
    title: '三点档',
    type: '深夜访谈',
    track: 'variety',
    tags: ['访谈', '综艺'],
    theme: '深夜',
    keywords: ['访谈', '口才', '口误'],
    grade: 'C',
    company: '昼间传媒',
    director: '值班导演',
    writer: '环节组',
    roleKind: '嘉宾',
    roleName: '自己',
    role: '飞行嘉宾',
    outline: '凌晨三点的访谈。观众不多，切片很快。说错一句，比演错一场传得更远。',
    roleBio: '你不演戏。你说话。镜头对着你的停顿。',
    plot: '节目看似随意，其实问题都准备得很细。回答得好可能被转发，口误也一样。',
    leads: [],
    supporting: [],
    need: { speech: 44, looks: 40 },
    weights: { speech: 4, looks: 2, confidence: 1 },
    shootNeed: 3,
    promoNeed: 1,
    pay: 5000,
    recognition: 4,
  }),
  S({
    id: 'glassroom',
    title: '隔间',
    type: '短片',
    tags: ['电影', '短片'],
    theme: '文艺',
    keywords: ['审讯', '停顿', '不招'],
    grade: 'B',
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女配角',
    roleName: '被问话的人',
    role: '女配 · 隔间里的女人',
    outline: '二十分钟。审讯室隔间，灯一直亮。她不招，也不哭。沈照不说戏，只说再短一点。评委会看的是你怎么把「不招」演满。',
    roleBio: '没有名字。灯在头顶，问题在玻璃外面。她把「不招」演满，而不是把委屈演满。',
    plot: '预算不高，拍摄要求却很严。沈照会把一个停顿反复磨很多遍。',
    press: [
      '沈照短片《隔间》还在找隔间里那个女人。片酬一般，评委会看。灯一直亮，不招，也不哭。',
      '《隔间》只有二十分钟。圈里有人拿它跟派出所、审讯室那种戏比，说短，但停顿要准。',
    ],
    leads: ['审讯员'],
    supporting: [],
    need: { acting: 70, poise: 64 },
    weights: { acting: 5, poise: 3 },
    shootNeed: 8,
    promoNeed: 2,
    pay: 18000,
    recognition: 22,
    hype: 'award',
    unlock: 'broker',
    highlights: ['director', 'hype'],
    meetNpc: 'shenzhao',
    sceneAt: 6,
    sceneEvent: 'scene-rain',
  }),
  S({
    id: 'sidecast',
    title: '星河渡·宴席一眼',
    type: '大 IP 网剧',
    tags: ['网络剧', '大 IP'],
    theme: '仙侠',
    keywords: ['客串', '宴席', '星河渡'],
    grade: 'B',
    company: '嘉尚影业',
    director: '裴衡',
    writer: '原著改编',
    roleKind: '客串',
    roleName: '宴席上的一眼',
    role: '客串 · 宴席一眼',
    outline: '还是《星河渡》。开年宴上女主路过席面，你没有名字，只有抬头那一眼。原著里这是过场，路透里已经有人在问旁边那个是谁。主演江晚宁、陆承宴已经定了，镜头会扫到你。',
    roleBio: '客串不是路人。这一眼要让人记得，又不能抢女主。原著粉会逐帧看你有没有「出戏」。',
    plot: '出场只有几秒。演得合适会被记住，太用力也很容易抢掉整场的重心。',
    press: [
      '大 IP《星河渡》客串还空一个宴席上的一眼。江晚宁、陆承宴已经定了，席面上还缺一张脸。',
      '《星河渡》开年宴路透。原著粉在逐帧认人：谁是过场，谁是隐藏人物。',
    ],
    leads: ['江晚宁', '陆承宴'],
    supporting: ['许宁'],
    need: { looks: 62, poise: 56, acting: 52 },
    weights: { looks: 3, poise: 3, acting: 2 },
    shootNeed: 4,
    promoNeed: 2,
    pay: 36000,
    recognition: 10,
    hype: 'ip',
    unlock: 'broker',
    highlights: ['cast', 'hype'],
  }),
  S({
    id: 'cpheat',
    title: '对手戏',
    type: '网剧',
    tags: ['网络剧'],
    theme: '都市',
    keywords: ['大厂', '需求会', '欢喜冤家', '切片'],
    grade: 'B',
    company: '浪潮时代',
    director: '陆深',
    writer: '乔南',
    roleKind: '女二',
    roleName: '余棠',
    role: '女二 · 余棠',
    outline: '互联网大厂。女二余棠和男二梁时不是官配，是需求会对到一半开始呛的那一对。嘴硬，镜头却总切到两个人之间。切片会先于正片到达，路人会先嗑这对本。',
    roleBio: '余棠嘴硬。她跟男二互相看不惯，产品会开完，走廊里还在顶。她不是来拆官配的，是那种「工作上谁也不让」的人。',
    plot: '片方看中了你和梁时之前的对手戏，宣传期也会安排双人采访。戏里的针锋相对要演得像真的，戏外却未必说得清。',
    press: [
      '网剧《对手戏》女二还没定。男二是梁时。片方要一对能在需求会上咬着演的人，切片会先于正片到达。',
      '《对手戏》路透出了会议室对吵。弹幕已经在嗑，官配粉已经在骂「又发糖」。',
      '《对手戏》定了双人采访。片方要「工作上合不来」，不要「私下已经好了」的通稿。',
    ],
    leads: ['江晚宁', '梁时'],
    supporting: [],
    need: { acting: 72, looks: 64, speech: 54 },
    weights: { acting: 3, looks: 2, speech: 2, confidence: 1 },
    shootNeed: 12,
    promoNeed: 5,
    pay: 72000,
    recognition: 16,
    hype: 'trade',
    unlock: 'liangshi',
    unlockFavor: 50,
    highlights: ['fame', 'cast'],
  }),
  S({
    id: 'lovevar',
    title: '心动观察',
    type: '恋爱综艺',
    tags: ['综艺'],
    theme: '观察',
    keywords: ['双人', '旅行', '别墅', '切片'],
    grade: 'B',
    company: '星汉文化',
    director: '节目组',
    writer: '环节组',
    roleKind: '嘉宾',
    roleName: '自己',
    role: '飞行嘉宾 · 和梁时一组',
    outline: '旅行恋爱综艺。镜头跟到分房、跟到吃饭、跟到第二天谁先下楼。节目组要一对「有过对手戏」的人，观察室里有人专门猜你们。不是演戏，播出去的样子不全由你们决定。',
    roleBio: '没有剧本角色可以躲。节目会放大你们相处时每一次沉默和犹豫。',
    plot: '你和梁时会被固定分到一组。节目组当然想要暧昧，剪辑也会帮一把。',
    press: [
      '《心动观察》还在找一对有过对手戏的人。节目组要切片：分房、沉默、谁先下楼。',
      '《心动观察》观察室先开。有人已经在猜梁时会跟谁一组，官博还没发名单。',
    ],
    leads: ['梁时'],
    supporting: [],
    need: { speech: 62, looks: 58, confidence: 56 },
    weights: { speech: 3, looks: 2, confidence: 3 },
    shootNeed: 8,
    promoNeed: 4,
    pay: 54000,
    recognition: 12,
    hype: 'trade',
    unlock: 'liangshi',
    unlockFavor: 65,
    highlights: ['fame'],
  }),
  S({
    id: 'goldseat',
    title: '金座',
    type: '都市剧',
    tags: ['上星剧'],
    theme: '资本',
    keywords: ['夜宴', '投资', '女三', '酒桌'],
    grade: 'A',
    company: '嘉尚影业',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女三',
    roleName: '顾家的客人',
    role: '女三 · 宴会上的人',
    outline: '滨江夜宴。投资人把项目按在转盘边上谈。女三是顾家请来的客人，不是花瓶——席面上谁先举杯、谁把话挡回去，比正戏还要准。顾宴川投了这部，角色却不是礼物。',
    roleBio: '她不是女主。她知道自己为什么被请来，也知道哪句话不能接。灯是暖的，话是冷的。',
    plot: '顾宴川是投资人，导演和选角另有判断。拿到以后也得在镜头前站得住。夜宴、黄酒、合同，都要拍得像真的酒桌。',
    press: [
      '《金座》女三还空着。闻疏的本，顾宴川投的。滨江夜宴，不是花瓶，是能把话挡回去的人。',
      '《金座》酒桌戏先传。有人说像纪实，有人说「又是资本局」。女三那席还没定。',
      '《金座》选角极慢。投资人盯着，导演也盯着。通稿写「客人」，剧本写的是能让男主当场接不上的人。',
    ],
    leads: ['江晚宁', '陆承宴'],
    supporting: ['宋晚'],
    need: { acting: 114, poise: 108, speech: 92, looks: 96 },
    weights: { acting: 3, poise: 3, speech: 2, looks: 2 },
    shootNeed: 14,
    promoNeed: 5,
    pay: 96000,
    recognition: 22,
    hype: 'trade',
    unlock: 'guyan',
    unlockFavor: 55,
    highlights: ['fame', 'director'],
    investor: 'guyan',
  }),
  S({
    id: 'peppercourt',
    title: '椒房春',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '后宫',
    keywords: ['后宫', '年氏', '更衣', '圣眷'],
    grade: 'S',
    fromYear: 2,
    company: '嘉尚影业',
    director: '邢未',
    writer: '流朱',
    roleKind: '女二',
    roleName: '蕙嫔',
    role: '女二 · 蕙嫔',
    outline: '后宫不是打戏。更衣、赐食、一句话能让人在宫里活过冬天。蕙嫔不是女主：她是年家送进来的人，圣眷来得快，也去得快。她要在女主还没站稳时，把自己活成宫里的一条路——谁先低头、谁先笑、药碗从哪只手递出去，都是戏。',
    roleBio: '蕙嫔入宫时还不会看人脸色。后来她会了，却仍有一处不肯让。难演的不是狠，是她明明知道规则，仍要在某一年把真心拿出来；也难在圣眷还在时，已经听见它离开的声音。',
    plot: '仪态、对视、药碗和诏书。服化道会先被骂，成片才见人。宫斗最怕演成撕扯。邢未不爱哭戏，要的是谁先把筷子放下。',
    press: [
      '古装《椒房春》女二蕙嫔还没定。后宫、年家、更衣。圈里拿它跟那些一宫里活十年的戏比，原著粉已经在列不能改的三件事。',
      '《椒房春》选角三轮。女主已定江晚宁，女二要能把「圣眷」演成负担，不是演成泼。邢未看了几轮，还没点头。',
      '《椒房春》服化道路透。头面比人先出圈，妆造说成片为准。赐食那场围读流出半页，有人说像真的宫里。',
      '《椒房春》白玉兰观察名单里有这部。女二戏份重，评委会不会只看女主。片方说先把人演住，奖以后再说。',
    ],
    leads: ['江晚宁', '陆承宴'],
    supporting: ['陈晚秋'],
    need: { acting: 128, poise: 132, looks: 108, wit: 112 },
    weights: { acting: 4, poise: 4, wit: 3, looks: 2 },
    shootNeed: 22,
    promoNeed: 7,
    pay: 320000,
    recognition: 36,
    hype: 'ip',
    awardTrack: true,
    highlights: ['hype', 'cast'],
  }),
  S({
    id: 'redcase',
    title: '赤焰案',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '朝堂',
    keywords: ['旧案', '郡主', '挂帅', '朝堂'],
    grade: 'S',
    fromYear: 2,
    company: '星汉文化',
    director: '齐衡',
    writer: '海宴客',
    roleKind: '女二',
    roleName: '梁郡主',
    role: '女二 · 梁郡主',
    outline: '朝堂上的旧案翻出来，死人要被写成叛徒。梁郡主不是来联姻的：她能挂帅，也能在宗庙前把话说完。男主是那个用病骨撑着翻案的人。她要演的是「我信你，但不为你放弃自己的军」——拒婚不是傲，是把军印放下，也把脊梁留下。',
    roleBio: '梁郡主坐得直，话少。她不是女主，却是这部里唯一能把「公道」说出口而不显得幼稚的人。联姻那场，她可以拒。难演的不是飒，是她把人救出来以后，仍不肯把命交给任何人。',
    plot: '朝会、军报、夜谈。齐衡不爱哭戏。郡主的戏在站姿、拒婚和点将，不在落泪。朝仪错一个，整条作废。',
    press: [
      '《赤焰案》梁郡主还在选。朝堂旧案、挂帅、拒婚。有人说这是男主的戏，有人说郡主那场能撑半部。',
      '《赤焰案》死人、军权、一句「臣敢请」。女二不是花瓶郡主。何朗已经定了，病骨那场先拍。',
      '《赤焰案》围读流出拒婚词。片方要「不柔、不泼、把军印放下也把脊梁留下」。原著粉说别写成爱上男主就卸甲。',
      '金桂不看剧，白玉兰会。齐衡的组，术语换成朝仪，错一个，整条作废。点将那场要过顾问。',
    ],
    leads: ['何朗'],
    supporting: ['裴渡'],
    need: { acting: 132, poise: 128, speech: 118, fitness: 96 },
    weights: { acting: 4, poise: 3, speech: 3, fitness: 1 },
    shootNeed: 20,
    promoNeed: 6,
    pay: 280000,
    recognition: 40,
    hype: 'ip',
    awardTrack: true,
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'dust',
    title: '隐尘',
    type: '电影',
    tags: ['电影'],
    theme: '农村',
    keywords: ['土地', '夫妻', '病', '沉默'],
    grade: 'S',
    fromYear: 2,
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女主',
    roleName: '曹英',
    role: '女主 · 曹英',
    outline: '西北。夫妻种地，病来了，地还在。几乎没有金句，也没有翻盘。女主不是来哭穷的：她要把日子过完，把一袋粮食从集上背回去。圈里当冲奖看，院线未必肯排。接了，就是拿当红档期去换一次被评委看见。',
    roleBio: '曹英话少，手粗。她爱她丈夫，方式是把药钱省下来。镜头会跟着她走路、做饭、不解释。妆面要往土里靠，漂亮是减分。',
    plot: '关门拍。沈照只说再短一点。片酬低，档期长。评委会盯这部，资本会问你为什么接。女主奖开始观察，赢几乎轮不到第二年。',
    press: [
      '沈照新片《隐尘》找女主。西北、土地、病。没有对白也能把人看哭的那种，院线排片不会多。',
      '《隐尘》片酬低，冲奖向。有人说这是今年电影的正途，有人说接了就是浪费当红档期。片方不谈女主奖，只谈「她像不像在地里站过」。',
      '《隐尘》选角极慢。沈照看了很多人。化妆、手、走路，先过，台词往后放。',
      '金桂奖内定传闻又起。组委会说请以公布为准。《隐尘》已经在观察名单里。女主栏空着。',
    ],
    leads: ['何朗'],
    supporting: [],
    need: { acting: 155, poise: 148, wit: 88, looks: 62 },
    weights: { acting: 5, poise: 4, looks: 1 },
    shootNeed: 24,
    promoNeed: 5,
    pay: 48000,
    recognition: 52,
    hype: 'award',
    awardTrack: true,
    meetNpc: 'shenzhao',
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'youngbook',
    title: '少年书',
    type: '电影',
    tags: ['电影'],
    theme: '校园',
    keywords: ['校园', '保护', '录像', '成年'],
    grade: 'A',
    fromYear: 2,
    company: '嘉尚影业',
    director: '老钱',
    writer: '周湛',
    roleKind: '女二',
    roleName: '魏早',
    role: '女二 · 魏早',
    outline: '高中。有人被欺到不敢回家，有人把录像存在手机里。女主不是你。魏早是那个看起来站在施暴那边、其实把U盘藏起来的人。电影不靠热血，靠谁敢把东西交出去。',
    roleBio: '魏早成绩好，话硬。她不是来拯救的，是第一次决定站哪边。演飘了会变成「良心发现的恶人」。',
    plot: '校园实拍。尺度会审。有几场不能哭，只能把东西放下。',
    press: [
      '电影《少年书》女二魏早还在选。校园、录像、保护。尺度会审，片方要「不像说教」。',
      '《少年书》一看完不敢说话。女二不是女主的影子：她看起来站在施暴那边，U盘却在她抽屉里。',
      '《少年书》入围观察。金桂看校园片少，但这部口碑会先于票房到。几场不能哭，只能把东西放下。',
    ],
    leads: ['白疏影'],
    supporting: ['阮清'],
    need: { acting: 124, poise: 116, speech: 88 },
    weights: { acting: 4, poise: 3, speech: 2 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 86000,
    recognition: 28,
    hype: 'award',
    awardTrack: true,
  }),
  S({
    id: 'northwind',
    title: '风过北河',
    type: '上星剧',
    tags: ['上星剧'],
    theme: '扫黑',
    keywords: ['扫黑', '律师', '父子', '一省'],
    grade: 'S',
    fromYear: 2,
    company: '天奇影视',
    director: '邢伟',
    writer: '徐纪周客',
    roleKind: '女二',
    roleName: '忻律',
    role: '女二 · 律师',
    outline: '一省的案子从夜市摊翻到厅局。女二是律师，不是女主：她接的是没人敢接的委托，酒桌上把话挡回去，卷宗里把人救出来。父子那条线不归她，但她知道那张桌子上谁在说谎。',
    roleBio: '忻律不吼。她把证据放在桌上，让别人先吵。台词是法条和人名，不能错。',
    plot: '实景、群演、注水传闻会先于正片。律师戏要过顾问，酒桌戏要像真的。',
    press: [
      '《风过北河》女二律师还没定。扫黑、父子、一省的案子。预告会先吵番位。',
      '《风过北河》注水传闻已经出来。编剧把开会写成三集。律师那场，顾问组盯口型。',
      '《风过北河》被写成今年的年度剧。女二不是花瓶，卷宗和酒桌都是戏。真实原型传闻已经压了一轮。',
    ],
    leads: ['龙武山', '裴渡'],
    supporting: ['许宁'],
    need: { acting: 130, speech: 126, wit: 120, poise: 100 },
    weights: { speech: 4, acting: 3, wit: 4 },
    shootNeed: 21,
    promoNeed: 7,
    pay: 210000,
    recognition: 34,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'returner',
    title: '故人归',
    type: '古装网剧',
    tags: ['网络剧', '大 IP', '古装'],
    theme: '仙侠',
    keywords: ['女主', '重逢', '天界', '大 IP'],
    grade: 'S',
    fromYear: 2,
    company: '嘉尚影业',
    director: '裴衡',
    writer: '原著改编',
    roleKind: '女主',
    roleName: '阿念',
    role: '女主 · 阿念',
    outline: '又一部仙侠大 IP。女主还没定死，试镜已经三轮。阿念不是《星河渡》那个用感情换位置的人：她是自己走上天界、也自己把命押上的人。粉籍会先骂名字，资本会盯脸。第二年能试女主，不等于能签下来。',
    roleBio: '阿念看起来软，决定很快。她不是来被救的。试镜要唱、要打、要把「我认得你」演成劫，不是演成甜。',
    plot: '女主竞争。你可能试了也拿不到。拿到了，超点、服化道、番位会把你先吵一遍。演技不够，裴衡不会为了流量改口。',
    press: [
      '大 IP《故人归》女主还没定。三轮试镜。原著粉已经准备退款。',
      '《故人归》和《星河渡》热度对打。有人说市场吃不下两部仙侠，有人说就这一年。',
      '《故人归》选角名单泄漏。女主那栏空着。裴衡说要能把重逢演成劫。资本要脸，导演要那场不说话的戏。',
    ],
    leads: ['陆承宴'],
    supporting: ['江晚宁'],
    need: { acting: 142, looks: 128, confidence: 122, poise: 118 },
    weights: { acting: 4, looks: 3, confidence: 3, poise: 2 },
    shootNeed: 23,
    promoNeed: 8,
    pay: 620000,
    recognition: 38,
    hype: 'ip',
    highlights: ['hype', 'cast'],
  }),
  S({
    id: 'lotusford',
    title: '莲花渡',
    type: '古装网剧',
    tags: ['网络剧', '古装'],
    theme: '江湖',
    keywords: ['江湖', '旅店', '探案', '女二'],
    grade: 'A',
    fromYear: 2,
    company: '浪潮时代',
    director: '闵秋',
    writer: '方简',
    roleKind: '女二',
    roleName: '渡娘',
    role: '女二 · 渡口的人',
    outline: '江湖不是宫斗。旅店、渡口、一桩桩案子。女二是渡口上那个把船撑走的人：知道男主是谁，不说破，也不跟他走。',
    roleBio: '渡娘看起来闲。她把客人送走，把尸体从夜里捞起来，第二天照常开船。',
    plot: '动作不多，案子要清楚。女二戏份容易被剪，演得住才会留。',
    press: [
      '《莲花渡》女二还在选。江湖探案，不是宫斗。渡口那场，片方要「知道也不说破」。',
      '《莲花渡》男主番位已定。女二戏份会不会被剪，看成片。',
    ],
    leads: ['何朗'],
    supporting: ['裴渡'],
    need: { acting: 118, speech: 108, poise: 110 },
    weights: { acting: 3, speech: 3, poise: 2 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 128000,
    recognition: 24,
    hype: 'trade',
  }),
  S({
    id: 'southwind',
    title: '南风寄',
    type: '电视剧',
    tags: ['上星剧'],
    theme: '小城',
    keywords: ['小城', '风', '寄居', '慢'],
    grade: 'A',
    fromYear: 2,
    company: '星汉文化',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女配角',
    roleName: '铺子',
    role: '女配 · 开铺的人',
    outline: '去一个有风的小城住下来。女主不是你。你是那家铺子：收信、借伞、把外乡人留下来吃一碗面。戏慢，没有爽点，口碑会两极。',
    roleBio: '她把铺子开好，不问来的人要去哪。真正难演的是不催情节。',
    plot: '实景、风、长镜头。闻疏不爱快剪。',
    press: [
      '《南风寄》还在补铺子那个女人。小城、慢、没有爽点。有人说今年需要这种，有人说播不完。',
      '《南风寄》路透全是风和电线。弹幕会吵「剧呢」。',
    ],
    leads: ['宋知夏'],
    supporting: [],
    need: { acting: 114, poise: 120, speech: 86 },
    weights: { acting: 3, poise: 4 },
    shootNeed: 14,
    promoNeed: 4,
    pay: 72000,
    recognition: 22,
    hype: 'award',
  }),
  S({
    id: 'weiyang',
    title: '未央辞',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '后宫',
    keywords: ['女主', '后宫', '从妃到后', '年'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '邢未',
    writer: '流朱',
    roleKind: '女主',
    roleName: '许蘅',
    role: '女主 · 许蘅',
    outline: '后宫从更衣走到掌事。女主不是生来就会斗：她先被送进来，后来才把自己活成宫里的规矩。蕙嫔若还在，是她的对照。这部要的是「一步步把命拿回来」，不是开局就狠。十年同一张脸，评委先看你有没有把季节演开。',
    roleBio: '许蘅入宫时会看病历，不会看人。后来她会了。女主要能把十年演成同一张脸的不同季节：软的那年、狠的那年、把诏书按住的那年，不能演成三个人。',
    plot: '女主本。档期以年计。白玉兰、国剧都会盯。拿奖很难，拍砸了更难看。邢未不爱开局就狠，要她把字说完。',
    press: [
      '《未央辞》女主还在选。从更衣到掌事，十年。圈里说这是宫斗正途，也有人说吃力不讨好。',
      '《未央辞》海报一出，评论只记得旧的那部一宫十年的戏。邢未说这次不靠那部活。',
      '《未央辞》女主试镜要求读一整段「我不信命」。邢未不爱哭，要她把字说完。江晚宁已定皇后线，女主栏仍空着。',
      '白玉兰观察名单里有这部。女主奖开始有人问，评委会把十年拆开看。拍飘了，比女二更难看。',
    ],
    leads: ['陆承宴'],
    supporting: ['陈晚秋', '江晚宁'],
    need: { acting: 158, poise: 155, wit: 140, looks: 118 },
    weights: { acting: 5, poise: 4, wit: 3, looks: 2 },
    shootNeed: 26,
    promoNeed: 8,
    pay: 880000,
    recognition: 48,
    hype: 'ip',
    awardTrack: true,
    highlights: ['hype', 'director'],
  }),
  S({
    id: 'shore',
    title: '岸边',
    type: '电影',
    tags: ['电影'],
    theme: '文艺',
    keywords: ['海边', '返乡', '女主', '冲奖'],
    grade: 'S',
    fromYear: 3,
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女主',
    roleName: '岸',
    role: '女主 · 岸',
    outline: '海边。她从城里回来，不解释，把网补上。电影不靠台词赢。金桂最佳女主角会看这部：冷、慢、卖座不一定。接了，就是拿档期去换一次被看见。影后不是年终礼物，评委也不看你热搜。',
    roleBio: '岸几乎不哭。她把网补好，把信烧掉，把人送走。女主要能把「回来」演满，而不是把「成功」演满。漂亮是减分。',
    plot: '关门拍。沈照不说戏。片酬普通，评委会盯女主。第三年能进组，不等于典礼会念你的名字。',
    press: [
      '沈照《岸边》找女主。海边、返乡、几乎不靠台词。圈里当冲影后看。',
      '《岸边》院线排片不会多。影评号已经在写「今年会盯的女主」。出海物料在做，翻译先把沉默译丢了。',
      '《岸边》选角比《未命名》更慢。沈照只说她要像在岸上站过。有人劝你别拿档期去赌冷片。',
    ],
    leads: [],
    supporting: ['何朗'],
    need: { acting: 168, poise: 162, wit: 118, looks: 70 },
    weights: { acting: 5, poise: 4, wit: 2 },
    shootNeed: 24,
    promoNeed: 6,
    pay: 120000,
    recognition: 60,
    hype: 'award',
    awardTrack: true,
    meetNpc: 'shenzhao',
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'ninegates',
    title: '九重门',
    type: '大 IP 网剧',
    tags: ['网络剧', '大 IP'],
    theme: '仙侠',
    keywords: ['女主', '天门', '粉籍'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '裴衡',
    writer: '原著改编',
    roleKind: '女主',
    roleName: '九门',
    role: '女主 · 九门',
    outline: '仙侠女主。不是女二那条把感情当筹码的命：她推开的是门，不是人。粉籍、服化道、超点、出海物料会把你先吵死。',
    roleBio: '九门看起来冷。她把门推开，把旧名字留下。女主要能打、能把重逢压住。',
    plot: '大 IP 女主。资本盯脸，导演盯一场不说话的戏。',
    press: [
      '《九重门》女主还没定。大 IP，出海物料已经在做。粉籍比剧组快。',
      '《九重门》服化道路透。头套又出戏。超点预告先出女主那一眼。',
    ],
    leads: ['陆承宴'],
    supporting: ['江晚宁'],
    need: { acting: 152, looks: 140, confidence: 132, poise: 128 },
    weights: { acting: 4, looks: 3, confidence: 3 },
    shootNeed: 24,
    promoNeed: 9,
    pay: 980000,
    recognition: 44,
    hype: 'ip',
  }),
  S({
    id: 'people-sea',
    title: '人海',
    type: '年代剧',
    tags: ['上星剧'],
    theme: '年代',
    keywords: ['一家人', '三十年', '群像'],
    grade: 'A',
    fromYear: 3,
    company: '天奇影视',
    director: '邢伟',
    writer: '梁晓声客',
    roleKind: '女主',
    roleName: '周蓉',
    role: '女主 · 周蓉',
    outline: '一家人三十年。女主从姑娘演到把孩子送走。群像里要站得住，注水会把开会写成三集。真假年代感会先被骂。',
    roleBio: '周蓉不是完人。她把家里的事做完，把外面的事忍下。女主要能把年龄演开。',
    plot: '跨年拍摄。妆容、口音、年代物不能错。',
    press: [
      '《人海》女主还在选。三十年群像。有人说像正剧，有人说注水。',
      '《人海》预告出了晚饭那一桌。弹幕在刷「我家也是这样过来的」。',
    ],
    leads: ['何朗', '龙武山'],
    supporting: ['宋知夏'],
    need: { acting: 148, poise: 140, speech: 110 },
    weights: { acting: 4, poise: 3, speech: 2 },
    shootNeed: 22,
    promoNeed: 6,
    pay: 360000,
    recognition: 36,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'sister',
    title: '她的小孩',
    type: '电影',
    tags: ['电影'],
    theme: '家庭',
    keywords: ['姐姐', '抚养', '选择'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '老钱',
    writer: '游晓颖客',
    roleKind: '女主',
    roleName: '安然',
    role: '女主 · 安然',
    outline: '姐姐要不要把弟弟留下。电影把选择摊在桌上，不给正确答案。女主不是来感动观众的：她要在医院走廊、律师事务所和夜里把「我可不可以过自己的日子」说完。',
    roleBio: '安然会笑，也会把文件推回去。女主要能把「不想当妈」演得不是狠。',
    plot: '现实题材，会审。冲奖，也容易被写成话题。',
    press: [
      '电影《她的小孩》找女主。抚养、选择、不当妈算不算狠。金桂会看，广场也会骂。',
      '《她的小孩》看完不敢说话。女主档期要让。会审会盯「选择」两个字怎么拍。',
    ],
    leads: [],
    supporting: ['白疏影'],
    need: { acting: 160, poise: 150, speech: 122, wit: 110 },
    weights: { acting: 5, poise: 3, speech: 3 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 160000,
    recognition: 50,
    hype: 'award',
    awardTrack: true,
  }),
  S({
    id: 'brocade',
    title: '锦衣夜',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '宅门',
    keywords: ['宅门', '嫡庶', '女工', '明媒'],
    grade: 'A',
    fromYear: 2,
    company: '嘉尚影业',
    director: '闵秋',
    writer: '流朱',
    roleKind: '女二',
    roleName: '盛宜',
    role: '女二 · 盛宜',
    outline: '宅门不是后宫。盛宜不是女主：她是嫡房里那个会女工、会看人、把明媒正娶四个字咬死的人。女主从庶房里往上走，她要演的是「规矩站在我这边」——直到规矩反过来咬她。',
    roleBio: '盛宜话不多，针脚密。她不是来作的，是真的信这套规矩能护住她。难演的不是骄，是她把人逼到墙角时，自己也没有退路。',
    plot: '女工、宴席、分家。闵秋要针脚和落座，不要撕打。服化道会先被夸，人要后到。',
    press: [
      '古装《锦衣夜》女二盛宜还在选。宅门、嫡庶、女工。不是后宫，是把明媒正娶咬死的人。',
      '《锦衣夜》围读流出分家那场。女二不是作精，是真的信规矩。原著粉说别写成恶毒嫡姐。',
      '《锦衣夜》女主已定。女二戏份重，白玉兰会不会看宅斗，看成片。',
    ],
    leads: ['宋知夏'],
    supporting: ['陈晚秋'],
    need: { acting: 122, poise: 126, wit: 110, looks: 100 },
    weights: { acting: 4, poise: 4, wit: 3 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 168000,
    recognition: 28,
    hype: 'trade',
    awardTrack: true,
    highlights: ['hype'],
  }),
  S({
    id: 'longnight',
    title: '长夜未明',
    type: '电影',
    tags: ['电影'],
    theme: '悬疑',
    keywords: ['小城', '录像', '证人', '沉默'],
    grade: 'A',
    fromYear: 2,
    company: '星汉文化',
    director: '老钱',
    writer: '周湛',
    roleKind: '女配角',
    roleName: '证人',
    role: '女配 · 不说话的人',
    outline: '小城。孩子、录像、一桩翻了十几年的案子。你不是女主。你是那个把带子藏过、后来又坐在询问室里不说话的人。电影不靠反转金句，靠谁先把沉默撑破。',
    roleBio: '她看起来普通。真正难演的是她知道，却把话咽回去的那几年。哭是减分。',
    plot: '东北实景。尺度会审。有几场只能坐着，把烟灰弹直。口碑会先于票房到。',
    press: [
      '电影《长夜未明》还在补证人。小城、录像、不说话的人。真实案件联想已经压了一轮。',
      '《长夜未明》询问室那场先传。有人说像纪录片，有人说太冷。女配不是来解释案情的。',
      '金桂看这种片子。女配也能进候选。片方不谈奖，只谈「她像不像在那座城里住过」。',
    ],
    leads: ['何朗'],
    supporting: ['白疏影'],
    need: { acting: 126, poise: 130, speech: 70 },
    weights: { acting: 5, poise: 4, speech: 1 },
    shootNeed: 14,
    promoNeed: 4,
    pay: 62000,
    recognition: 30,
    hype: 'award',
    awardTrack: true,
    highlights: ['director'],
  }),
  S({
    id: 'counter',
    title: '柜台',
    type: '电影',
    tags: ['电影'],
    theme: '现实',
    keywords: ['药', '柜台', '假药', '病人'],
    grade: 'S',
    fromYear: 2,
    company: '星汉文化',
    director: '老钱',
    writer: '唐纸',
    roleKind: '女二',
    roleName: '药房',
    role: '女二 · 把药递出去的人',
    outline: '药很贵。有人从柜台把仿制药递出去，有人因此能再活一年。女主不是你。你是药房里那个知道风险、仍把药箱打开的人。电影会让广场骂，评委会盯「像不像真的把药递过手」。',
    roleBio: '她不是圣人。她把价钱报清楚，把后果也说清楚，然后把药推过玻璃。难演的不是哭，是她报完价以后不再解释。',
    plot: '实景、病人、会审。片酬普通。冲奖向。女二戏份容易被写成工具人，演住了才会留在成片里。',
    press: [
      '电影《柜台》女二还在选。药房、仿制药、把药递过玻璃的人。会审已经来过一轮。',
      '《柜台》片酬普通，冲奖向。有人说这是正途，有人说接了就是往舆论上撞。',
      '《柜台》选角要「她像在药房站过」。手、口型、报药名，顾问组盯。金桂观察名单里有这部。',
    ],
    leads: ['龙武山'],
    supporting: [],
    need: { acting: 140, poise: 132, speech: 118, looks: 68 },
    weights: { acting: 5, speech: 3, poise: 3, looks: 1 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 54000,
    recognition: 38,
    hype: 'award',
    awardTrack: true,
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'nightward',
    title: '白夜班',
    type: '上星剧',
    tags: ['上星剧'],
    theme: '医疗',
    keywords: ['外科', '夜班', '一台戏', '连轴'],
    grade: 'A',
    fromYear: 2,
    company: '天奇影视',
    director: '齐衡',
    writer: '周湛',
    roleKind: '女二',
    roleName: '值班',
    role: '女二 · 外科值班',
    outline: '比走廊里的实习更重的一台戏。女二是外科值班：她把人从台上接下来，也把坏消息送出手术室。术语不能错，连轴也不能演成苦情。',
    roleBio: '她不吼。她把手套摘下来，把话一次说完。难演的不是救人，是她把「没了」三个字送到家属面前。',
    plot: '齐衡组。医顾问进组。口型、病历、推床路线都要过。连轴拍，化妆要往虚里靠，不能妆造比人先出圈。',
    press: [
      '《白夜班》女二外科值班还没定。齐衡的组，术语错一个，整条作废。比《白大褂》更重。',
      '《白夜班》医顾问组进组。手术室那场要过三轮。有人劝你别拿档期去熬夜班。',
      '《白夜班》预告会先出推床。弹幕会吵「又是医疗剧」，成片才见人。',
    ],
    leads: ['何朗'],
    supporting: ['许宁'],
    need: { acting: 124, speech: 120, poise: 108, fitness: 88 },
    weights: { acting: 4, speech: 4, poise: 2 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 142000,
    recognition: 26,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'painted',
    title: '扮相',
    type: '电影',
    tags: ['电影'],
    theme: '戏曲',
    keywords: ['戏班', '扮相', '师徒', '台上'],
    grade: 'S',
    fromYear: 3,
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女主',
    roleName: '程秋',
    role: '女主 · 程秋',
    outline: '戏班。她在台上是一个人，台下是另一个人。电影把师徒、班主、一场必须唱完的戏摊在桌上，不给革命口号。金桂最佳女主角会看这部：扮相、嗓子、把命押在一场上。接了，才艺和演技都要过，漂亮是减分。',
    roleBio: '程秋会唱。她把脸涂上，就把自己留下。女主要能把「我是戏」和「我还是人」演成同一副骨架，不能演成两出。',
    plot: '关门拍。唱段要真唱。沈照不说戏。片酬普通，档期长。评委会盯女主，院线不一定排。影后很难，陪跑更常见。',
    press: [
      '沈照《扮相》找女主。戏班、扮相、台上台下不是同一个人。圈里当冲影后看。',
      '《扮相》要真唱。才艺过不了，试镜直接停。有人说这是今年电影最难的女主。',
      '《扮相》选角极慢。沈照要「她像把命押在一场上」。出海物料在做，翻译先把唱段译丢了。',
      '金桂女主观察。陈晚秋陪跑过这种片子。片方不承诺奖，只谈你敢不敢把脸涂上。',
    ],
    leads: [],
    supporting: ['何朗'],
    need: { acting: 172, talent: 148, poise: 160, looks: 72 },
    weights: { acting: 5, talent: 4, poise: 4, looks: 1 },
    shootNeed: 26,
    promoNeed: 6,
    pay: 96000,
    recognition: 58,
    hype: 'award',
    awardTrack: true,
    meetNpc: 'shenzhao',
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'cipher',
    title: '密信',
    type: '电影',
    tags: ['电影'],
    theme: '谍战',
    keywords: ['密馆', '两套话', '一张脸', '夜里'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '邢未',
    writer: '海宴客',
    roleKind: '女主',
    roleName: '顾青',
    role: '女主 · 顾青',
    outline: '密馆。一张脸要演两套话：白天是夫人，夜里把信送出去。电影不靠枪林弹雨，靠谁先把眼神露馅。金桂会看，广场会吵「她到底站哪边」。接了，就是把妩媚和狠放在同一场里，还不能演成两个角色。',
    roleBio: '顾青会笑。她把茶端稳，把信藏好。女主要能把「我在说谎」演成日常，而不是演成高潮。',
    plot: '会审。邢未不爱喊口号。片酬中等。评委会盯女主一场不说话的戏。卖座不一定。',
    press: [
      '电影《密信》找女主。密馆、两套话、一张脸。圈里当冲奖看，也有人说尺度过不了。',
      '《密信》试镜要一场把茶端稳。邢未说别演间谍，演一个会把日子过完的人。',
      '《密信》会审已经来过。片方改了两稿。金桂观察，女主栏空着。',
    ],
    leads: ['陆承宴'],
    supporting: ['陈晚秋'],
    need: { acting: 166, poise: 158, wit: 142, speech: 128 },
    weights: { acting: 5, poise: 4, wit: 3, speech: 2 },
    shootNeed: 20,
    promoNeed: 6,
    pay: 180000,
    recognition: 54,
    hype: 'award',
    awardTrack: true,
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'citylamp',
    title: '城中灯',
    type: '上星剧',
    tags: ['上星剧'],
    theme: '家庭',
    keywords: ['都市', '家庭', '不是甜宠', '贺岁'],
    grade: 'A',
    fromYear: 3,
    company: '天奇影视',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女主',
    roleName: '灯',
    role: '女主 · 灯',
    outline: '都市家庭，不是甜宠。女主把家里的账和外面的脸同时撑住。贺岁档会要笑，成片里她不一定给。收视会吵，尺度会审，国剧会看她有没有把「过年」演成压力。',
    roleBio: '灯会应酬。她把饭桌上的话挡回去，把孩子的事按住。女主要能把体面演满，也把体面后面的那一口气留下。',
    plot: '实景、家庭、贺岁档。闻疏不爱金句。女主本，不是冲影后，是把一线坐住的那种上星。',
    press: [
      '《城中灯》女主还在选。都市家庭，不是甜宠。贺岁档要笑，片方要「别演成鸡汤」。',
      '《城中灯》尺度会审。收视会先吵番位。有人说这是今年要的年味，有人说播不完。',
    ],
    leads: ['裴渡'],
    supporting: ['宋知夏'],
    need: { acting: 146, poise: 138, speech: 122, looks: 108 },
    weights: { acting: 4, poise: 3, speech: 3 },
    shootNeed: 20,
    promoNeed: 7,
    pay: 420000,
    recognition: 34,
    hype: 'trade',
    awardTrack: true,
  }),
]

export function scriptById(id: string): ScriptDef | undefined {
  return SCRIPTS.find((s) => s.id === id)
}

export function rumorLine(script: ScriptDef, week = 1): string {
  if (script.press.length) {
    return script.press[(week + script.id.length) % script.press.length]
  }
  return `《${script.title}》还在选${roleLine(script)}。${script.director}还没点头。`
}

export function scriptMatch(attrs: Attrs, script: ScriptDef): number {
  let num = 0
  let den = 0
  for (const k of ATTR_KEYS) {
    const need = script.need[k]
    if (!need) continue
    const w = script.weights[k] ?? 1
    num += Math.min(1.25, attrs[k] / need) * w
    den += w
  }
  return den ? Math.min(100, Math.round((100 * num) / den)) : 50
}

export function matchWord(n: number): string {
  if (n >= 82) return '倒像你'
  if (n >= 64) return '能试试'
  if (n >= 48) return '有点勉强'
  return '现在不像'
}

export function canTakeScript(
  attrs: Attrs,
  script: ScriptDef,
  career?: { recognition: number; fans: number },
): boolean {
  if (!ATTR_KEYS.every((k) => (script.need[k] ?? 0) <= attrs[k])) return false
  if (script.awardTrack) {
    if (script.roleTier === 'lead') {
      if ((career?.recognition ?? 0) < 80) return false
      if ((career?.fans ?? 0) < 60000) return false
    } else {
      if ((career?.recognition ?? 0) < 32) return false
      if ((career?.fans ?? 0) < 20000) return false
    }
  }
  return true
}

export function hypeLine(script: ScriptDef): string {
  if (script.hype === 'ip') return '原著读者很多，选角消息一直有人关注。'
  if (script.hype === 'award') return '导演和剧本更受业内关注，商业回报未必稳定。'
  if (script.roleTier === 'second' || script.roleTier === 'lead') return '角色戏份较重，试镜会有多轮。'
  if (script.grade === 'S' || script.grade === 'A') return '制作周期较长，主创团队已经确定。'
  return ''
}

const HIGHLIGHT_NAME: Record<ScriptHighlight, string> = {
  fame: '项目讨论度较高',
  director: '导演受业内关注',
  cast: '主要演员阵容已经确定',
  hype: '前期宣传投入较多',
}

export function highlightLine(script: ScriptDef): string {
  if (!script.highlights?.length) return ''
  return `${script.highlights.map((h) => HIGHLIGHT_NAME[h]).join('；')}。`
}

export function roleLine(script: ScriptDef): string {
  if (script.track === 'music') {
    if (script.roleTier === 'second') return '独唱。有名字。'
    return '声音。不一定有名字。'
  }
  if (script.track === 'variety') return script.roleKind
  if (script.roleTier === 'lead') return '女主'
  if (script.roleTier === 'second') return '女二'
  if (script.roleTier === 'third') return '女三'
  if (script.roleTier === 'cameo') return '客串'
  return '配角'
}

export function needGaps(attrs: Attrs, script: ScriptDef): { key: AttrKey; need: number; have: number }[] {
  return ATTR_KEYS.filter((k) => script.need[k])
    .map((k) => ({ key: k, need: script.need[k] ?? 0, have: attrs[k] }))
}

export function needLook(script: ScriptDef): string {
  const names = ATTR_KEYS.filter((k) => script.need[k]).map((k) => NEED_NAME[k])
  if (!names.length) return '通告没有注明特别要求。'
  return `试镜要看${names.join('、')}。`
}

export function scheduleLine(script: ScriptDef): string {
  const pay = script.pay > 0 ? `片酬 ${script.pay >= 10000 ? `${(script.pay / 10000).toFixed(1)}万` : `${script.pay}元`}。` : '没有片酬。'
  const dep = script.deposit > 0 ? `定金 ${script.deposit} 元。` : ''
  return `共拍 ${script.shootNeed} 场，需在 ${script.deadlineDays} 天内完成。杀青后另有 ${script.promoNeed} 场宣传。${pay}${dep}`
}

export function monthIndex(week: number): number {
  return Math.floor((week - 1) / 4)
}

function mulberry32(a: number) {
  return () => {
    let t = (a += 0x6d2b79f5)
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function gradeOpen(script: ScriptDef, recognition: number, fans: number, identity: IdentityId): boolean {
  return gradeUnlocked(script.grade, recognition, fans, identity)
}

export type OfferAccess = {
  flags?: Record<string, boolean>
  favor?: Record<string, number>
  met?: Record<string, boolean>
}

function scriptUnlocked(script: ScriptDef, access?: OfferAccess): boolean {
  if (!script.unlock) return true
  const flags = access?.flags ?? {}
  const favor = access?.favor ?? {}
  const met = access?.met ?? {}
  if (script.unlock === 'broker') return Boolean(flags.brokerSpecial)
  if (script.unlock === 'liangshi') return Boolean(met.liangshi) && (favor.liangshi ?? 0) >= (script.unlockFavor ?? 50)
  if (script.unlock === 'guyan') return Boolean(met.guyan) && (favor.guyan ?? 0) >= (script.unlockFavor ?? 55)
  return false
}

export function monthOfferIds(
  seed: number,
  week: number,
  finished: string[],
  filmingIds: string[],
  recognition: number,
  identity: IdentityId,
  track: Track = 'film',
  fans = 0,
  access?: OfferAccess,
): string[] {
  const m = monthIndex(week)
  const year = playYear(week)
  const rng = mulberry32((seed + (m + 1) * 1315423911 + (track === 'music' ? 17 : track === 'variety' ? 31 : 0)) >>> 0)
  const blocked = new Set([...finished, ...filmingIds])
  const pool = SCRIPTS.filter((s) => {
    if (s.track !== track || blocked.has(s.id) || !scriptUnlocked(s, access)) return false
    if ((s.fromYear ?? 1) > year) return false
    if (year >= 2 && s.grade === 'C') return false
    if (!gradeOpen(s, recognition, fans, identity)) return false
    if (s.roleTier === 'lead' && s.awardTrack && (s.hype === 'award' || /电影/.test(s.type))) {
      if (year < 3 && (recognition < 80 || fans < 60000)) return false
      if (year >= 3 && (recognition < 80 || fans < 90000)) return false
    }
    if (s.unlock) return true
    return roleOffered(s.roleTier, recognition, fans, year)
  })
  const specials = pool.filter((s) => s.unlock)
  const regular = pool.filter((s) => !s.unlock)
  const staples = regular.filter((s) => !s.random)
  const extras = regular.filter((s) => s.random && rng() > 0.42)
  let cand = [...staples, ...extras]
  if (cand.length < 3) cand = regular
  if (year >= 2) {
    const now = cand.filter((s) => (s.fromYear ?? 1) === year)
    const older = cand.filter((s) => (s.fromYear ?? 1) < year)
    cand = now.length >= 3 ? now : [...now, ...older]
  }
  const shuffled = [...cand]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  const forced = [...specials]
  for (let i = forced.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1))
    ;[forced[i], forced[j]] = [forced[j], forced[i]]
  }
  const pickSpecial = forced.slice(0, 2)
  const need = Math.max(0, 3 - pickSpecial.length)
  const ids = [...pickSpecial, ...shuffled.filter((s) => !pickSpecial.includes(s)).slice(0, need)].map((s) => s.id)
  return ids.slice(0, 3)
}

export function monthOffers(week: number, finished: string[], filmingId: string | null): ScriptDef[] {
  return monthOfferIds(1, week, finished, filmingId ? [filmingId] : [], 0, 'college')
    .map((id) => scriptById(id))
    .filter((s): s is ScriptDef => Boolean(s))
}
