import type { Attrs, IdentityId, NpcId, Track } from './types'
import { ATTR_KEYS, playYear, type AttrKey } from './types'
import { gradeUnlocked, roleOffered, type RoleTier } from './rank'

export type ScriptGrade = 'C' | 'B' | 'A' | 'S'
export type ScriptHype = 'quiet' | 'trade' | 'ip' | 'award'
export type ScriptHighlight = 'fame' | 'director' | 'cast' | 'hype'
export type ScriptUnlock = 'broker' | 'liangshi' | 'guyan'

export type ScriptDef = {
  id: string
  title: string
  type: string
  track: Track
  tags: string[]
  theme: string
  keywords: string[]
  grade: ScriptGrade
  company: string
  director: string
  writer: string
  roleKind: string
  roleName: string
  role: string
  roleTier: RoleTier
  hype: ScriptHype
  awardTrack: boolean
  outline: string
  roleBio: string
  plot: string
  /** 圈内、原著、选角新闻。通告和手机里会轮到。 */
  press: string[]
  leads: string[]
  supporting: string[]
  need: Partial<Attrs>
  weights: Partial<Attrs>
  shootNeed: number
  deadlineDays: number
  promoNeed: number
  promoDays: number
  pay: number
  deposit: number
  recognition: number
  random?: boolean
  meetNpc?: NpcId
  sceneAt?: number
  sceneEvent?: string
  investor?: NpcId
  unlock?: ScriptUnlock
  unlockFavor?: number
  highlights?: ScriptHighlight[]
  /** 第几年开始出现。第一年的本后面仍可接。 */
  fromYear: number
}

export const GRADE_LABEL: Record<ScriptGrade, string> = {
  C: 'C · 小制作',
  B: 'B · 常规项目',
  A: 'A · 重点项目',
  S: 'S · 行业盯着',
}

export const GRADE_MULT: Record<ScriptGrade, number> = { C: 1, B: 1.45, A: 2.2, S: 3.4 }

export const NEED_NAME: Record<AttrKey, string> = {
  looks: '容貌',
  acting: '演技',
  talent: '才艺',
  speech: '口才',
  poise: '气质',
  fashion: '时尚',
  wit: '智慧',
  fitness: '体能',
  confidence: '自信',
}

export function workWindow(need: number): number {
  return need * 3 + 6
}

function inferRole(kind: string): RoleTier {
  if (/女主/.test(kind)) return 'lead'
  if (/女二/.test(kind)) return 'second'
  if (/女三/.test(kind)) return 'third'
  if (/客串/.test(kind)) return 'cameo'
  return 'support'
}

function inferHype(s: { grade: ScriptGrade; tags?: string[]; type: string }): ScriptHype {
  if (s.tags?.some((t) => /大 IP/.test(t))) return 'ip'
  if (s.grade === 'S' && /电影/.test(s.type)) return 'award'
  if (s.grade === 'S' || s.grade === 'A') return 'trade'
  return 'quiet'
}

function S(
  s: Omit<ScriptDef, 'tags' | 'deposit' | 'promoNeed' | 'promoDays' | 'track' | 'deadlineDays' | 'roleTier' | 'hype' | 'awardTrack' | 'press' | 'fromYear'> & {
    tags?: string[]
    deposit?: number
    promoNeed?: number
    promoDays?: number
    deadlineDays?: number
    track?: Track
    roleTier?: RoleTier
    hype?: ScriptHype
    awardTrack?: boolean
    press?: string[]
    fromYear?: number
  },
): ScriptDef {
  const promoNeed = s.promoNeed ?? 2
  const roleTier = s.roleTier ?? inferRole(s.roleKind)
  const hype = s.hype ?? inferHype(s)
  return {
    ...s,
    track: s.track ?? 'film',
    tags: s.tags ?? [s.type],
    press: s.press ?? [],
    fromYear: s.fromYear ?? 1,
    deposit: s.deposit ?? Math.round(s.pay * 0.2),
    promoNeed,
    deadlineDays: s.deadlineDays ?? workWindow(s.shootNeed),
    promoDays: s.promoDays ?? workWindow(promoNeed),
    roleTier,
    hype,
    awardTrack: s.awardTrack ?? false,
  }
}

export const SCRIPTS: ScriptDef[] = [
  S({
    id: 'store',
    title: '夜班便利店',
    type: '网剧',
    tags: ['网络剧'],
    theme: '都市深夜',
    keywords: ['便利店', '夜班', '沉默', '都市'],
    grade: 'C',
    company: '浪潮时代',
    director: '陈麦',
    writer: '许晚',
    roleKind: '女配角',
    roleName: '小周',
    role: '女配 · 夜班店员',
    outline: '凌晨三点的便利店。夜班店员小周先后遇见离家出走的女孩、刚下夜班的护士和不肯回家的醉汉。天快亮时，她也做了一个关于自己的决定。',
    roleBio: '小周二十四岁，在这家店做了半年。她不爱打听，却很会听人说话。台词不多，大部分情绪都在找零、热饭和短暂的停顿里。',
    plot: '导演想拍得自然，不要刻意煽情。中间有一场临时加戏，会和同组演员正面抢镜头。',
    leads: ['何朗', '江惜'],
    supporting: ['许宁'],
    need: { acting: 46, looks: 42 },
    weights: { acting: 3, looks: 2, speech: 1 },
    shootNeed: 6,
    pay: 6000,
    recognition: 4,
    meetNpc: 'xuning',
    sceneAt: 3,
    sceneEvent: 'scene-store',
  }),
  S({
    id: 'dialogue',
    title: '对白练习',
    type: '毕业短片',
    tags: ['短片', '学院'],
    theme: '校园',
    keywords: ['分手', '对白', '教室'],
    grade: 'C',
    company: '学院工作室',
    director: '韩向秋',
    writer: '韩向秋',
    roleKind: '女配角',
    roleName: '被留下的人',
    role: '女主同学 · 一场对手戏',
    outline: '一间空教室，一对已经决定分手的恋人。两个人都说得很客气，真正想问的话却一句也没说出口。',
    roleBio: '角色没有名字。她明明想挽留，嘴上却只说“路上小心”。这场戏从头到尾都不能哭。',
    plot: '韩老师现场执导，要求很细。拍摄时全班都会在旁边看。',
    leads: ['韩向秋'],
    supporting: [],
    need: { acting: 48, poise: 40 },
    weights: { acting: 4, confidence: 2, poise: 1 },
    shootNeed: 4,
    promoNeed: 1,
    pay: 0,
    deposit: 0,
    recognition: 6,
    sceneAt: 4,
    sceneEvent: 'scene-dialogue',
  }),
  S({
    id: 'vitamin',
    title: '维C广告女配',
    type: '广告',
    tags: ['广告'],
    theme: '商业',
    keywords: ['饮料', '邻家', '干净'],
    grade: 'C',
    company: '星汉文化',
    director: '广告组',
    writer: '品牌部',
    roleKind: '女配角',
    roleName: '回头的那个',
    role: '喝饮料回头的那个',
    outline: '十五秒的饮料广告。你和朋友从便利店出来，喝一口饮料，听见有人叫你，再回头对镜头笑。',
    roleBio: '没有角色名。你是氛围。妆面和走路比台词重要。品牌方坐在监视器后面，会说「再甜一点」，也会说「太甜了」。',
    plot: '品牌要自然、清爽，不能有太重的表演感。拍摄时间不长，但一个回头可能会反复拍很多次。',
    leads: ['顾辞晚'],
    supporting: [],
    need: { looks: 56, fashion: 50 },
    weights: { looks: 4, fashion: 3, confidence: 1 },
    shootNeed: 3,
    pay: 14000,
    recognition: 2,
  }),
  S({
    id: 'lipstick',
    title: '口红色号 08',
    type: '广告',
    tags: ['广告'],
    theme: '美妆',
    keywords: ['口红', '特写', '时尚'],
    grade: 'C',
    company: '星汉文化',
    director: '品牌影像组',
    writer: '策划',
    roleKind: '女配角',
    roleName: '08 号色',
    role: '涂口红的侧脸',
    outline: '只有嘴和锁骨入镜。品牌不要明星脸，要「像会买这支的人」。',
    roleBio: '没有台词，只有侧脸和唇部特写。妆面、眼神和拿口红的动作都要配合镜头。',
    plot: '棚拍一天，现场会试很多种灯光和角度。定金随合同先结。',
    leads: [],
    supporting: [],
    need: { looks: 62, fashion: 56, confidence: 44 },
    weights: { looks: 4, fashion: 4 },
    shootNeed: 2,
    promoNeed: 1,
    pay: 22000,
    recognition: 2,
    random: true,
  }),
  S({
    id: 'summer',
    title: '盛夏未完',
    type: '网剧',
    tags: ['网络剧'],
    theme: '青春',
    keywords: ['音乐学院', '室友', '选秀', '夏天'],
    grade: 'B',
    company: '浪潮时代',
    director: '陆深',
    writer: '乔南',
    roleKind: '女二',
    roleName: '林夏',
    role: '女二 林夏',
    outline: '县城女生考进音乐学院，夏天很长，选拔一场接一场。林夏是女主的室友：白天帮她记词，夜里自己加练。不是恶毒女二，是那种不敢先示弱、选秀里却不肯让的人。',
    roleBio: '林夏十九岁，来自小县城，嘴硬又敏感。室友发烧她会去买药，第二天的名额却一点不让。她怕被落下，比怕被讨厌更厉害。',
    plot: '有一场女主忘词。你伸不伸手，会改林夏的人设，也会改片场关系。学院礼堂、琴房加练、夏夜天台，都是这部要反复拍的地方。',
    press: [
      '陆深在拍青春网剧《盛夏未完》。浪潮时代的B级，讲县城女生考进音乐学院，女二林夏是室友，白天帮人记词，夜里自己加练。这个女二还在选。',
      '《盛夏未完》选秀那几集还没定人。女二林夏要能唱，也要演得过帮完忙转身去赢那场。',
      '《盛夏未完》路透出了琴房加练。唱的是现场还是后期配的，评论已经吵开了。',
    ],
    leads: ['周棠'],
    supporting: ['梁时'],
    need: { acting: 72, talent: 66, looks: 60, confidence: 62 },
    weights: { acting: 3, talent: 3, looks: 2, confidence: 1 },
    shootNeed: 12,
    promoNeed: 4,
    pay: 86000,
    recognition: 18,
    hype: 'trade',
    meetNpc: 'liangshi',
    sceneAt: 6,
    sceneEvent: 'scene-summer',
  }),
  S({
    id: 'nightstudy',
    title: '晚自习以后',
    type: '校园网剧',
    tags: ['网络剧', '校园'],
    theme: '校园',
    keywords: ['高考', '天台', '课代表', '家长群'],
    grade: 'B',
    company: '嘉尚影业',
    director: '闵秋',
    writer: '沈纸',
    roleKind: '女配角',
    roleName: '课代表',
    role: '女配 · 课代表',
    outline: '高三。晚自习后的天台，家长群比卷子响。课代表收卷子时能看见别人的崩溃，自己一句不说。她不是女主的闺蜜，是成绩好、话少、大家不敢靠近的那种同学。',
    roleBio: '话少，成绩好。不是严厉的班干部，只是太习惯把自己的事放到最后。久而久之，大家都以为她什么也不需要。',
    plot: '教室、天台、家访，都要拍得像真的高三，不能演成鸡汤。家长群那几场，弹幕会比正片先到。',
    press: [
      '闵秋在拍校园网剧《晚自习以后》。嘉尚影业的B级，讲高三晚自习、家长群和模拟考，不是谈恋爱的校园剧。还在找课代表这个配角。',
      '《晚自习以后》家访那场先传开了。有人说像自家，有人说拍得太真，看着累。',
    ],
    leads: ['安青', '裴渡'],
    supporting: ['阮清'],
    need: { acting: 68, poise: 62, wit: 48 },
    weights: { acting: 3, poise: 3, wit: 2 },
    shootNeed: 10,
    promoNeed: 3,
    pay: 24000,
    recognition: 9,
    meetNpc: 'ruanqing',
    sceneAt: 5,
    sceneEvent: 'scene-nightstudy',
  }),
  S({
    id: 'uncle',
    title: '我的二舅爷',
    type: '上星剧',
    tags: ['上星剧', '网络剧'],
    theme: '当代乡村',
    keywords: ['农村', '基建', '通水', '回乡'],
    grade: 'B',
    company: '天奇影视',
    director: '邢伟',
    writer: '葛大运',
    roleKind: '女配角',
    roleName: '黄三珍',
    role: '女配 · 黄三珍',
    outline: '西北村子从灾年走到通水通路。村长黄万福带着人开会、挖渠，把不肯回来的年轻人一个个劝回家。黄三珍是他女儿，去城里学了美容，最后把手艺带回来——戏不在哭，在她怎么把城里那点傲气收住。',
    roleBio: '黄三珍叛逆，但孝顺。城里学的是美容，回来面对的是还没通上的水和不肯认她的邻居。她不是女主，镜头却总在她进村那一次。',
    plot: '剧组会在乡下拍很久。人物要接地气，但不能故意把农村生活演得土气或可怜。开会、挖渠、婚宴，都得像真的村子。',
    press: [
      '邢伟在拍上星剧《我的二舅爷》。天奇影视的B级，讲西北村子通水通路，不是土味短剧。还在找村长女儿黄三珍，不是女主，镜头却不少。',
      '《我的二舅爷》在村里实拍。盒饭、尘土、停电都是真的，妆要往土里靠，不能拍成精修。',
      '《我的二舅爷》预告出了通水那天。弹幕在刷「我们县也是这样过来的」。',
    ],
    leads: ['龙武山', '徐开荣'],
    supporting: ['严宣', '王一芸'],
    need: { acting: 70, poise: 56, speech: 50 },
    weights: { acting: 3, poise: 2, speech: 2, looks: 1 },
    shootNeed: 16,
    promoNeed: 4,
    pay: 42000,
    recognition: 12,
    hype: 'trade',
    random: true,
  }),
  S({
    id: 'sweet',
    title: '请你偏爱',
    type: '甜宠网剧',
    tags: ['网络剧'],
    theme: '都市甜宠',
    keywords: ['联姻', '退婚', '宴会', '女三'],
    grade: 'B',
    company: '浪潮时代',
    director: '赵浅',
    writer: '米柚',
    roleKind: '女三',
    roleName: '许晚宁',
    role: '女三 · 被退掉的联姻',
    outline: '财阀联姻宴会上，男主当众把婚约从她手里改到女主手上。她把戒指摘下来，笑着敬下一杯。不是因为爱而砸场，是第一次发现有人可以当众不选她。后面还有几场「前任」戏，切片会比正片先火。',
    roleBio: '许晚宁从小被家里安排好一切：学校、衣服、婚约。她不是恶毒女三，是那种笑着把场子圆完、回车上才把脸卸下来的人。',
    plot: '宴会退婚是全网先传的那场。笑要得体，走要干脆，不能演成泼妇，也不能演成白莲。通告密，档期一撞，片方不等。',
    press: [
      '赵浅在拍甜宠网剧《请你偏爱》。浪潮时代的B级，财阀宴会上男主当众换婚约。女三许晚宁还在换人，宴会上摘戒指那场已经传开。',
      '《请你偏爱》提前点播的预告只剪了退婚。原著粉说女三后面还有戏，路人说不就是恶毒女三。',
      '《请你偏爱》女三档期排得很满。片方要能撑住宴会、也能撑住后面几场前任戏的人，不是路过哭一下。',
    ],
    leads: ['盛宴', '姜棠'],
    supporting: ['宋晚'],
    need: { looks: 78, confidence: 68, acting: 62, fashion: 64 },
    weights: { looks: 3, confidence: 3, acting: 2, fashion: 2 },
    shootNeed: 10,
    promoNeed: 4,
    pay: 52000,
    recognition: 14,
    random: true,
    meetNpc: 'songwan',
    sceneAt: 4,
    sceneEvent: 'scene-sweet',
  }),
  S({
    id: 'rain',
    title: '回南天',
    type: '微电影',
    tags: ['电影', '短片'],
    theme: '家庭',
    keywords: ['回南天', '父亲', '返乡', '沉默'],
    grade: 'B',
    company: '星汉文化',
    director: '沈照',
    writer: '无名氏',
    roleKind: '女配角',
    roleName: '女儿',
    role: '女配 · 沉默的女儿',
    outline: '回南天，墙上在滴水。父亲的旧收音机怎么调都是杂音。女儿不解释为什么从城里回来，只把窗一遍遍擦干。几乎没有台词，靠的是停顿和呼吸。',
    roleBio: '她不是来和解的，也不是来决裂的。她把窗擦干，把饭热上，把该说的话留在喉咙里。导演不喜欢哭戏。',
    plot: '全片台词很少。沈照不讲情绪，只会告诉你哪里不对。回南天的水、旧收音机、擦窗，都要拍很多遍。',
    press: [
      '沈照在拍短片《回南天》。星汉文化的B级，回南天墙上滴水，女儿从城里回来却不解释。几乎不说话，还在找这个女儿。',
      '《回南天》几乎没有台词。圈里有人说评奖会看，也有人说现在谁看这个。',
    ],
    leads: ['老周'],
    supporting: [],
    need: { acting: 72, poise: 66 },
    weights: { acting: 4, poise: 3, looks: 1 },
    shootNeed: 12,
    promoNeed: 3,
    pay: 16000,
    recognition: 16,
    hype: 'award',
    meetNpc: 'shenzhao',
    sceneAt: 10,
    sceneEvent: 'scene-rain',
  }),
  S({
    id: 'blade',
    title: '西市夜',
    type: '古装网剧',
    tags: ['网络剧', '古装'],
    theme: '古装',
    keywords: ['客串', '夜市', '武戏', '西市'],
    grade: 'B',
    company: '嘉尚影业',
    director: '裴横',
    writer: '方简',
    roleKind: '客串',
    roleName: '戏班女角',
    role: '客串 · 夜市上唱武戏的女角',
    outline: '西市夜市。戏班里唱武戏、会翻跟头的女角在棚上唱一句、翻一个跟头，女主路过，扔来钱袋。没有名字，只有这一场。戏班的锣鼓、夜市的灯，要比人先入镜。',
    roleBio: '夜市戏班里唱武戏、会翻跟头的女角。唱一句，翻一个跟头，再接住女主扔来的钱袋。出场很短，动作必须干净。',
    plot: '角色只有一场戏，唱腔和动作都要提前准备。剧组不会为客串延长档期。',
    press: [
      '裴横在拍古装网剧《西市夜》。嘉尚影业的B级，背景是长安西市的夜市。还在找一个客串：戏班里唱武戏、会翻跟头的女角，只有一场，女主路过时扔下一个钱袋。没有角色名，时间很短，动作要干净。',
    ],
    leads: ['沈照'],
    supporting: [],
    need: { talent: 62, fitness: 58, poise: 50 },
    weights: { talent: 3, fitness: 3, poise: 2 },
    shootNeed: 5,
    promoNeed: 1,
    pay: 12000,
    recognition: 7,
    random: true,
    meetNpc: 'shenzhao',
  }),
  S({
    id: 'whitenoise',
    title: '白噪音',
    type: '都市剧',
    tags: ['上星剧'],
    theme: '都市心理',
    keywords: ['心理门诊', '前台', '中产', '秘密'],
    grade: 'A',
    company: '嘉尚影业',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女配角',
    roleName: '前台',
    role: '女配 · 心理门诊前台',
    outline: '写字楼里一家心理门诊。客人把出轨、裁员、不肯回家的孩子留在诊室，前台把下一杯水递出去。她每天听见中产的秘密，自己的约会却记不住。戏看起来闲，其实每场都在听别人的人生。',
    roleBio: '前台不是工具人。她记得每个预约，却不记得自己的约会。真正难演的是职业性的体贴，而不是热心。',
    plot: '她每天听见很多秘密，却从不参与任何人的人生。叫号、倒水、送客，都是戏。闻疏说，叫号也要有停顿。',
    press: [
      '闻疏在拍都市剧《白噪音》。嘉尚影业的A级，写字楼里一家心理门诊，前台每天听客人把不肯带回家的事说完。这个前台还没定。',
      '《白噪音》对词流出几页。没有血腥，全是谈话。有人说像纪实，有人说现在谁看心理。',
      '《白噪音》男主沈照、梁时都定了。前台那栏还空着，片方要能把「闲着也是戏」演满的人。',
    ],
    leads: ['沈照', '梁时'],
    supporting: ['许宁'],
    need: { acting: 118, speech: 102, wit: 96 },
    weights: { acting: 3, speech: 3, wit: 3, poise: 2 },
    shootNeed: 18,
    promoNeed: 5,
    pay: 62000,
    recognition: 20,
    meetNpc: 'xuning',
    investor: 'guyan',
  }),
  S({
    id: 'intern',
    title: '白大褂',
    type: '医疗剧',
    tags: ['上星剧'],
    theme: '医疗',
    keywords: ['急诊', '实习', '夜班', '术语'],
    grade: 'A',
    company: '嘉尚影业',
    director: '齐衡',
    writer: '医科顾问组',
    roleKind: '女配角',
    roleName: '实习医师 陈慈',
    role: '女配 · 实习医生',
    outline: '三甲急诊。走廊里有人被喊去推床，术语不能错，交接班写在白板上。陈慈不是女主，是刚轮转过来、说每句话都很慢的那一个。忙起来以后，反而成了最稳的那个。',
    roleBio: '陈慈刚轮转到急诊。她怕出错，所以说得很慢；真正忙起来，手比嘴先到。台词少，病历和口型不能错。',
    plot: '走廊、夜班、抢救。齐衡不爱重来。医顾问组盯口型，术语错一个，整条作废。',
    press: [
      '齐衡在拍医疗剧《白大褂》。嘉尚影业的A级，三甲急诊，术语不能错，不是谈恋爱的医生剧。还在找实习医生陈慈。',
      '《白大褂》医学顾问已经进组。口型、病历、推床路线都要过。有人说这是看病的剧，有人说看着太累。',
      '《白大褂》夜班戏连着拍。盒饭、绿光、真正的交接班白板，花絮比正片先传出来。',
    ],
    leads: ['何朗', '白疏影'],
    supporting: ['陈慈'],
    need: { acting: 116, wit: 110, speech: 82, poise: 78 },
    weights: { wit: 4, acting: 3, speech: 2 },
    shootNeed: 14,
    promoNeed: 4,
    pay: 58000,
    recognition: 18,
    random: true,
  }),
  S({
    id: 'snowcourt',
    title: '庭前雪',
    type: '古装网剧',
    tags: ['网络剧', '古装'],
    theme: '古装权谋',
    keywords: ['联姻', '宴席', '仪态', '世家'],
    grade: 'A',
    company: '浪潮时代',
    director: '邢未',
    writer: '顾辞',
    roleKind: '女三',
    roleName: '小郡主',
    role: '女三 · 小郡主',
    outline: '北地小郡主被送去联姻。宴席上笑要得体，怒不能露，落座先后能改两家结盟。不是宫斗女主本，是那些把仪态演满的郡主戏：表面守礼，真正的态度藏在看人和敬酒的顺序里。',
    roleBio: '小郡主被人说花瓶。你要让观众觉得她不是。她不是来抢女主的，是被安排在席面上、一句话也不能说错的人。',
    plot: '戏集中在几场宴席。动作戏不多，仪态一场接一场。服装造型会先被骂，正片才见人。',
    press: [
      '邢未的古装权谋《庭前雪》还在选女三小郡主。浪潮时代的A级网剧，原著从男频权谋改成女向，戏都在联姻宴席上。片方说这张脸要重新看。',
      '《庭前雪》海报上的名字顺序又改了一版。片方说按合同，原著粉说按人气。女三小郡主那栏还空着。',
      '邢未在拍古装权谋《庭前雪》。浪潮时代的A级网剧，编剧顾辞，原著是男频权谋改的女向，讲北地小郡主去联姻，戏都在宴席上。服装路透先出了头上的饰品，妆造连夜发长文，说等正片。',
      '《庭前雪》对词时传出联姻宴席那场。女三不用打架，只敬酒、落座。有人说难演，有人说根本没戏。',
    ],
    leads: ['陈晚秋', '陆承宴'],
    supporting: ['小郡主'],
    need: { acting: 126, poise: 122, looks: 105, fitness: 76 },
    weights: { acting: 3, poise: 3, looks: 3, fashion: 1, fitness: 1 },
    shootNeed: 23,
    promoNeed: 6,
    pay: 128000,
    recognition: 26,
    hype: 'trade',
  }),
  S({
    id: 'musicdoc',
    title: '隔音未满',
    type: '音综纪录',
    track: 'variety',
    tags: ['综艺', '纪录'],
    theme: '音乐',
    keywords: ['唱歌', '排练室', '同期', '真人'],
    grade: 'A',
    company: '星汉文化',
    director: '节目组',
    writer: '剪辑台',
    roleKind: '选手',
    roleName: '自己',
    role: '选手 · 自己',
    outline: '一档把排练室、抢麦、选歌都拍下来的音综。镜头会跟到练声，也会跟到大家累到不想说话的时候。没有角色可以躲，观众很容易看出谁在经营人设。',
    roleBio: '没有角色可以躲。节目组想看真实反应：抢排练室、选歌吵起来、唱砸了以后的脸。',
    plot: '舞台表现和采访同样重要。唱得好会留下完整舞台，失误也可能被单独剪出来。',
    press: [
      '星汉文化在做音综《隔音未满》。A级，拍排练室和生活，不是只拍舞台。还在补选手。有人拿它跟把乐队关进一栋楼那种节目比。',
      '《隔音未满》预告先出了抢排练室。弹幕在猜谁会红，谁会在采访里说错话。',
    ],
    leads: ['裴予'],
    supporting: [],
    need: { talent: 112, speech: 88, fitness: 82 },
    weights: { talent: 5, speech: 2, confidence: 2, looks: 1 },
    shootNeed: 16,
    promoNeed: 6,
    pay: 42000,
    recognition: 16,
    meetNpc: 'peiyu',
  }),
  S({
    id: 'watch',
    title: '观察室',
    type: '真人秀',
    track: 'variety',
    tags: ['综艺'],
    theme: '观察',
    keywords: ['点评', '观察室', '恋爱综艺'],
    grade: 'A',
    company: '星汉文化',
    director: '总导演',
    writer: '环节组',
    roleKind: '观察员',
    roleName: '自己',
    role: '飞行观察员',
    outline: '恋爱综艺的飞行观察员。你不进别墅，只在演播室看片段、聊天、猜嘉宾下一步会选谁。回答太圆滑会显得无聊，随口一句说重了，播出后就是争议。',
    roleBio: '你演自己。观察室里的人要会看、会接话，也要知道哪句不能说完。',
    plot: '录制多在晚上，环节和话题会临时调整。镜头会切到你听完沉默的那一秒。',
    press: [
      '星汉文化的真人秀《观察室》还在找飞行观察员。A级恋爱综艺，你不进别墅，只在演播室看片段、聊天、猜下一步。节目组要能接话、也敢把话说满的人。',
      '《观察室》先放出了演播室片段。有人靠一句点评上了热搜，有人靠一句口误。',
    ],
    leads: [],
    supporting: ['许宁'],
    need: { speech: 112, confidence: 98, looks: 88 },
    weights: { speech: 4, confidence: 3, looks: 2 },
    shootNeed: 8,
    promoNeed: 3,
    pay: 48000,
    recognition: 15,
    random: true,
    meetNpc: 'xuning',
  }),
  S({
    id: 'unnamed',
    title: '未命名',
    type: '文艺电影',
    tags: ['电影'],
    theme: '文艺',
    keywords: ['书店', '无对白', '退货', '等待'],
    grade: 'S',
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女配角',
    roleName: '店员',
    role: '女配 · 书店店员',
    outline: '旧书店。退货的书要一本本重新上架，几乎没有对白。店员每天等一个不会回来的人。沈照不说戏，只说「再安静一点」。圈里当冲奖看，也有人觉得这是在浪费档期。',
    roleBio: '店员没有名字，独自在旧书店工作。她把退回来的书重新上架，也在等一个已经不会回来的人。戏在手指、脚步和停顿里。',
    plot: '行业里会有人因为这部片才正眼看你，也会有人觉得你在浪费时间。金桂奖偶尔会看这种角色，但几乎轮不到新人。不让探班，跟拍的人等不到人。',
    press: [
      '沈照在拍文艺电影《未命名》。星汉文化的S级，旧书店里几乎没有台词，店员每天等一个不会回来的人。还在找这个书店女人。圈里当冲奖看。',
      '《未命名》不让探班。跟拍的人在酒店走廊等到天亮，只拍到一箱退货的书。',
      '影评号说，《未命名》那个书店店员，今年颁奖季可能会被点名，有获奖的希望。也有人说，现在谁还进电影院看书店。',
      '《未命名》选角极慢。沈照看了很多人，只说再安静一点。片酬一般，档期却要让。',
    ],
    leads: ['何朗'],
    supporting: [],
    need: { acting: 168, poise: 158, wit: 118 },
    weights: { acting: 5, poise: 4, wit: 2, looks: 1 },
    shootNeed: 23,
    promoNeed: 6,
    pay: 92000,
    recognition: 44,
    hype: 'award',
    awardTrack: true,
    meetNpc: 'shenzhao',
    sceneAt: 18,
    sceneEvent: 'scene-rain',
  }),
  S({
    id: 'starriver',
    title: '星河渡',
    type: '大 IP 网剧',
    tags: ['网络剧', '大 IP'],
    theme: '仙侠',
    keywords: ['女二', '联姻', '天界', '原著'],
    grade: 'S',
    company: '嘉尚影业',
    director: '裴衡',
    writer: '原著改编',
    roleKind: '女二',
    roleName: '反派侧',
    role: '女二 · 反派侧',
    outline: '上神渡劫，小仙误入天界。原著连载时订阅过千万，讲的是一场用三百年换一次回头的姻缘。女二不是女主的影子：她是魔尊侧送来联姻的人，清楚自己在用感情换一个位置。粉丝会撕，投资人会盯海报上的名字顺序。',
    roleBio: '她爱得难看，但每一笔都算过。演飘了就会被写成「恶毒女二」；演收了，原著粉才会承认这是原著里那个把命押上去的人。',
    plot: '这是个很容易被演成普通反派的角色。她真正的野心、感情和不甘必须同时成立。提前点播的预告、海报上的名字顺序、服装造型路透，都会比正片先吵完。',
    press: [
      '裴衡在拍大IP网剧《星河渡》。嘉尚影业的S级，原著连载时订阅过千万：上神渡劫，小仙进天界。女二是魔尊那边送来联姻的人，还没定。裴衡看了几轮，原著粉已经按人设在骂名字。',
      '《星河渡》选角名单泄漏。江晚宁女主、陆承宴上神，女二那栏还空着。原著粉连夜列出不能改的三件事。',
      '《星河渡》提前点播的预告先出了女二那一眼。一半说原著就是这样，一半说又改成恶毒女二。',
      '《星河渡》服装造型路透。假发套边缘看得出来，妆造连夜发长文。海报上的名字顺序又改了一版，片方说按合同。',
    ],
    leads: ['江晚宁', '陆承宴'],
    supporting: ['许宁'],
    need: { acting: 158, looks: 142, confidence: 136, speech: 112 },
    weights: { acting: 4, looks: 3, confidence: 2, speech: 2 },
    shootNeed: 23,
    promoNeed: 8,
    pay: 480000,
    recognition: 32,
    hype: 'ip',
    meetNpc: 'xuning',
  }),
  S({
    id: 'northstation',
    title: '北站',
    type: '电影',
    tags: ['电影'],
    theme: '现实主义',
    keywords: ['春运', '广播', '延误', '车站'],
    grade: 'S',
    company: '嘉尚影业',
    director: '老钱',
    writer: '老钱',
    roleKind: '女配角',
    roleName: '广播员',
    role: '女配 · 站台广播员',
    outline: '春运。广播室里通宵念延误、重连、请旅客不要拥挤。电影不靠你赢，但有一场你对着空麦克风把通知念完，剪进预告就会被人记住。正脸不多，声音和停顿是戏。',
    roleBio: '广播员不露脸太多。她把通知念完，把哭声隔在玻璃外面。导演希望观众先记住她的声音，再记住她的人。',
    plot: '有一段很长的独白。春运是真的人流，剧组要赶点，广播词不能念成朗诵。',
    press: [
      '老钱在拍电影《北站》。嘉尚影业的S级，春运，广播室通宵念延误。广播员还在试，有一场对着空话筒把通知念完，有人说能进预告。',
      '《北站》在车站实拍。春运是真的，路过的群众是真的，广播词改了十一稿。',
      '《北站》预告先出了广播。有人听完说像回家，有人说又是春运苦情。',
    ],
    leads: ['何朗'],
    supporting: ['广播员'],
    need: { acting: 148, speech: 128, poise: 118 },
    weights: { acting: 4, speech: 4, poise: 2 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 98000,
    recognition: 40,
    hype: 'award',
  }),
  S({
    id: 'coverclip',
    title: '未发布的翻唱',
    type: '翻唱企划',
    track: 'music',
    tags: ['翻唱'],
    theme: '翻唱',
    keywords: ['翻唱', '短视频', '原曲'],
    grade: 'C',
    company: '北声厂牌',
    director: '企划',
    writer: '原曲',
    roleKind: '歌手',
    roleName: '自己',
    role: '翻唱 · 自己',
    outline: '厂牌要一条能发出去的翻唱。不是发行，是试你的声音能不能站住。棚很小，耳机漏音。',
    roleBio: '你唱别人的歌，要保留原曲的味道，也得让人听出这是你的声音。',
    plot: '录音棚很小，制作人会从头听到尾。最终版本是否上线，要等录完以后再决定。',
    leads: [],
    supporting: [],
    need: { talent: 44, speech: 32 },
    weights: { talent: 5, speech: 1 },
    shootNeed: 3,
    promoNeed: 2,
    pay: 3500,
    recognition: 3,
  }),
  S({
    id: 'ostdemo',
    title: '未署名插曲',
    type: '剧宣曲',
    track: 'music',
    tags: ['剧宣曲'],
    theme: '剧集宣传',
    keywords: ['插曲', '不署名', '副歌'],
    grade: 'C',
    company: '北声厂牌',
    director: '配乐组',
    writer: '词作者未署名',
    roleKind: '声部',
    roleName: '未署名',
    role: '插曲声部',
    outline: '剧要一首插曲，名字不出现在片尾。副歌只给你两句。棚里先对气口，再谈钱。',
    roleBio: '没有名字。声音贴上了，片尾也不写你。',
    plot: '只有两句副歌，但要贴合剧里的人物情绪。录得合适，可能会用进预告。',
    leads: [],
    supporting: [],
    need: { talent: 50, poise: 40 },
    weights: { talent: 4, poise: 2 },
    shootNeed: 4,
    promoNeed: 2,
    pay: 7000,
    recognition: 4,
  }),
  S({
    id: 'nightsingle',
    title: '夜班以后',
    type: '独立单曲',
    track: 'music',
    tags: ['单曲'],
    theme: '独立发行',
    keywords: ['单曲', '夜', '发行'],
    grade: 'B',
    company: '海潮唱片',
    director: '制作人阿白',
    writer: '阿白',
    roleKind: '歌手',
    roleName: '自己',
    role: '独唱',
    outline: '一张要上架的单曲。封面、词、发行日都已经定了，差一个敢把副歌唱满的人。',
    roleBio: '这回有名字。发行日不能拖。',
    plot: '除了录歌，还要拍封面和跑发行采访。第一次以自己的名字发歌，每个环节都得本人出现。',
    leads: [],
    supporting: [],
    need: { talent: 72, speech: 54, looks: 54 },
    weights: { talent: 5, speech: 2, looks: 2 },
    shootNeed: 6,
    promoNeed: 4,
    pay: 28000,
    recognition: 12,
    roleTier: 'second',
  }),
  S({
    id: 'nighttalk',
    title: '三点档',
    type: '深夜访谈',
    track: 'variety',
    tags: ['访谈', '综艺'],
    theme: '深夜',
    keywords: ['访谈', '口才', '口误'],
    grade: 'C',
    company: '昼间传媒',
    director: '值班导演',
    writer: '环节组',
    roleKind: '嘉宾',
    roleName: '自己',
    role: '飞行嘉宾',
    outline: '凌晨三点的访谈。观众不多，切片很快。说错一句，比演错一场传得更远。',
    roleBio: '你不演戏。你说话。镜头对着你的停顿。',
    plot: '节目看似随意，其实问题都准备得很细。回答得好可能被转发，口误也一样。',
    leads: [],
    supporting: [],
    need: { speech: 44, looks: 40 },
    weights: { speech: 4, looks: 2, confidence: 1 },
    shootNeed: 3,
    promoNeed: 1,
    pay: 5000,
    recognition: 4,
  }),
  S({
    id: 'glassroom',
    title: '隔间',
    type: '短片',
    tags: ['电影', '短片'],
    theme: '文艺',
    keywords: ['审讯', '停顿', '不招'],
    grade: 'B',
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女配角',
    roleName: '被问话的人',
    role: '女配 · 隔间里的女人',
    outline: '二十分钟。审讯室隔间，灯一直亮。她不招，也不哭。沈照不说戏，只说再短一点。评委会看的是你怎么把「不招」演满。',
    roleBio: '没有名字。灯在头顶，问题在玻璃外面。她把「不招」演满，而不是把委屈演满。',
    plot: '预算不高，拍摄要求却很严。沈照会把一个停顿反复磨很多遍。',
    press: [
      '沈照在拍短片《隔间》。星汉文化的B级，二十分钟，审讯室灯一直亮。还在找隔间里那个不招也不哭的女人。片酬一般，评奖会看。',
      '《隔间》只有二十分钟。圈里有人拿它跟派出所、审讯室那种戏比，说短，但停顿要准。',
    ],
    leads: ['审讯员'],
    supporting: [],
    need: { acting: 70, poise: 64 },
    weights: { acting: 5, poise: 3 },
    shootNeed: 8,
    promoNeed: 2,
    pay: 18000,
    recognition: 22,
    hype: 'award',
    unlock: 'broker',
    highlights: ['director', 'hype'],
    meetNpc: 'shenzhao',
    sceneAt: 6,
    sceneEvent: 'scene-rain',
  }),
  S({
    id: 'sidecast',
    title: '星河渡·宴席一眼',
    type: '大 IP 网剧',
    tags: ['网络剧', '大 IP'],
    theme: '仙侠',
    keywords: ['客串', '宴席', '星河渡'],
    grade: 'B',
    company: '嘉尚影业',
    director: '裴衡',
    writer: '原著改编',
    roleKind: '客串',
    roleName: '宴席上的一眼',
    role: '客串 · 宴席一眼',
    outline: '还是《星河渡》。开年宴上女主路过席面，你没有名字，只有抬头那一眼。原著里这是只出一会儿的戏，路透里已经有人在问旁边那个是谁。主演江晚宁、陆承宴已经定了，镜头会扫到你。',
    roleBio: '客串不是路人。这一眼要让人记得，又不能抢女主。原著粉会逐帧看你有没有「出戏」。',
    plot: '出场只有几秒。演得合适会被记住，太用力也很容易抢掉整场的重心。',
    press: [
      '裴衡的大IP《星河渡》还空一个客串：开年宴上女主路过席面，你没有名字，只有抬头那一眼。江晚宁、陆承宴已经定了，席面上还缺一张脸。',
      '《星河渡》开年宴路透。原著粉在一帧帧认人：谁只出一会儿，谁可能是隐藏人物。',
    ],
    leads: ['江晚宁', '陆承宴'],
    supporting: ['许宁'],
    need: { looks: 62, poise: 56, acting: 52 },
    weights: { looks: 3, poise: 3, acting: 2 },
    shootNeed: 4,
    promoNeed: 2,
    pay: 36000,
    recognition: 10,
    hype: 'ip',
    unlock: 'broker',
    highlights: ['cast', 'hype'],
  }),
  S({
    id: 'cpheat',
    title: '对手戏',
    type: '网剧',
    tags: ['网络剧'],
    theme: '都市',
    keywords: ['大厂', '需求会', '欢喜冤家', '切片'],
    grade: 'B',
    company: '浪潮时代',
    director: '陆深',
    writer: '乔南',
    roleKind: '女二',
    roleName: '余棠',
    role: '女二 · 余棠',
    outline: '互联网大厂。女二余棠和男二梁时不是官配，是需求会对到一半开始呛的那一对。嘴硬，镜头却总切到两个人之间。切片会先于正片到达，路人会先嗑这对本。',
    roleBio: '余棠嘴硬。她跟男二互相看不惯，产品会开完，走廊里还在顶。她不是来拆官配的，是那种「工作上谁也不让」的人。',
    plot: '片方看中了你和梁时之前的对手戏，宣传期也会安排双人采访。戏里的针锋相对要演得像真的，戏外却未必说得清。',
    press: [
      '陆深在拍网剧《对手戏》。浪潮时代的B级，互联网大厂，女二余棠还没定，男二是梁时。片方要一对能在需求会上呛着演的人，切片会比正片先到。',
      '《对手戏》路透出了会议室对吵。弹幕已经在嗑，官配粉已经在骂又发糖。',
      '《对手戏》定了双人采访。片方要写成工作上合不来，不要写成私下已经好了。',
    ],
    leads: ['江晚宁', '梁时'],
    supporting: [],
    need: { acting: 72, looks: 64, speech: 54 },
    weights: { acting: 3, looks: 2, speech: 2, confidence: 1 },
    shootNeed: 12,
    promoNeed: 5,
    pay: 72000,
    recognition: 16,
    hype: 'trade',
    unlock: 'liangshi',
    unlockFavor: 50,
    highlights: ['fame', 'cast'],
  }),
  S({
    id: 'lovevar',
    title: '心动观察',
    type: '恋爱综艺',
    tags: ['综艺'],
    theme: '观察',
    keywords: ['双人', '旅行', '别墅', '切片'],
    grade: 'B',
    company: '星汉文化',
    director: '节目组',
    writer: '环节组',
    roleKind: '嘉宾',
    roleName: '自己',
    role: '飞行嘉宾 · 和梁时一组',
    outline: '旅行恋爱综艺。镜头跟到分房、跟到吃饭、跟到第二天谁先下楼。节目组要一对「有过对手戏」的人，观察室里有人专门猜你们。不是演戏，播出去的样子不全由你们决定。',
    roleBio: '没有剧本角色可以躲。节目会放大你们相处时每一次沉默和犹豫。',
    plot: '你和梁时会被固定分到一组。节目组当然想要暧昧，剪辑也会帮一把。',
    press: [
      '星汉文化的恋爱综艺《心动观察》还在找一对演过对手戏的人。B级旅行恋爱，镜头跟到分房、吃饭、第二天谁先下楼。',
      '《心动观察》观察室先开了。有人已经在猜梁时会跟谁一组，官博还没发名单。',
    ],
    leads: ['梁时'],
    supporting: [],
    need: { speech: 62, looks: 58, confidence: 56 },
    weights: { speech: 3, looks: 2, confidence: 3 },
    shootNeed: 8,
    promoNeed: 4,
    pay: 54000,
    recognition: 12,
    hype: 'trade',
    unlock: 'liangshi',
    unlockFavor: 65,
    highlights: ['fame'],
  }),
  S({
    id: 'goldseat',
    title: '金座',
    type: '都市剧',
    tags: ['上星剧'],
    theme: '资本',
    keywords: ['夜宴', '投资', '女三', '酒桌'],
    grade: 'A',
    company: '嘉尚影业',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女三',
    roleName: '顾家的客人',
    role: '女三 · 宴会上的人',
    outline: '滨江夜宴。投资人把项目按在转盘边上谈。女三是顾家请来的客人，不是花瓶——席面上谁先举杯、谁把话挡回去，比正戏还要准。顾宴川投了这部，角色却不是礼物。',
    roleBio: '她不是女主。她知道自己为什么被请来，也知道哪句话不能接。灯是暖的，话是冷的。',
    plot: '顾宴川是投资人，导演和选角另有判断。拿到以后也得在镜头前站得住。夜宴、黄酒、合同，都要拍得像真的酒桌。',
    press: [
      '闻疏在拍都市剧《金座》。嘉尚影业的A级，顾宴川投的，滨江夜宴上投资人把项目按在转盘边上谈。女三还空着，不是花瓶，是能把话挡回去的人。',
      '《金座》酒桌戏先传出来。有人说像纪实，有人说又是资本局。女三那席还没定。',
      '《金座》选角极慢。投资人盯着，导演也盯着。通稿写客人，剧本写的是能让男主当场接不上的人。',
    ],
    leads: ['江晚宁', '陆承宴'],
    supporting: ['宋晚'],
    need: { acting: 114, poise: 108, speech: 92, looks: 96 },
    weights: { acting: 3, poise: 3, speech: 2, looks: 2 },
    shootNeed: 14,
    promoNeed: 5,
    pay: 96000,
    recognition: 22,
    hype: 'trade',
    unlock: 'guyan',
    unlockFavor: 55,
    highlights: ['fame', 'director'],
    investor: 'guyan',
  }),
  S({
    id: 'peppercourt',
    title: '椒房春',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '后宫',
    keywords: ['后宫', '年氏', '更衣', '圣眷'],
    grade: 'S',
    fromYear: 2,
    company: '嘉尚影业',
    director: '邢未',
    writer: '流朱',
    roleKind: '女二',
    roleName: '蕙嫔',
    role: '女二 · 蕙嫔',
    outline: '后宫不是打戏。更衣、赐食、一句话能让人在宫里活过冬天。蕙嫔不是女主：她是年家送进来的人，圣眷来得快，也去得快。她要在女主还没站稳时，把自己活成宫里的一条路——谁先低头、谁先笑、药碗从哪只手递出去，都是戏。',
    roleBio: '蕙嫔入宫时还不会看人脸色。后来她会了，却仍有一处不肯让。难演的不是狠，是她明明知道规则，仍要在某一年把真心拿出来；也难在圣眷还在时，已经听见它离开的声音。',
    plot: '仪态、对视、药碗和诏书。服装造型会先被骂，正片才见人。宫斗最怕演成撕扯。邢未不爱哭戏，要的是谁先把筷子放下。',
    press: [
      '邢未在拍古装剧《椒房春》。嘉尚影业的S级，后宫、年家、更衣，圈里拿它跟那些一宫里活十年的戏比。女二蕙嫔还没定。',
      '《椒房春》选了三轮。女主已定江晚宁，女二要把圣眷演成负担，不是演成泼。邢未看了几轮，还没点头。',
      '《椒房春》服装造型路透。头上的饰品比人先传开，妆造说等正片。赐食那场对词流出半页，有人说像真的宫里。',
      '白玉兰观察名单里有《椒房春》。女二戏份重，评奖不会只看女主。片方说先把人演住，奖以后再说。',
    ],
    leads: ['江晚宁', '陆承宴'],
    supporting: ['陈晚秋'],
    need: { acting: 128, poise: 132, looks: 108, wit: 112 },
    weights: { acting: 4, poise: 4, wit: 3, looks: 2 },
    shootNeed: 22,
    promoNeed: 7,
    pay: 320000,
    recognition: 36,
    hype: 'ip',
    awardTrack: true,
    highlights: ['hype', 'cast'],
  }),
  S({
    id: 'redcase',
    title: '赤焰案',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '朝堂',
    keywords: ['旧案', '郡主', '挂帅', '朝堂'],
    grade: 'S',
    fromYear: 2,
    company: '星汉文化',
    director: '齐衡',
    writer: '海宴客',
    roleKind: '女二',
    roleName: '梁郡主',
    role: '女二 · 梁郡主',
    outline: '朝堂上的旧案翻出来，死人要被写成叛徒。梁郡主不是来联姻的：她能挂帅，也能在宗庙前把话说完。男主是那个用病骨撑着翻案的人。她要演的是「我信你，但不为你放弃自己的军」——拒婚不是傲，是把军印放下，也把脊梁留下。',
    roleBio: '梁郡主坐得直，话少。她不是女主，却是这部里唯一能把「公道」说出口而不显得幼稚的人。联姻那场，她可以拒。难演的不是飒，是她把人救出来以后，仍不肯把命交给任何人。',
    plot: '朝会、军报、夜谈。齐衡不爱哭戏。郡主的戏在站姿、拒婚和点将，不在落泪。朝仪错一个，整条作废。',
    press: [
      '齐衡在拍古装剧《赤焰案》。星汉文化的S级，朝堂翻旧案，女二梁郡主能挂帅也能拒婚，还在选。有人说这是男主的戏，有人说郡主那场能撑半部。',
      '《赤焰案》死人、军权、一句臣敢请。女二不是花瓶郡主。何朗已经定了，生病那场先拍。',
      '《赤焰案》对词流出拒婚词。片方要她不柔、不泼，把兵权放下也把脊梁留下。原著粉说别写成爱上男主就卸甲。',
      '电影金桂奖不看剧，白玉兰会看。齐衡的组，朝堂礼节错一个，整条作废。点将那场要过顾问。',
    ],
    leads: ['何朗'],
    supporting: ['裴渡'],
    need: { acting: 132, poise: 128, speech: 118, fitness: 96 },
    weights: { acting: 4, poise: 3, speech: 3, fitness: 1 },
    shootNeed: 20,
    promoNeed: 6,
    pay: 280000,
    recognition: 40,
    hype: 'ip',
    awardTrack: true,
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'dust',
    title: '隐尘',
    type: '电影',
    tags: ['电影'],
    theme: '农村',
    keywords: ['土地', '夫妻', '病', '沉默'],
    grade: 'S',
    fromYear: 2,
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女主',
    roleName: '曹英',
    role: '女主 · 曹英',
    outline: '西北。夫妻种地，病来了，地还在。几乎没有金句，也没有翻盘。女主不是来哭穷的：她要把日子过完，把一袋粮食从集上背回去。圈里当冲奖看，院线未必肯排。接了，就是拿当红档期去换一次被评委看见。',
    roleBio: '曹英话少，手粗。她爱她丈夫，方式是把药钱省下来。镜头会跟着她走路、做饭、不解释。妆面要往土里靠，漂亮是减分。',
    plot: '不让探班。沈照只说再短一点。片酬低，档期长。评奖会盯这部，投资人会问你为什么接。女主奖开始观察，赢几乎轮不到第二年。',
    press: [
      '沈照在拍电影《隐尘》。星汉文化的S级，西北种地，病来了地还在。找女主，几乎不靠台词，电影院不一定肯排。',
      '《隐尘》片酬低，冲奖。有人说这是今年电影该走的路，有人说接了就是浪费当红档期。片方不谈女主奖，只谈她像不像在地里站过。',
      '《隐尘》选角极慢。沈照看了很多人。化妆、手、走路先过，台词往后放。',
      '金桂奖内定传闻又起。组委会说请以公布为准。《隐尘》已经在观察名单里。女主栏还空着。',
    ],
    leads: ['何朗'],
    supporting: [],
    need: { acting: 155, poise: 148, wit: 88, looks: 62 },
    weights: { acting: 5, poise: 4, looks: 1 },
    shootNeed: 24,
    promoNeed: 5,
    pay: 48000,
    recognition: 52,
    hype: 'award',
    awardTrack: true,
    meetNpc: 'shenzhao',
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'youngbook',
    title: '少年书',
    type: '电影',
    tags: ['电影'],
    theme: '校园',
    keywords: ['校园', '保护', '录像', '成年'],
    grade: 'A',
    fromYear: 2,
    company: '嘉尚影业',
    director: '老钱',
    writer: '周湛',
    roleKind: '女二',
    roleName: '魏早',
    role: '女二 · 魏早',
    outline: '高中。有人被欺到不敢回家，有人把录像存在手机里。女主不是你。魏早是那个看起来站在施暴那边、其实把U盘藏起来的人。电影不靠热血，靠谁敢把东西交出去。',
    roleBio: '魏早成绩好，话硬。她不是来拯救的，是第一次决定站哪边。演飘了会变成「良心发现的恶人」。',
    plot: '校园实拍。尺度审查。有几场不能哭，只能把东西放下。',
    press: [
      '老钱在拍电影《少年书》。嘉尚影业的A级，高中里有人被欺到不敢回家。女二魏早还在选。审查盯尺度，片方要拍得不像说教。',
      '《少年书》一看完不敢说话。女二不是女主的影子：她看起来站在施暴那边，U盘却在她抽屉里。',
      '《少年书》进了观察。金桂奖很少看校园片，但这部口碑会比票房先到。几场不能哭，只能把东西放下。',
    ],
    leads: ['白疏影'],
    supporting: ['阮清'],
    need: { acting: 124, poise: 116, speech: 88 },
    weights: { acting: 4, poise: 3, speech: 2 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 86000,
    recognition: 28,
    hype: 'award',
    awardTrack: true,
  }),
  S({
    id: 'northwind',
    title: '风过北河',
    type: '上星剧',
    tags: ['上星剧'],
    theme: '扫黑',
    keywords: ['扫黑', '律师', '父子', '一省'],
    grade: 'S',
    fromYear: 2,
    company: '天奇影视',
    director: '邢伟',
    writer: '徐纪周客',
    roleKind: '女二',
    roleName: '忻律',
    role: '女二 · 律师',
    outline: '一省的案子从夜市摊翻到厅局。女二是律师，不是女主：她接的是没人敢接的委托，酒桌上把话挡回去，卷宗里把人救出来。父子那条线不归她，但她知道那张桌子上谁在说谎。',
    roleBio: '忻律不吼。她把证据放在桌上，让别人先吵。台词是法条和人名，不能错。',
    plot: '实景、群众演员、集数被拉长的传闻会比正片先到。律师戏要过顾问，酒桌戏要像真的。',
    press: [
      '邢伟在拍上星剧《风过北河》。天奇影视的S级，一省的案子从夜市摊翻到厅局。女二是律师，还没定。预告会先吵海报上谁的名字在前。',
      '《风过北河》已经有人说集数被拉得很长。编剧把开会写成三集。律师那场，顾问盯口型。',
      '《风过北河》被写成今年的年度剧。女二不是花瓶，卷宗和酒桌都是戏。像不像真实案子，传闻已经被压过一轮。',
    ],
    leads: ['龙武山', '裴渡'],
    supporting: ['许宁'],
    need: { acting: 130, speech: 126, wit: 120, poise: 100 },
    weights: { speech: 4, acting: 3, wit: 4 },
    shootNeed: 21,
    promoNeed: 7,
    pay: 210000,
    recognition: 34,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'returner',
    title: '故人归',
    type: '古装网剧',
    tags: ['网络剧', '大 IP', '古装'],
    theme: '仙侠',
    keywords: ['女主', '重逢', '天界', '大 IP'],
    grade: 'S',
    fromYear: 2,
    company: '嘉尚影业',
    director: '裴衡',
    writer: '原著改编',
    roleKind: '女主',
    roleName: '阿念',
    role: '女主 · 阿念',
    outline: '又一部仙侠大 IP。女主还没定死，试镜已经三轮。阿念不是《星河渡》那个用感情换位置的人：她是自己走上天界、也自己把命押上的人。原著粉会先骂名字，资本会盯脸。第二年能试女主，不等于能签下来。',
    roleBio: '阿念看起来软，决定很快。她不是来被救的。试镜要唱、要打、要把「我认得你」演成劫，不是演成甜。',
    plot: '女主竞争。你可能试了也拿不到。拿到了，提前点播、服装造型、海报名字顺序会把你先吵一遍。演技不够，裴衡不会为了流量改口。',
    press: [
      '裴衡在拍大IP古装网剧《故人归》。嘉尚影业的S级仙侠，女主阿念自己走上天界，试了三轮还没定。原著粉已经准备退款。',
      '《故人归》和《星河渡》热度对打。有人说市场吃不下两部仙侠，有人说就这一年。',
      '《故人归》选角名单泄漏。女主那栏还空着。裴衡说要能把重逢演成劫。投资人要脸，导演要那场不说话的戏。',
    ],
    leads: ['陆承宴'],
    supporting: ['江晚宁'],
    need: { acting: 142, looks: 128, confidence: 122, poise: 118 },
    weights: { acting: 4, looks: 3, confidence: 3, poise: 2 },
    shootNeed: 23,
    promoNeed: 8,
    pay: 620000,
    recognition: 38,
    hype: 'ip',
    highlights: ['hype', 'cast'],
  }),
  S({
    id: 'lotusford',
    title: '莲花渡',
    type: '古装网剧',
    tags: ['网络剧', '古装'],
    theme: '江湖',
    keywords: ['江湖', '旅店', '探案', '女二'],
    grade: 'A',
    fromYear: 2,
    company: '浪潮时代',
    director: '闵秋',
    writer: '方简',
    roleKind: '女二',
    roleName: '渡娘',
    role: '女二 · 渡口的人',
    outline: '江湖不是宫斗。旅店、渡口、一桩桩案子。女二是渡口上那个把船撑走的人：知道男主是谁，不说破，也不跟他走。',
    roleBio: '渡娘看起来闲。她把客人送走，把尸体从夜里捞起来，第二天照常开船。',
    plot: '动作不多，案子要清楚。女二戏份容易被剪，演得住才会留。',
    press: [
      '闵秋在拍古装网剧《莲花渡》。浪潮时代的A级，江湖探案，不是宫斗。女二是渡口上把船撑走的人，还在选。片方要她知道男主是谁，也不说破。',
      '《莲花渡》男主已经定了。女二戏份会不会被剪，看成片。',
    ],
    leads: ['何朗'],
    supporting: ['裴渡'],
    need: { acting: 118, speech: 108, poise: 110 },
    weights: { acting: 3, speech: 3, poise: 2 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 128000,
    recognition: 24,
    hype: 'trade',
  }),
  S({
    id: 'southwind',
    title: '南风寄',
    type: '电视剧',
    tags: ['上星剧'],
    theme: '小城',
    keywords: ['小城', '风', '寄居', '慢'],
    grade: 'A',
    fromYear: 2,
    company: '星汉文化',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女配角',
    roleName: '铺子',
    role: '女配 · 开铺的人',
    outline: '去一个有风的小城住下来。女主不是你。你是那家铺子：收信、借伞、把外乡人留下来吃一碗面。戏慢，没有爽点，口碑会两极。',
    roleBio: '她把铺子开好，不问来的人要去哪。真正难演的是不催情节。',
    plot: '实景、风、长镜头。闻疏不爱快剪。',
    press: [
      '闻疏在拍电视剧《南风寄》。星汉文化的A级，去一个有风的小城住下来。还在找铺子里那个女人：收信、借伞、留外乡人吃面。戏慢，没有爽点。',
      '《南风寄》路透全是风和电线。弹幕会吵剧情呢。',
    ],
    leads: ['宋知夏'],
    supporting: [],
    need: { acting: 114, poise: 120, speech: 86 },
    weights: { acting: 3, poise: 4 },
    shootNeed: 14,
    promoNeed: 4,
    pay: 72000,
    recognition: 22,
    hype: 'award',
  }),
  S({
    id: 'weiyang',
    title: '未央辞',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '后宫',
    keywords: ['女主', '后宫', '从妃到后', '年'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '邢未',
    writer: '流朱',
    roleKind: '女主',
    roleName: '许蘅',
    role: '女主 · 许蘅',
    outline: '后宫从更衣走到掌事。女主不是生来就会斗：她先被送进来，后来才把自己活成宫里的规矩。蕙嫔若还在，是她的对照。这部要的是「一步步把命拿回来」，不是开局就狠。十年同一张脸，评委先看你有没有把季节演开。',
    roleBio: '许蘅入宫时会看病历，不会看人。后来她会了。女主要能把十年演成同一张脸的不同季节：软的那年、狠的那年、把诏书按住的那年，不能演成三个人。',
    plot: '女主本。档期以年计。白玉兰、国剧都会盯。拿奖很难，拍砸了更难看。邢未不爱开局就狠，要她把字说完。',
    press: [
      '邢未在拍古装剧《未央辞》。嘉尚影业的S级，后宫从更衣走到掌事，要演十年。女主还在选。圈里说这是宫斗正路，也有人说吃力不讨好。',
      '《未央辞》海报一出，评论只记得旧的那部一宫十年的戏。邢未说这次不靠那部活。',
      '《未央辞》女主试镜要读一整段「我不信命」。邢未不爱哭，要她把字说完。江晚宁已定皇后线，女主栏还空着。',
      '白玉兰观察名单里有这部。已经有人问女主奖，评奖会把十年拆开看。拍飘了，比女二更难看。',
    ],
    leads: ['陆承宴'],
    supporting: ['陈晚秋', '江晚宁'],
    need: { acting: 158, poise: 155, wit: 140, looks: 118 },
    weights: { acting: 5, poise: 4, wit: 3, looks: 2 },
    shootNeed: 26,
    promoNeed: 8,
    pay: 880000,
    recognition: 48,
    hype: 'ip',
    awardTrack: true,
    highlights: ['hype', 'director'],
  }),
  S({
    id: 'shore',
    title: '岸边',
    type: '电影',
    tags: ['电影'],
    theme: '文艺',
    keywords: ['海边', '返乡', '女主', '冲奖'],
    grade: 'S',
    fromYear: 3,
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女主',
    roleName: '岸',
    role: '女主 · 岸',
    outline: '海边。她从城里回来，不解释，把网补上。电影不靠台词赢。金桂最佳女主角会看这部：冷、慢、卖座不一定。接了，就是拿档期去换一次被看见。影后不是年终礼物，评委也不看你热搜。',
    roleBio: '岸几乎不哭。她把网补好，把信烧掉，把人送走。女主要能把「回来」演满，而不是把「成功」演满。漂亮是减分。',
    plot: '不让探班。沈照不说戏。片酬普通，评奖会盯女主。第三年能进组，不等于典礼会念你的名字。',
    press: [
      '沈照在拍电影《岸边》。星汉文化的S级，海边返乡，几乎不靠台词。还在找女主。圈里当冲击影后看。',
      '《岸边》电影院不一定肯多排。影评号说，这部女主今年颁奖季可能会被点名，有获奖的希望。给国外看的宣传在做，翻译先把沉默译丢了。',
      '《岸边》选角比《未命名》更慢。沈照只说她要像在岸上站过。有人劝你别拿档期去赌一部冷片。',
    ],
    leads: [],
    supporting: ['何朗'],
    need: { acting: 168, poise: 162, wit: 118, looks: 70 },
    weights: { acting: 5, poise: 4, wit: 2 },
    shootNeed: 24,
    promoNeed: 6,
    pay: 120000,
    recognition: 60,
    hype: 'award',
    awardTrack: true,
    meetNpc: 'shenzhao',
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'ninegates',
    title: '九重门',
    type: '大 IP 网剧',
    tags: ['网络剧', '大 IP'],
    theme: '仙侠',
    keywords: ['女主', '天门', '原著'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '裴衡',
    writer: '原著改编',
    roleKind: '女主',
    roleName: '九门',
    role: '女主 · 九门',
    outline: '仙侠女主。不是女二那条把感情当筹码的命：她推开的是门，不是人。粉丝、服装造型、提前点播、给国外看的宣传会把你先吵死。',
    roleBio: '九门看起来冷。她把门推开，把旧名字留下。女主要能打、能把重逢压住。',
    plot: '大 IP 女主。资本盯脸，导演盯一场不说话的戏。',
    press: [
      '裴衡在拍大IP网剧《九重门》。嘉尚影业的S级仙侠，女主推开的是门，不是人。女主还没定。给国外看的宣传已经在做，粉丝比剧组快。',
      '《九重门》服装造型路透。假发套又看得出来。提前点播的预告先出了女主那一眼。',
    ],
    leads: ['陆承宴'],
    supporting: ['江晚宁'],
    need: { acting: 152, looks: 140, confidence: 132, poise: 128 },
    weights: { acting: 4, looks: 3, confidence: 3 },
    shootNeed: 24,
    promoNeed: 9,
    pay: 980000,
    recognition: 44,
    hype: 'ip',
  }),
  S({
    id: 'people-sea',
    title: '人海',
    type: '年代剧',
    tags: ['上星剧'],
    theme: '年代',
    keywords: ['一家人', '三十年', '群像'],
    grade: 'A',
    fromYear: 3,
    company: '天奇影视',
    director: '邢伟',
    writer: '梁晓声客',
    roleKind: '女主',
    roleName: '周蓉',
    role: '女主 · 周蓉',
    outline: '一家人三十年。女主从姑娘演到把孩子送走。群像里要站得住，集数拉长会把开会写成三集。真假年代感会先被骂。',
    roleBio: '周蓉不是完人。她把家里的事做完，把外面的事忍下。女主要能把年龄演开。',
    plot: '跨年拍摄。妆容、口音、年代物不能错。',
    press: [
      '邢伟在拍年代剧《人海》。天奇影视的A级，一家人三十年，女主从姑娘演到把孩子送走。女主还在选。有人说像正剧，有人说集数会被拉得很长。',
      '《人海》预告出了晚饭那一桌。弹幕在刷「我家也是这样过来的」。',
    ],
    leads: ['何朗', '龙武山'],
    supporting: ['宋知夏'],
    need: { acting: 148, poise: 140, speech: 110 },
    weights: { acting: 4, poise: 3, speech: 2 },
    shootNeed: 22,
    promoNeed: 6,
    pay: 360000,
    recognition: 36,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'sister',
    title: '她的小孩',
    type: '电影',
    tags: ['电影'],
    theme: '家庭',
    keywords: ['姐姐', '抚养', '选择'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '老钱',
    writer: '游晓颖客',
    roleKind: '女主',
    roleName: '安然',
    role: '女主 · 安然',
    outline: '姐姐要不要把弟弟留下。电影把选择摊在桌上，不给正确答案。女主不是来感动观众的：她要在医院走廊、律师事务所和夜里把「我可不可以过自己的日子」说完。',
    roleBio: '安然会笑，也会把文件推回去。女主要能把「不想当妈」演得不是狠。',
    plot: '现实题材，审查。冲奖，也容易被写成话题。',
    press: [
      '老钱在拍电影《她的小孩》。嘉尚影业的S级，姐姐要不要把弟弟留下，不当妈算不算狠。还在找女主。金桂奖会看，网上也会骂。',
      '《她的小孩》看完不敢说话。女主档期要让。审查会盯「选择」两个字怎么拍。',
    ],
    leads: [],
    supporting: ['白疏影'],
    need: { acting: 160, poise: 150, speech: 122, wit: 110 },
    weights: { acting: 5, poise: 3, speech: 3 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 160000,
    recognition: 50,
    hype: 'award',
    awardTrack: true,
  }),
  S({
    id: 'brocade',
    title: '锦衣夜',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '宅门',
    keywords: ['宅门', '嫡庶', '女工', '明媒'],
    grade: 'A',
    fromYear: 2,
    company: '嘉尚影业',
    director: '闵秋',
    writer: '流朱',
    roleKind: '女二',
    roleName: '盛宜',
    role: '女二 · 盛宜',
    outline: '宅门不是后宫。盛宜不是女主：她是嫡房里那个会女工、会看人、把明媒正娶四个字咬死的人。女主从庶房里往上走，她要演的是「规矩站在我这边」——直到规矩反过来咬她。',
    roleBio: '盛宜话不多，针脚密。她不是来作的，是真的信这套规矩能护住她。难演的不是骄，是她把人逼到墙角时，自己也没有退路。',
    plot: '女工、宴席、分家。闵秋要针脚和落座，不要撕打。服装造型会先被夸，人要后到。',
    press: [
      '闵秋在拍古装剧《锦衣夜》。嘉尚影业的A级，宅门不是后宫。女二盛宜会女工、会看人，把明媒正娶咬死，还在选。',
      '《锦衣夜》对词流出分家那场。女二不是作精，是真的信规矩。原著粉说别写成恶毒嫡姐。',
      '《锦衣夜》女主已定。女二戏份重，白玉兰会不会看宅斗，看成片。',
    ],
    leads: ['宋知夏'],
    supporting: ['陈晚秋'],
    need: { acting: 122, poise: 126, wit: 110, looks: 100 },
    weights: { acting: 4, poise: 4, wit: 3 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 168000,
    recognition: 28,
    hype: 'trade',
    awardTrack: true,
    highlights: ['hype'],
  }),
  S({
    id: 'longnight',
    title: '长夜未明',
    type: '电影',
    tags: ['电影'],
    theme: '悬疑',
    keywords: ['小城', '录像', '证人', '沉默'],
    grade: 'A',
    fromYear: 2,
    company: '星汉文化',
    director: '老钱',
    writer: '周湛',
    roleKind: '女配角',
    roleName: '证人',
    role: '女配 · 不说话的人',
    outline: '小城。孩子、录像、一桩翻了十几年的案子。你不是女主。你是那个把带子藏过、后来又坐在询问室里不说话的人。电影不靠反转金句，靠谁先把沉默撑破。',
    roleBio: '她看起来普通。真正难演的是她知道，却把话咽回去的那几年。哭是减分。',
    plot: '东北实景。尺度审查。有几场只能坐着，把烟灰弹直。口碑会先于票房到。',
    press: [
      '老钱在拍电影《长夜未明》。星汉文化的A级，小城一桩翻了十几年的案子。还在找证人：把带子藏过、后来坐在询问室里不说话的人。像不像真实案件，传闻已经被压过一轮。',
      '《长夜未明》询问室那场先传出来。有人说像纪录片，有人说太冷。这个配角不是来解释案情的。',
      '金桂奖会看这种片子。女配也能进候选。片方不谈奖，只谈她像不像在那座城里住过。',
    ],
    leads: ['何朗'],
    supporting: ['白疏影'],
    need: { acting: 126, poise: 130, speech: 70 },
    weights: { acting: 5, poise: 4, speech: 1 },
    shootNeed: 14,
    promoNeed: 4,
    pay: 62000,
    recognition: 30,
    hype: 'award',
    awardTrack: true,
    highlights: ['director'],
  }),
  S({
    id: 'counter',
    title: '柜台',
    type: '电影',
    tags: ['电影'],
    theme: '现实',
    keywords: ['药', '柜台', '假药', '病人'],
    grade: 'S',
    fromYear: 2,
    company: '星汉文化',
    director: '老钱',
    writer: '唐纸',
    roleKind: '女二',
    roleName: '药房',
    role: '女二 · 把药递出去的人',
    outline: '药很贵。有人从柜台把仿制药递出去，有人因此能再活一年。女主不是你。你是药房里那个知道风险、仍把药箱打开的人。电影会让广场骂，评委会盯「像不像真的把药递过手」。',
    roleBio: '她不是圣人。她把价钱报清楚，把后果也说清楚，然后把药推过玻璃。难演的不是哭，是她报完价以后不再解释。',
    plot: '实景、病人、审查。片酬普通。冲奖。女二戏份容易被写成工具人，演住了才会留在正片里。',
    press: [
      '老钱在拍电影《柜台》。星汉文化的S级，药房把仿制药递过玻璃。女二还在选。审查已经来过一轮。',
      '《柜台》片酬普通，冲奖。有人说这是该走的路，有人说接了就是往舆论上撞。',
      '《柜台》选角要她像在药房站过。手、口型、报药名，顾问盯着。金桂观察名单里有这部。',
    ],
    leads: ['龙武山'],
    supporting: [],
    need: { acting: 140, poise: 132, speech: 118, looks: 68 },
    weights: { acting: 5, speech: 3, poise: 3, looks: 1 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 54000,
    recognition: 38,
    hype: 'award',
    awardTrack: true,
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'nightward',
    title: '白夜班',
    type: '上星剧',
    tags: ['上星剧'],
    theme: '医疗',
    keywords: ['外科', '夜班', '一台戏', '连轴'],
    grade: 'A',
    fromYear: 2,
    company: '天奇影视',
    director: '齐衡',
    writer: '周湛',
    roleKind: '女二',
    roleName: '值班',
    role: '女二 · 外科值班',
    outline: '比走廊里的实习更重的一台戏。女二是外科值班：她把人从台上接下来，也把坏消息送出手术室。术语不能错，连轴也不能演成苦情。',
    roleBio: '她不吼。她把手套摘下来，把话一次说完。难演的不是救人，是她把「没了」三个字送到家属面前。',
    plot: '齐衡组。医顾问进组。口型、病历、推床路线都要过。连轴拍，化妆要往虚里靠，不能妆造比人先出圈。',
    press: [
      '齐衡在拍上星剧《白夜班》。天奇影视的A级，外科值班，比《白大褂》更重。女二还没定。术语错一个，整条作废。',
      '《白夜班》医学顾问进组。手术室那场要过三轮。有人劝你别拿档期去熬夜班。',
      '《白夜班》预告会先出推床。弹幕会吵又是医疗剧，人要等正片才见。',
    ],
    leads: ['何朗'],
    supporting: ['许宁'],
    need: { acting: 124, speech: 120, poise: 108, fitness: 88 },
    weights: { acting: 4, speech: 4, poise: 2 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 142000,
    recognition: 26,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'painted',
    title: '扮相',
    type: '电影',
    tags: ['电影'],
    theme: '戏曲',
    keywords: ['戏班', '扮相', '师徒', '台上'],
    grade: 'S',
    fromYear: 3,
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女主',
    roleName: '程秋',
    role: '女主 · 程秋',
    outline: '戏班。她在台上是一个人，台下是另一个人。电影把师徒、班主、一场必须唱完的戏摊在桌上，不给革命口号。金桂最佳女主角会看这部：扮相、嗓子、把命押在一场上。接了，才艺和演技都要过，漂亮是减分。',
    roleBio: '程秋会唱。她把脸涂上，就把自己留下。女主要能把「我是戏」和「我还是人」演成同一副骨架，不能演成两出。',
    plot: '不让探班。唱段要真唱。沈照不说戏。片酬普通，档期长。评奖会盯女主，电影院不一定排。影后很难，陪跑更常见。',
    press: [
      '沈照在拍电影《扮相》。星汉文化的S级，戏班里台上台下不是同一个人。还在找女主。圈里当冲击影后看。',
      '《扮相》要真唱。才艺过不了，试镜直接停。有人说这是今年电影最难的女主。',
      '《扮相》选角极慢。沈照要她像把命押在一场上。给国外看的宣传在做，翻译先把唱段译丢了。',
      '金桂女主观察。陈晚秋陪跑过这种片子。片方不承诺奖，只谈你敢不敢把脸涂上。',
    ],
    leads: [],
    supporting: ['何朗'],
    need: { acting: 172, talent: 148, poise: 160, looks: 72 },
    weights: { acting: 5, talent: 4, poise: 4, looks: 1 },
    shootNeed: 26,
    promoNeed: 6,
    pay: 96000,
    recognition: 58,
    hype: 'award',
    awardTrack: true,
    meetNpc: 'shenzhao',
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'cipher',
    title: '密信',
    type: '电影',
    tags: ['电影'],
    theme: '谍战',
    keywords: ['密馆', '两套话', '一张脸', '夜里'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '邢未',
    writer: '海宴客',
    roleKind: '女主',
    roleName: '顾青',
    role: '女主 · 顾青',
    outline: '密馆。一张脸要演两套话：白天是夫人，夜里把信送出去。电影不靠枪林弹雨，靠谁先把眼神露馅。金桂会看，广场会吵「她到底站哪边」。接了，就是把妩媚和狠放在同一场里，还不能演成两个角色。',
    roleBio: '顾青会笑。她把茶端稳，把信藏好。女主要能把「我在说谎」演成日常，而不是演成高潮。',
    plot: '审查。邢未不爱喊口号。片酬中等。评奖会盯女主一场不说话的戏。卖座不一定。',
    press: [
      '邢未在拍电影《密信》。嘉尚影业的S级，一张脸两套话。还在找女主。圈里当冲奖看，也有人说尺度过不了。',
      '《密信》试镜要一场把茶端稳。邢未说别演间谍，演一个会把日子过完的人。',
      '《密信》审查已经来过。片方改了两稿。金桂观察，女主栏还空着。',
    ],
    leads: ['陆承宴'],
    supporting: ['陈晚秋'],
    need: { acting: 166, poise: 158, wit: 142, speech: 128 },
    weights: { acting: 5, poise: 4, wit: 3, speech: 2 },
    shootNeed: 20,
    promoNeed: 6,
    pay: 180000,
    recognition: 54,
    hype: 'award',
    awardTrack: true,
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'citylamp',
    title: '城中灯',
    type: '上星剧',
    tags: ['上星剧'],
    theme: '家庭',
    keywords: ['都市', '家庭', '不是甜宠', '贺岁'],
    grade: 'A',
    fromYear: 3,
    company: '天奇影视',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女主',
    roleName: '灯',
    role: '女主 · 灯',
    outline: '都市家庭，不是甜宠。女主把家里的账和外面的脸同时撑住。贺岁档会要笑，成片里她不一定给。收视会吵，尺度审查，国剧会看她有没有把「过年」演成压力。',
    roleBio: '灯会应酬。她把饭桌上的话挡回去，把孩子的事按住。女主要能把体面演满，也把体面后面的那一口气留下。',
    plot: '实景、家庭、贺岁档。闻疏不爱金句。女主本，不是冲影后，是把一线坐住的那种上星。',
    press: [
      '闻疏在拍都市家庭剧《城中灯》。嘉尚影业的A级，贺岁档要笑，不是甜宠。女主还在选。片方说别演成鸡汤。',
      '《城中灯》审查盯尺度。收视会先吵海报上谁的名字在前。有人说这是今年要的年味，有人说播不完。',
    ],
    leads: ['裴渡'],
    supporting: ['宋知夏'],
    need: { acting: 146, poise: 138, speech: 122, looks: 108 },
    weights: { acting: 4, poise: 3, speech: 3 },
    shootNeed: 20,
    promoNeed: 7,
    pay: 420000,
    recognition: 34,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'teahouse',
    title: '茶酒录',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '市井',
    keywords: ['酒楼', '茶酒', '自立', '市井'],
    grade: 'A',
    fromYear: 2,
    company: '嘉尚影业',
    director: '闵秋',
    writer: '方简',
    roleKind: '女二',
    roleName: '酒牌',
    role: '女二 · 酒楼里的人',
    outline: '宋制市井。酒楼、茶摊、一笔能把人从局里托出来的账。女主不是你。你是酒牌：把客人的话听完，把酒温上，把不该进门的人挡在帘外。她不是来联姻的，是把日子做成一门手艺。',
    roleBio: '酒牌会算、会看人。她把笑容摆在柜上，把硬话留在后厨。难演的不是飒，是她把人救出来以后，仍要回去洗碗。',
    plot: '宴席、账本、市井夜。闵秋要手艺和落座，不要打戏撑场。服装造型会先被夸，人要后到。',
    press: [
      '闵秋在拍古装《茶酒录》。嘉尚影业的A级，市井酒楼，不靠宫斗。女二酒牌还在选，要把日子做成手艺。',
      '《茶酒录》对词流出温酒那场。女二不是花瓶掌柜。原著粉说别写成爱上男主就关铺。',
      '《茶酒录》路透全是灶和账本。弹幕会先夸服装造型，人要等正片才见。',
    ],
    leads: ['宋知夏'],
    supporting: ['陈晚秋'],
    need: { acting: 116, poise: 120, looks: 104, fashion: 96 },
    weights: { acting: 3, poise: 4, looks: 2, fashion: 2 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 148000,
    recognition: 26,
    hype: 'trade',
    awardTrack: true,
    highlights: ['hype'],
  }),
  S({
    id: 'sideline',
    title: '旁观录',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '朝堂',
    keywords: ['旁观', '内库', '入局', '轻'],
    grade: 'S',
    fromYear: 2,
    company: '天奇影视',
    director: '邢伟',
    writer: '海宴客',
    roleKind: '女二',
    roleName: '内库',
    role: '女二 · 内库',
    outline: '朝堂有人在布局，有人在旁观。女二管内库：银子、名单、谁今晚不能出门。她不是女主，却是这部里唯一能把「我看见了」说得不像告密的人。轻，不等于没骨头。',
    roleBio: '内库话少，账清楚。她把男主从局里托出来，也不把自己赔进去。难演的不是聪明，是她明明能走，仍把钥匙留下。',
    plot: '朝会、夜账、一句玩笑里的刀。邢伟不爱哭戏。术语换成典章，错一个，整条作废。',
    press: [
      '邢未在拍古装《旁观录》。嘉尚影业的A级，朝堂旁观再入局。女二内库还在选。有人说这是男主的戏，有人说内库那场能撑半部。',
      '《旁观录》对词流出夜账。女二不是花瓶谋士。片方要她轻、准，把钥匙留下。',
      '《旁观录》预告先出玩笑。弹幕会当轻松喜剧，正片要的是她把名单按住的那一下。白玉兰会不会看，看成片。',
    ],
    leads: ['陆承宴'],
    supporting: ['裴渡'],
    need: { acting: 122, wit: 126, speech: 110, poise: 108 },
    weights: { wit: 4, acting: 3, speech: 3, poise: 2 },
    shootNeed: 20,
    promoNeed: 6,
    pay: 240000,
    recognition: 32,
    hype: 'ip',
    awardTrack: true,
    highlights: ['hype', 'cast'],
  }),
  S({
    id: 'loopbus',
    title: '循环线',
    type: '网剧',
    tags: ['网络剧'],
    theme: '悬疑',
    keywords: ['同一趟', '车上', '循环', '救人'],
    grade: 'A',
    fromYear: 2,
    company: '浪潮时代',
    director: '老钱',
    writer: '周湛',
    roleKind: '女二',
    roleName: '车上',
    role: '女二 · 车上的人',
    outline: '同一趟车，同一段路，同一声爆。女主不是你。你是车上那个把小孩按住、把话一次说完的人。电影式的网剧，不靠金句翻盘，靠谁先把规则摸清楚，仍选择把人拉开。',
    roleBio: '她看起来普通。真正难演的是她第无数次仍伸手，且不把这事演成英雄。',
    plot: '车厢实拍。尺度审查。有几场只能坐着，把呼吸放平。口碑会先于热度到。',
    press: [
      '老钱在拍网剧《循环线》。浪潮时代的A级，同一趟车同一声爆。女二还在选。片方要拍得不像科幻，像事故。',
      '《循环线》审查已经来过。车上那个女人不是来解释规则的，是把人拉开的。',
      '拍悬疑的人都在看这部。女二戏份容易被剪，演住了才会留在正片里。',
    ],
    leads: ['何朗'],
    supporting: ['阮清'],
    need: { acting: 118, poise: 112, wit: 100 },
    weights: { acting: 4, poise: 3, wit: 2 },
    shootNeed: 14,
    promoNeed: 5,
    pay: 96000,
    recognition: 26,
    hype: 'award',
    awardTrack: true,
  }),
  S({
    id: 'twonight',
    title: '双面夜',
    type: '网剧',
    tags: ['网络剧'],
    theme: '刑侦',
    keywords: ['法医', '双面', '夜', '案子'],
    grade: 'A',
    fromYear: 2,
    company: '星汉文化',
    director: '齐衡',
    writer: '海宴客',
    roleKind: '女二',
    roleName: '法医',
    role: '女二 · 法医',
    outline: '夜里有两张脸在办案。女二是法医：她把人从台上接下来，把报告写得不像通稿。男主的秘密不归她说破，她只把刀口和时间为准。',
    roleBio: '她不吼。她把手套摘下来，把时间说完。难演的不是酷，是她知道谁在说谎，仍把字写清楚。',
    plot: '齐衡组。法医顾问进组。口型、伤口、记录时间都要过。连轴拍，妆要往虚里靠。',
    press: [
      '齐衡在拍网剧《双面夜》。星汉文化的A级刑侦，夜里两张脸。女二法医还没定。术语错一个，整条作废。',
      '《双面夜》路透出了停尸房。弹幕会先吵男主，法医那场顾问盯手。',
      '有人拿它跟那些夜里换一张脸办案的戏比。片方不认，只谈报告要像真的。',
    ],
    leads: ['何朗'],
    supporting: ['龙武山'],
    need: { acting: 120, speech: 114, wit: 108, poise: 100 },
    weights: { acting: 3, speech: 3, wit: 3 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 156000,
    recognition: 28,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'truthfile',
    title: '卷宗里',
    type: '网剧',
    tags: ['网络剧'],
    theme: '悬疑',
    keywords: ['法学生', '卷宗', '旧案', '沉默'],
    grade: 'A',
    fromYear: 2,
    company: '星汉文化',
    director: '老钱',
    writer: '唐纸',
    roleKind: '女二',
    roleName: '卷宗',
    role: '女二 · 翻卷宗的人',
    outline: '一桩被写成意外的旧案。女主不是你。你是法学院里那个把卷宗复印出来、夜里还在对时间的人。电影不靠反转金句，靠谁先把沉默撑破。',
    roleBio: '她成绩好，话硬。她不是来拯救的，是第一次决定把复印件交出去。演飘了会变成「良心发现」。',
    plot: '实景、复印室、审查。有几场不能哭，只能把夹子放下。',
    press: [
      '老钱在拍网剧《卷宗里》。星汉文化的A级，法学生翻旧案。女二还在选。审查盯尺度，片方要拍得不像说教。',
      '《卷宗里》一看完不敢说话。女二不是女主的影子：卷宗在她包里，话她先咽回去。',
      '金桂奖很少看这种网剧，口碑会比点击先到。几场不能哭，只能把夹子放下。',
    ],
    leads: ['白疏影'],
    supporting: ['许宁'],
    need: { acting: 122, speech: 118, wit: 120, poise: 108 },
    weights: { acting: 4, speech: 3, wit: 4 },
    shootNeed: 15,
    promoNeed: 5,
    pay: 88000,
    recognition: 30,
    hype: 'award',
    awardTrack: true,
    highlights: ['director'],
  }),
  S({
    id: 'supper',
    title: '晚饭以后',
    type: '上星剧',
    tags: ['上星剧'],
    theme: '家庭',
    keywords: ['晚饭', '离家', '家里', '体面'],
    grade: 'A',
    fromYear: 2,
    company: '天奇影视',
    director: '闻疏',
    writer: '梁晓声客',
    roleKind: '女二',
    roleName: '先走的人',
    role: '女二 · 先出社会的那个',
    outline: '一家人以晚饭为战场。女主不是你。你是最早离家、把钱寄回来、把体面先撑住的人。家里当你不懂事，外面当你很会过。她要演的是「我把家撑过了，所以我有资格不回家吃饭」。',
    roleBio: '她会应酬。她把饭桌上的话挡回去，把汇款单按住。难演的不是狠，是她回家仍会洗碗。',
    plot: '实景、晚饭、过年。闻疏不爱金句。集数拉长会把开会写成三集，真假家常会先被骂。',
    press: [
      '闻疏在拍上星剧《晚饭以后》。天奇影视的A级家庭戏。女二是家里最先离家的那个，不是来撕的。还在选。预告会先出晚饭那一桌。',
      '《晚饭以后》弹幕已经在刷我家也是这样。女二戏份重，白玉兰会不会看家庭戏，看成片。',
      '《晚饭以后》审查盯尺度。有人说像正剧，有人说集数会被拉得很长。闻疏说先把饭吃完。',
    ],
    leads: ['龙武山'],
    supporting: ['宋知夏'],
    need: { acting: 114, speech: 108, poise: 110 },
    weights: { acting: 4, speech: 3, poise: 3 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 132000,
    recognition: 24,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'sixfloor',
    title: '六号楼',
    type: '都市剧',
    tags: ['上星剧'],
    theme: '都市',
    keywords: ['合租', '楼', '闺蜜', '账'],
    grade: 'B',
    fromYear: 2,
    company: '浪潮时代',
    director: '陆深',
    writer: '乔南',
    roleKind: '女二',
    roleName: '三零二',
    role: '女二 · 三零二',
    outline: '一栋楼里几套房子。女主不是你。你是三零二：看起来最会过，账却先空。她把酒倒上，把同事的事挡回去，夜里自己算房租。不是恶毒女二，是那种先笑、后把灯关掉的人。',
    roleBio: '三零二会说话。她怕被看成乡下来的，比怕被讨厌更厉害。难演的不是精，是她把朋友送下楼以后，自己坐在门口抽烟。',
    plot: '城市实景。群像容易抢，演得住才会留。有一场酒，伸不伸手会改人设。',
    press: [
      '陆深在拍都市剧《六号楼》。浪潮时代的B级，一栋楼几套房子。女二三零二还在选。有人说像闺蜜楼，片方说别演成鸡汤。',
      '《六号楼》路透出了楼道。女二不是来抢男主的，是把账撑住的人。',
    ],
    leads: ['周棠'],
    supporting: ['阮清'],
    need: { acting: 106, speech: 100, looks: 98, confidence: 92 },
    weights: { acting: 3, speech: 3, looks: 2, confidence: 2 },
    shootNeed: 14,
    promoNeed: 5,
    pay: 114000,
    recognition: 20,
    hype: 'trade',
  }),
  S({
    id: 'listing',
    title: '挂牌',
    type: '都市剧',
    tags: ['上星剧'],
    theme: '职场',
    keywords: ['房子', '带看', '话术', '中介'],
    grade: 'B',
    fromYear: 2,
    company: '嘉尚影业',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女二',
    roleName: '带看',
    role: '女二 · 带看',
    outline: '房子要卖出去，话要说得像生活。女主是金牌。你是那个把脏房子先撑住、把业主的火接住的人。她不是来励志的：她把钥匙转一圈，把「这套能住」三个字说完，自己不一定住得起。',
    roleBio: '带看会笑。她把鞋套递给客人，把脏话咽回去。难演的不是能说，是她把别人的家说完，自己在地铁上不说话。',
    plot: '实景、样板间、电梯。闻疏不爱金句。话术顾问进组，错一个小区名，整条作废。',
    press: [
      '闻疏在拍都市剧《挂牌》。嘉尚影业的B级房产中介。女二带看还在选，要把脏房子撑住。片方说别演成鸡汤。',
      '《挂牌》顾问盯小区名。女二不是金牌，是先把火接住的人。',
    ],
    leads: ['江晚宁'],
    supporting: ['许宁'],
    need: { acting: 104, speech: 108, looks: 96, wit: 88 },
    weights: { speech: 4, acting: 3, looks: 2, wit: 2 },
    shootNeed: 14,
    promoNeed: 5,
    pay: 108000,
    recognition: 20,
    hype: 'trade',
  }),
  S({
    id: 'innnight',
    title: '同福夜',
    type: '古装网剧',
    tags: ['网络剧', '古装'],
    theme: '江湖',
    keywords: ['客栈', '跑堂', '江湖', '日子'],
    grade: 'B',
    fromYear: 2,
    company: '浪潮时代',
    director: '闵秋',
    writer: '方简',
    roleKind: '女二',
    roleName: '跑堂',
    role: '女二 · 跑堂',
    outline: '客栈不是宫。白天吵架，夜里把灯吹灭。女二是跑堂：她把江湖过成日子，把客人的秘密听完，不写成话本。轻，但是要把碗放下的那一下演准。',
    roleBio: '跑堂嘴快，心不散。她不是来闹的，是把客栈当成一条命。难演的不是逗，是她把人送走以后，自己把账对平。',
    plot: '室内戏多。闵秋要节奏，不要纯闹剧。女二戏份容易被剪成包袱，演住了才会留。',
    press: [
      '闵秋在拍古装网剧《同福夜》。浪潮时代的B级，客栈江湖。女二跑堂还在选。有人说像轻松喜剧，片方要碗放准。',
      '《同福夜》路透全是灶和院子。弹幕会当下饭剧，正片要的是夜里把灯吹灭那场。',
    ],
    leads: ['裴渡'],
    supporting: ['许宁'],
    need: { acting: 102, speech: 96, talent: 88, poise: 90 },
    weights: { acting: 3, speech: 3, talent: 2, poise: 2 },
    shootNeed: 14,
    promoNeed: 4,
    pay: 92000,
    recognition: 18,
    hype: 'trade',
  }),
  S({
    id: 'sketch',
    title: '画像',
    type: '网剧',
    tags: ['网络剧'],
    theme: '刑侦',
    keywords: ['画像', '嫌疑人', '脸', '案子'],
    grade: 'A',
    fromYear: 2,
    company: '星汉文化',
    director: '齐衡',
    writer: '周湛',
    roleKind: '女二',
    roleName: '画像师',
    role: '女二 · 画像师',
    outline: '一张脸从口述里长出来。女二是画像师：她不审人，她把人画准。证人说谎，笔不能跟着谎走。她不是女主，却是这部里唯一能让嫌疑人坐不住的人。',
    roleBio: '她看人的时间比说话长。难演的不是天才，是她把像画完，仍把「这只是像」四个字留下。',
    plot: '齐衡组。顾问盯手和比例。有几场只能画，不能解释案情。',
    press: [
      '齐衡在拍网剧《画像》。星汉文化的A级刑侦。女二画像师还在选。顾问盯手。',
      '《画像》预告先出橡皮。弹幕会当破案，正片要的是她把像交给警方、自己先走。',
    ],
    leads: ['何朗'],
    supporting: ['白疏影'],
    need: { acting: 118, wit: 116, looks: 90, poise: 104 },
    weights: { acting: 3, wit: 4, poise: 2 },
    shootNeed: 15,
    promoNeed: 5,
    pay: 124000,
    recognition: 24,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'listenwind',
    title: '听风楼',
    type: '年代剧',
    tags: ['上星剧'],
    theme: '民国',
    keywords: ['民国', '楼', '地下', '大小姐'],
    grade: 'A',
    fromYear: 2,
    company: '嘉尚影业',
    director: '邢未',
    writer: '流朱',
    roleKind: '女二',
    roleName: '大小姐',
    role: '女二 · 听风楼的人',
    outline: '民国。楼里有人听戏，有人传话。女二是大小姐：她把宴会撑住，把一张纸条从袖口递出去。她不是女主，却是这部里唯一能在客厅和后巷用同一张脸的人。',
    roleBio: '她会笑，也会把茶杯放正。难演的不是飒，是她把人送出门以后，自己把口红补上。',
    plot: '宴席、旗袍、暗号。邢未不爱枪战撑场。仪态错一个，整条作废。',
    press: [
      '邢未在拍年代剧《听风楼》。嘉尚影业的A级，民国宴会上袖口里有纸条。女二还在选。有人说像谍战，片方说先把客厅拍住。',
      '《听风楼》服装造型路透。头上的饰品比人先传开。女二不是花瓶大小姐。',
      '审查会盯纸条怎么拍。女二戏份重，白玉兰会不会看年代戏，看成片。',
    ],
    leads: ['陆承宴'],
    supporting: ['陈晚秋'],
    need: { acting: 120, poise: 118, speech: 100, looks: 108 },
    weights: { acting: 4, poise: 4, looks: 2, speech: 2 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 162000,
    recognition: 28,
    hype: 'trade',
    awardTrack: true,
    highlights: ['hype'],
  }),
  S({
    id: 'audit',
    title: '造价',
    type: '都市剧',
    tags: ['上星剧'],
    theme: '职场',
    keywords: ['审计', '造价', '项目', '数字'],
    grade: 'A',
    fromYear: 2,
    company: '天奇影视',
    director: '邢伟',
    writer: '徐纪周客',
    roleKind: '女二',
    roleName: '造价',
    role: '女二 · 把数算完的人',
    outline: '项目要从标书走到竣工。女主不是你。你是造价：酒桌上把话挡回去，表格里把人救出来。数字不能错。她不是来励志的，是把「这钱不该付」说完。',
    roleBio: '她不吼。她把表格推过去，让别人先吵。台词是科目和人名，不能错。',
    plot: '会议室、工地、酒桌。顾问盯口型。集数被拉长的传闻会比正片先到。',
    press: [
      '邢伟在拍都市剧《造价》。天奇影视的A级审计职场。女二还没定。预告会先吵海报上谁的名字在前。',
      '《造价》顾问盯会计科目。女二不是花瓶职场，表格和酒桌都是戏。',
      '《造价》被写成今年的年度职场。像不像真实项目，传闻已经被压过一轮。',
    ],
    leads: ['江晚宁', '裴渡'],
    supporting: ['许宁'],
    need: { acting: 116, wit: 124, speech: 108, poise: 96 },
    weights: { wit: 4, speech: 3, acting: 3 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 140000,
    recognition: 26,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'phototime',
    title: '旧照',
    type: '网剧',
    tags: ['网络剧'],
    theme: '时间',
    keywords: ['照相馆', '旧照', '同一张脸', '时间'],
    grade: 'A',
    fromYear: 2,
    company: '浪潮时代',
    director: '陆深',
    writer: '乔南',
    roleKind: '女二',
    roleName: '照相馆',
    role: '女二 · 照相馆',
    outline: '同一张脸出现在两叠照片里。女主去把人找回来。你是照相馆：冲胶片、报时间、把「她来过」四个字说完。不是甜，是把时间缝先撑住的人。原著粉会先写成爱情，成片要的是她把灯关掉。',
    roleBio: '照相馆话少。她把照片夹好，不问来的人要去哪一年。难演的不是穿越感，是她明明认得那张脸，仍把工钱收好。',
    plot: '棚、暗房、同一条街。陆深不爱金句。时间线审查，错一个日期，整条作废。',
    press: [
      '陆深在拍网剧《旧照》。浪潮时代的A级，同一张脸两叠照片。女二照相馆还在选。粉丝会先写成爱情，片方要先把灯关掉。',
      '《旧照》时间线过了审查。女二不是女主的影子：她认得，却不跟。',
      '《旧照》预告先出暗房。有人说今年需要这种，有人说看不懂。',
    ],
    leads: ['周棠'],
    supporting: ['阮清'],
    need: { acting: 112, looks: 108, poise: 110, confidence: 96 },
    weights: { acting: 3, poise: 3, looks: 2, confidence: 2 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 126000,
    recognition: 24,
    hype: 'trade',
  }),
  S({
    id: 'nightvisit',
    title: '夜访',
    type: '访谈',
    track: 'variety',
    tags: ['综艺'],
    theme: '访谈',
    keywords: ['访谈', '夜里', '行业', '真话'],
    grade: 'A',
    fromYear: 2,
    company: '星汉文化',
    director: '总导演',
    writer: '环节组',
    roleKind: '嘉宾',
    roleName: '自己',
    role: '对谈嘉宾',
    outline: '一档把人留到夜里才问的访谈。你不唱歌，只把行业里的事说完。太圆滑会显得无聊，随口一句说重了，播出后就是热搜。',
    roleBio: '你演自己。观察室里的人要会看、会接话，也要知道哪句不能说完。',
    plot: '录制多在晚上。镜头会切到你听完沉默的那一秒。',
    press: [
      '星汉文化的访谈《夜访》还在找对谈嘉宾。A级，夜里问，不走游戏环节。节目组要能把话说满、也知道哪句不能说完的人。',
      '《夜访》先放出了沉默。有人靠一句真话上了热搜，有人靠一句口误。',
    ],
    leads: [],
    supporting: ['许宁'],
    need: { speech: 108, confidence: 100, poise: 92 },
    weights: { speech: 4, confidence: 3, poise: 2 },
    shootNeed: 8,
    promoNeed: 3,
    pay: 62000,
    recognition: 18,
  }),
  S({
    id: 'ostnamed',
    title: '片尾有名',
    type: '剧宣曲',
    track: 'music',
    tags: ['剧宣曲'],
    theme: '剧集宣传',
    keywords: ['片尾', '署名', '副歌'],
    grade: 'B',
    fromYear: 2,
    company: '海潮唱片',
    director: '制作人阿白',
    writer: '阿白',
    roleKind: '歌手',
    roleName: '自己',
    role: '独唱。有名字。',
    outline: '剧要一首片尾，名字要出现。副歌要唱满，发行日不能拖。这回不是未署名。',
    roleBio: '这回有名字。封面、词、发行日都已经定了。',
    plot: '除了录歌，还要拍封面和跑发行采访。贴剧里的人物情绪，不能唱成自己的抒情。',
    press: [
      '海潮唱片的剧宣曲《片尾有名》还在找声音。B级，要署名，不要躲在和声里。',
      '《片尾有名》预告先出副歌。弹幕在猜是谁，厂牌还没官宣。',
    ],
    leads: [],
    supporting: [],
    need: { talent: 88, speech: 62, poise: 70 },
    weights: { talent: 5, speech: 2, poise: 1 },
    shootNeed: 6,
    promoNeed: 4,
    pay: 48000,
    recognition: 14,
    roleTier: 'second',
  }),
  S({
    id: 'bund',
    title: '外滩灯',
    type: '年代剧',
    tags: ['上星剧'],
    theme: '年代',
    keywords: ['上海', '九十年代', '生意', '夜里'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女主',
    roleName: '灯',
    role: '女主 · 灯',
    outline: '上海。九十年代的灯比合同先亮。女主把生意和夜里的饭局同时撑住。她不是来怀旧的：她把货谈成，把人送走，把「我还能再来」三个字留下。服装造型会先被夸，人要后到。',
    roleBio: '灯会应酬。她把酒杯放下，把数字说完。女主要能把体面演满，也把体面后面的那一口气留下。年龄要演开。',
    plot: '实景、夜、黄浦。闻疏不爱金句。集数拉长会把开会写成三集，真假年代感会先被骂。',
    press: [
      '闻疏在拍年代剧《外滩灯》。嘉尚影业的S级，上海九十年代，女主把生意和夜里的饭局同时撑住。女主还在选。圈里说这是今年的年代正路，也有人说吃力不讨好。',
      '《外滩灯》路透全是灯和雨。弹幕会先夸服装造型。女主栏还空着。',
      '《外滩灯》预告出了晚饭那一桌。有人说像正剧，有人说集数会被拉得很长。国剧奖会看她有没有把「过来」演成压力。',
    ],
    leads: ['陆承宴'],
    supporting: ['江晚宁'],
    need: { acting: 150, fashion: 132, poise: 140, looks: 118 },
    weights: { acting: 4, poise: 3, fashion: 3, looks: 2 },
    shootNeed: 24,
    promoNeed: 8,
    pay: 720000,
    recognition: 42,
    hype: 'ip',
    awardTrack: true,
    highlights: ['hype', 'director'],
  }),
  S({
    id: 'rivermouth',
    title: '大江口',
    type: '年代剧',
    tags: ['上星剧'],
    theme: '改革',
    keywords: ['厂', '会计', '改革', '三十年'],
    grade: 'S',
    fromYear: 3,
    company: '天奇影视',
    director: '邢伟',
    writer: '梁晓声客',
    roleKind: '女主',
    roleName: '账',
    role: '女主 · 厂里的账',
    outline: '厂门口的三十年。女主从姑娘演到把账本交出去。改革不是口号：她把数字算完，把人从局里托出来，也把家里的事忍下。群像里要站得住。',
    roleBio: '账不是完人。她把厂里的事做完，把外面的事按住。女主要能把年龄演开，把「这钱不该动」说完。',
    plot: '跨年拍摄。妆容、口音、年代物不能错。邢伟不爱哭戏。',
    press: [
      '邢伟在拍年代剧《大江口》。天奇影视的S级，厂门口三十年，女主从姑娘演到把账本交出去。女主还在选。有人说像正剧，有人说集数会被拉得很长。',
      '《大江口》预告出了厂门口。弹幕在刷我们厂也是这样过来的。',
      '白玉兰观察名单里有这部。已经有人问女主奖，评奖会把三十年拆开看。',
    ],
    leads: ['何朗', '龙武山'],
    supporting: ['宋知夏'],
    need: { acting: 148, wit: 138, poise: 132, speech: 112 },
    weights: { acting: 4, wit: 4, poise: 3, speech: 2 },
    shootNeed: 24,
    promoNeed: 7,
    pay: 580000,
    recognition: 40,
    hype: 'trade',
    awardTrack: true,
    highlights: ['director'],
  }),
  S({
    id: 'yanfu',
    title: '严府灯',
    type: '古装剧',
    tags: ['上星剧', '古装'],
    theme: '朝堂',
    keywords: ['严府', '朝堂', '灯', '女配'],
    grade: 'A',
    fromYear: 3,
    company: '天奇影视',
    director: '邢伟',
    writer: '海宴客',
    roleKind: '女配角',
    roleName: '严府',
    role: '女配 · 严府里的人',
    outline: '朝堂上的账从一盏灯算起。你不是女主。你是严府里那个把茶续上、把话听完、把「今晚谁不能出门」记在心里的人。正剧，不靠打戏。评委会盯「像不像在府里站过」。',
    roleBio: '她话少。她把灯拨亮，把名单留下。哭是减分。',
    plot: '朝仪、夜谈、一封信。邢伟不爱重来。片酬普通，口碑会先于热度到。',
    press: [
      '邢伟在拍古装剧《严府灯》。天奇影视的A级朝堂正剧，不是宫斗。还在找严府里那个把茶续上、把话听完的女人。',
      '《严府灯》审查已经来过。这个配角不是来解释朝政的。电影金桂奖不看剧，白玉兰会看。',
    ],
    leads: ['龙武山'],
    supporting: ['陈晚秋'],
    need: { acting: 140, poise: 144, wit: 128, speech: 96 },
    weights: { acting: 4, poise: 4, wit: 3 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 180000,
    recognition: 36,
    hype: 'award',
    awardTrack: true,
  }),
  S({
    id: 'lawful',
    title: '正当',
    type: '电影',
    tags: ['电影'],
    theme: '现实',
    keywords: ['正当防卫', '法庭', '姐姐', '法条'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '老钱',
    writer: '周湛',
    roleKind: '女二',
    roleName: '姐姐',
    role: '女二 · 把话送到法庭的人',
    outline: '一桩被写成互殴的事。女主不是你。你是那个把正当防卫四个字送到法庭、把家属按住的人。电影会让广场骂，评委会盯「像不像真的把法条说完」。',
    roleBio: '她不是圣人。她把价钱和后果说清楚，然后把卷宗推过桌子。难演的不是哭，是她说完以后不再解释。',
    plot: '法庭、走廊、审查。片酬普通。冲奖。女二戏份容易被写成工具人。',
    press: [
      '老钱在拍电影《正当》。嘉尚影业的S级，一桩被写成互殴的事。女二把正当防卫四个字送到法庭，还在选。审查已经来过一轮。',
      '《正当》片酬普通，冲奖。有人说这是该走的路，有人说接了就是往舆论上撞。',
      '金桂观察名单里有这部。顾问盯法条口型。',
    ],
    leads: ['何朗'],
    supporting: ['白疏影'],
    need: { acting: 152, speech: 148, wit: 130, poise: 126 },
    weights: { acting: 4, speech: 5, wit: 3, poise: 2 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 220000,
    recognition: 46,
    hype: 'award',
    awardTrack: true,
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'changan',
    title: '长安信',
    type: '电影',
    tags: ['电影'],
    theme: '诗',
    keywords: ['长安', '诗', '信', '送行'],
    grade: 'A',
    fromYear: 3,
    company: '星汉文化',
    director: '沈照',
    writer: '沈照',
    roleKind: '女配角',
    roleName: '送行',
    role: '女配 · 把信送走的人',
    outline: '诗和路都在长安之外。你不是女主。你是把信送到、把人送走、自己不入画的人。电影不靠台词赢。评委会盯停顿。',
    roleBio: '她几乎不哭。她把信按进袖里，把路让开。漂亮是减分。',
    plot: '不让探班。沈照只说再短一点。片酬低，口碑会比票房先到。',
    press: [
      '沈照在拍电影《长安信》。星汉文化的A级，诗和路都在长安之外。还在找把信送到、自己不入画的女人。几乎不靠台词。',
      '《长安信》电影院不一定肯多排。女配也能进候选。片方不谈奖，只谈她像不像把人送走过。',
    ],
    leads: ['何朗'],
    supporting: [],
    need: { acting: 132, talent: 120, poise: 140, looks: 74 },
    weights: { acting: 4, poise: 4, talent: 3, looks: 1 },
    shootNeed: 12,
    promoNeed: 4,
    pay: 96000,
    recognition: 38,
    hype: 'award',
    awardTrack: true,
    meetNpc: 'shenzhao',
    highlights: ['director'],
  }),
  S({
    id: 'exitvisa',
    title: '出境',
    type: '电影',
    tags: ['电影'],
    theme: '悬疑',
    keywords: ['找人', '出境', '手续', '沉默'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '老钱',
    writer: '游晓颖客',
    roleKind: '女主',
    roleName: '找',
    role: '女主 · 去把人找回来',
    outline: '人在境外失踪。女主去办手续、等窗口、把照片递进去。电影不靠反转三连：她找到的不一定是她要的人。金桂会看，广场会先写成复仇。接了，就是拿档期去换一次被评委看见。',
    roleBio: '找话少。她把材料码齐，把翻译耳机戴上。女主要能把「回来」演满，而不是把「赢」演满。',
    plot: '实景、窗口、审查。老钱不爱金句。片酬普通，评奖会盯女主。漂亮是减分。',
    press: [
      '老钱在拍电影《出境》。嘉尚影业的S级，窗口、手续、找人。还在找女主。有人说像类型片，有人说太冷。',
      '《出境》审查会盯找到以后怎么办。金桂奖会看，网上会先骂。',
      '《出境》选角要她像在窗口站过。手、口型、护照页，顾问盯着。',
    ],
    leads: [],
    supporting: ['白疏影'],
    need: { acting: 156, poise: 148, speech: 118, looks: 78 },
    weights: { acting: 5, poise: 4, speech: 2, looks: 1 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 168000,
    recognition: 52,
    hype: 'award',
    awardTrack: true,
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'troupe',
    title: '文工团',
    type: '年代剧',
    tags: ['上星剧'],
    theme: '文工',
    keywords: ['文工团', '跳舞', '年代', '青春'],
    grade: 'A',
    fromYear: 3,
    company: '嘉尚影业',
    director: '闵秋',
    writer: '流朱',
    roleKind: '女二',
    roleName: '伴舞',
    role: '女二 · 伴舞',
    outline: '文工团。台上齐，台下不是。女主不是你。你是伴舞：把队形站住，把一句闲话听完，把「我也可以独唱」咽回去。青春会先被写成粉，成片要的是她把鞋带系上。',
    roleBio: '她会跳。她把笑摆在脸上，把名次留下。难演的不是纯，是她把人让到前面以后，自己还在喘。',
    plot: '排练、巡演、年代物。才艺要过。闵秋要队形，不要纯怀旧。',
    press: [
      '闵秋在拍年代剧《文工团》。嘉尚影业的A级。女二伴舞还在选，要把名次咽回去。才艺过不了直接停。',
      '《文工团》路透出了练功房。有人说像青春，片方要别演成偶像。',
    ],
    leads: ['宋知夏'],
    supporting: ['周棠'],
    need: { acting: 138, talent: 128, poise: 120, fitness: 110 },
    weights: { acting: 3, talent: 4, poise: 3, fitness: 2 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 160000,
    recognition: 32,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'northland',
    title: '北疆风',
    type: '电影',
    tags: ['电影'],
    theme: '文艺',
    keywords: ['北疆', '牧场', '风', '寄居'],
    grade: 'A',
    fromYear: 3,
    company: '星汉文化',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女配角',
    roleName: '牧场',
    role: '女配 · 牧场上的人',
    outline: '去北疆住一阵。女主不是你。你是牧场：借马、借路、把外乡人留下来喝一碗奶茶。戏慢，没有爽点，口碑会两极。',
    roleBio: '她把日子过好，不问来的人要去哪。真正难演的是不催情节。',
    plot: '实景、风、长镜头。闻疏不爱快剪。妆面要往土里靠。',
    press: [
      '闻疏在拍电影《北疆风》。星汉文化的A级，牧场、慢、没有爽点。还在找牧场那个女人。有人说今年需要这种，有人说播不完。',
      '《北疆风》路透全是风和电线。弹幕会吵剧情呢。',
    ],
    leads: ['宋知夏'],
    supporting: [],
    need: { acting: 134, poise: 142, looks: 88, speech: 80 },
    weights: { acting: 3, poise: 4, looks: 1 },
    shootNeed: 14,
    promoNeed: 4,
    pay: 84000,
    recognition: 34,
    hype: 'award',
    awardTrack: true,
  }),
  S({
    id: 'county',
    title: '大院',
    type: '上星剧',
    tags: ['上星剧'],
    theme: '基层',
    keywords: ['大院', '秘书', '基层', '会'],
    grade: 'A',
    fromYear: 3,
    company: '天奇影视',
    director: '邢伟',
    writer: '徐纪周客',
    roleKind: '女二',
    roleName: '秘书',
    role: '女二 · 秘书',
    outline: '县委大院里的一年。女二是秘书：她把会务做完，把不该进门的话挡回去，把「这件事过不了」说给该听的人。她不是女主，却是这部里唯一能把会议写成戏的人。',
    roleBio: '她不吼。她把文件放正，让别人先吵。台词是人名和流程，不能错。',
    plot: '实景、会议、集数被拉长的传闻会比正片先到。顾问盯口型。',
    press: [
      '邢伟在拍上星剧《大院》。天奇影视的A级基层。女二秘书还没定，要把话挡回去。预告会先吵海报上谁的名字在前。',
      '《大院》已经有人说集数被拉得很长。编剧把开会写成三集。秘书那场，顾问盯流程。',
    ],
    leads: ['龙武山'],
    supporting: ['裴渡'],
    need: { acting: 140, speech: 128, wit: 122, poise: 118 },
    weights: { acting: 3, speech: 4, wit: 3, poise: 2 },
    shootNeed: 18,
    promoNeed: 6,
    pay: 190000,
    recognition: 34,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'shnight',
    title: '夜谈',
    type: '电影',
    tags: ['电影'],
    theme: '都市',
    keywords: ['上海', '饭局', '中产', '夜'],
    grade: 'A',
    fromYear: 3,
    company: '嘉尚影业',
    director: '闻疏',
    writer: '唐纸',
    roleKind: '女二',
    roleName: '饭局',
    role: '女二 · 饭局里的人',
    outline: '上海夜里的一桌。女主不是你。你是把酒倒上、把话挡回去、把「我们这代人」五个字说完又不说完的人。电影不靠金句，靠谁先把沉默撑破。',
    roleBio: '她会笑。她把话题转开，把真话说一半。难演的不是犀利，是她把车钥匙放下以后，自己也不走。',
    plot: '实景、饭局、长镜头。闻疏不爱快剪。口碑会两极。',
    press: [
      '闻疏在拍电影《夜谈》。嘉尚影业的A级，上海饭局。女二还在选，把话说一半。有人说像纪实，有人说太闲。',
      '《夜谈》一看完不敢说话。女二不是来解释中产的。金桂奖会不会看，看成片。',
    ],
    leads: ['何朗'],
    supporting: ['江晚宁'],
    need: { acting: 142, speech: 126, poise: 130, looks: 108 },
    weights: { acting: 4, speech: 3, poise: 3 },
    shootNeed: 12,
    promoNeed: 4,
    pay: 180000,
    recognition: 36,
    hype: 'award',
    awardTrack: true,
  }),
  S({
    id: 'mythcamp',
    title: '祭台',
    type: '大制作电影',
    tags: ['电影', '大 IP'],
    theme: '神话',
    keywords: ['质子府', '祭台', '神话', '大制作'],
    grade: 'S',
    fromYear: 3,
    company: '嘉尚影业',
    director: '裴衡',
    writer: '原著改编',
    roleKind: '女二',
    roleName: '质子府',
    role: '女二 · 质子府的人',
    outline: '神话史诗。女主不是你。你是质子府里那个把礼做完、把「我不是来当诱饵的」说完的人。特效会先传开，人要后到。粉丝、服装造型、提前点播会把你先吵一遍。',
    roleBio: '她看起来冷。她把礼器放下，把旧名字留下。女二要能把一场不说话的戏撑住，不能演成工具人。',
    plot: '大制作。投资人盯脸，导演盯一场礼。提前点播、给国外看的宣传会先到。',
    press: [
      '裴衡在拍大制作电影《祭台》。嘉尚影业的S级神话。女二是质子府里把礼做完的人，还没定。给国外看的宣传已经在做，粉丝比剧组快。',
      '《祭台》服装造型路透。假发套又看得出来。提前点播的预告先出了女二那一眼。',
      '《祭台》和宫斗、仙侠不是一条路。片方要礼、骨，把诱饵两个字按住。',
    ],
    leads: ['陆承宴'],
    supporting: ['江晚宁'],
    need: { acting: 146, poise: 148, looks: 130, confidence: 122 },
    weights: { acting: 4, poise: 4, looks: 3, confidence: 2 },
    shootNeed: 22,
    promoNeed: 8,
    pay: 860000,
    recognition: 44,
    hype: 'ip',
    highlights: ['hype', 'cast'],
  }),
  S({
    id: 'cliff',
    title: '冰崖',
    type: '电影',
    tags: ['电影'],
    theme: '谍战',
    keywords: ['雪', '地下', '任务', '一张脸'],
    grade: 'S',
    fromYear: 3,
    company: '星汉文化',
    director: '老钱',
    writer: '流朱',
    roleKind: '女二',
    roleName: '接头',
    role: '女二 · 接头的人',
    outline: '雪地里的一次接头。女主不是你。你是把暗号说完、把人送走、自己不一定活着走回来的人。电影把任务摊在桌上，不给革命口号。金桂会看女配。',
    roleBio: '她会笑。她把接头词说得像闲聊。难演的不是狠，是她把人送出门以后，自己把妆补上。',
    plot: '不让探班。审查。片酬普通。冲奖。女二戏份容易被剪成只出一会儿。',
    press: [
      '老钱在拍电影《冰崖》。星汉文化的S级，雪地接头。女二还在选。审查已经改了两稿。',
      '《冰崖》片酬普通，冲奖。有人说这是该走的路，有人说接了就是浪费当红档期。',
      '金桂女配观察。试镜要一场把暗号说成闲聊。',
    ],
    leads: ['何朗'],
    supporting: ['陈晚秋'],
    need: { acting: 150, poise: 146, speech: 110, looks: 100 },
    weights: { acting: 5, poise: 4, speech: 2 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 140000,
    recognition: 48,
    hype: 'award',
    awardTrack: true,
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'zhengyang',
    title: '正阳门',
    type: '年代剧',
    tags: ['上星剧'],
    theme: '京味',
    keywords: ['京味', '门', '买卖', '邻里'],
    grade: 'A',
    fromYear: 3,
    company: '天奇影视',
    director: '邢伟',
    writer: '梁晓声客',
    roleKind: '女主',
    roleName: '门',
    role: '女主 · 门口的人',
    outline: '一门里的几十年。女主把买卖做成邻里，把脸面和账同时撑住。不是甜宠，是把「这门口还开着」演满。真假京味会先被骂。',
    roleBio: '门会应酬。她把客人送走，把家里的事按住。女主要能把年龄演开。',
    plot: '实景、胡同、过年。口音不能错。邢伟不爱金句。',
    press: [
      '邢伟在拍年代剧《正阳门》。天奇影视的A级京味，一门里的几十年。女主还在选。有人说像正剧，有人说集数会被拉得很长。',
      '《正阳门》预告出了门口那一桌。弹幕在刷我们胡同也是这样过来的。',
    ],
    leads: ['龙武山'],
    supporting: ['宋知夏'],
    need: { acting: 144, speech: 120, poise: 128, wit: 108 },
    weights: { acting: 4, poise: 3, speech: 3 },
    shootNeed: 22,
    promoNeed: 7,
    pay: 380000,
    recognition: 36,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'signedname',
    title: '署名',
    type: '上星剧',
    tags: ['上星剧'],
    theme: '反腐',
    keywords: ['检察', '署名', '案子', '签字'],
    grade: 'S',
    fromYear: 3,
    company: '天奇影视',
    director: '邢伟',
    writer: '徐纪周客',
    roleKind: '女二',
    roleName: '检察',
    role: '女二 · 把字签上的人',
    outline: '一省的案子从签字翻到厅局。女二是检察官：她接的是没人敢接的卷，酒桌上把话挡回去，报告里把人写进去。她不是女主，却是这部里唯一能把「我署名」三个字说得不像口号的人。',
    roleBio: '她不吼。她把证据放在桌上，让别人先吵。台词是法条和人名，不能错。',
    plot: '实景、群众演员、集数被拉长的传闻会比正片先到。律师戏要过顾问。',
    press: [
      '邢伟在拍上星剧《署名》。天奇影视的S级，检察签字。女二还没定。预告会先吵海报上谁的名字在前。',
      '《署名》已经有人说集数被拉得很长。检察那场，顾问盯口型。',
      '《署名》被写成今年的年度剧。女二不是花瓶，卷宗和酒桌都是戏。像不像真实案子，传闻已经被压过一轮。',
    ],
    leads: ['龙武山', '裴渡'],
    supporting: ['许宁'],
    need: { acting: 146, speech: 140, wit: 136, poise: 122 },
    weights: { speech: 4, acting: 3, wit: 4 },
    shootNeed: 20,
    promoNeed: 7,
    pay: 320000,
    recognition: 42,
    hype: 'trade',
    awardTrack: true,
    highlights: ['director', 'hype'],
  }),
  S({
    id: 'along',
    title: '沿途',
    type: '上星剧',
    tags: ['上星剧'],
    theme: '路上',
    keywords: ['列车', '沿途', '站', '年'],
    grade: 'A',
    fromYear: 3,
    company: '天奇影视',
    director: '邢伟',
    writer: '周湛',
    roleKind: '女主',
    roleName: '车',
    role: '女主 · 列车上的人',
    outline: '一条线跑过十几年。女主把车开过站，把人送回家，把「这班还在」演满。群像，集数拉长会把开会写成三集。真假路上会先被骂。',
    roleBio: '车会应酬。她把广播词说完，把夜里的事按住。女主要能把年龄演开。',
    plot: '实景、车厢、春运。口音、年代物不能错。',
    press: [
      '邢伟在拍上星剧《沿途》。天奇影视的A级，一条线跑过十几年。女主还在选，把人送回家。有人说像正剧，有人说集数会被拉得很长。',
      '《沿途》预告出了到站。弹幕在刷我们那班也是这样过来的。',
    ],
    leads: ['何朗'],
    supporting: ['裴渡'],
    need: { acting: 142, poise: 130, speech: 118, fitness: 96 },
    weights: { acting: 4, poise: 3, speech: 3 },
    shootNeed: 20,
    promoNeed: 6,
    pay: 360000,
    recognition: 36,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'oldwine',
    title: '老酒',
    type: '年代剧',
    tags: ['上星剧'],
    theme: '东北',
    keywords: ['酒馆', '东北', '老', '邻里'],
    grade: 'A',
    fromYear: 3,
    company: '浪潮时代',
    director: '闵秋',
    writer: '方简',
    roleKind: '女二',
    roleName: '柜',
    role: '女二 · 柜上的人',
    outline: '东北一座酒馆。女主不是你。你是柜：把酒打上，把人劝走，把「这杯不算」四个字说完。轻，但是要把日子过成一条命。',
    roleBio: '柜嘴快，心不散。她不是来闹的。难演的不是逗，是她把人送走以后，自己把灯留下。',
    plot: '室内戏多。闵秋要节奏，不要纯怀旧。口音不能飘。',
    press: [
      '闵秋在拍年代剧《老酒》。浪潮时代的A级，东北一座酒馆。女二柜上还在选。有人说像轻松喜剧，片方要灯留下。',
      '《老酒》路透全是灶和雪。弹幕会当下饭剧，正片要的是夜里把灯吹灭那场。',
    ],
    leads: ['龙武山'],
    supporting: ['许宁'],
    need: { acting: 136, speech: 122, poise: 124, talent: 88 },
    weights: { acting: 4, speech: 3, poise: 3 },
    shootNeed: 16,
    promoNeed: 5,
    pay: 168000,
    recognition: 30,
    hype: 'trade',
    awardTrack: true,
  }),
  S({
    id: 'carpetnight',
    title: '红毯席',
    type: '访谈',
    track: 'variety',
    tags: ['综艺'],
    theme: '红毯',
    keywords: ['红毯', '观察', '礼服', '席'],
    grade: 'A',
    fromYear: 3,
    company: '星汉文化',
    director: '总导演',
    writer: '环节组',
    roleKind: '观察员',
    roleName: '自己',
    role: '飞行观察员',
    outline: '颁奖季的飞行观察。你不走红毯，只在席上看谁先到、谁把话挡回去。太圆滑会显得无聊，随口一句说重了，播出后就是热搜。',
    roleBio: '你演自己。要会看、会接话，也要知道哪句不能说完。',
    plot: '录制赶典礼。镜头会切到你听完沉默的那一秒。',
    press: [
      '星汉文化的访谈《红毯席》还在找观察员。A级，你不走红毯，只在席上看谁先到、谁把话挡回去。节目组要能接话、也敢把话说满的人。',
      '《红毯席》先放出了沉默。有人靠一句点评上了热搜。',
    ],
    leads: [],
    supporting: ['许宁'],
    need: { speech: 118, confidence: 108, fashion: 110, poise: 104 },
    weights: { speech: 4, fashion: 3, confidence: 3, poise: 2 },
    shootNeed: 6,
    promoNeed: 3,
    pay: 88000,
    recognition: 22,
  }),
  S({
    id: 'solotour',
    title: '独唱夜',
    type: '独立单曲',
    track: 'music',
    tags: ['单曲'],
    theme: '发行',
    keywords: ['独唱', '小样', '发行'],
    grade: 'B',
    fromYear: 3,
    company: '海潮唱片',
    director: '制作人阿白',
    writer: '阿白',
    roleKind: '歌手',
    roleName: '自己',
    role: '独唱。有名字。',
    outline: '一张要巡演前先上架的单曲。封面、词、发行日都已经定了，差一个敢把副歌唱满的人。',
    roleBio: '这回有名字。发行日不能拖。',
    plot: '除了录歌，还要拍封面和跑发行采访。第三次以自己的名字发歌，每个环节都得本人出现。',
    press: [
      '海潮唱片的单曲《独唱夜》还在找声音。B级，巡演前要先上架，不要躲在和声里。',
      '《独唱夜》小样先出副歌。弹幕在猜是谁。',
    ],
    leads: [],
    supporting: [],
    need: { talent: 110, speech: 80, poise: 88, confidence: 96 },
    weights: { talent: 5, speech: 2, confidence: 2 },
    shootNeed: 8,
    promoNeed: 5,
    pay: 86000,
    recognition: 20,
    roleTier: 'second',
  }),
]

export function scriptById(id: string): ScriptDef | undefined {
  return SCRIPTS.find((s) => s.id === id)
}

export function rumorLine(script: ScriptDef, week = 1): string {
  if (script.press.length) {
    return script.press[(week + script.id.length) % script.press.length]
  }
  return `《${script.title}》还在选${roleLine(script)}。${script.director}还没点头。`
}

export function scriptMatch(attrs: Attrs, script: ScriptDef): number {
  let num = 0
  let den = 0
  for (const k of ATTR_KEYS) {
    const need = script.need[k]
    if (!need) continue
    const w = script.weights[k] ?? 1
    num += Math.min(1.25, attrs[k] / need) * w
    den += w
  }
  return den ? Math.min(100, Math.round((100 * num) / den)) : 50
}

export function matchWord(n: number): string {
  if (n >= 82) return '倒像你'
  if (n >= 64) return '能试试'
  if (n >= 48) return '有点勉强'
  return '现在不像'
}

export function canTakeScript(
  attrs: Attrs,
  script: ScriptDef,
  career?: { recognition: number; fans: number },
): boolean {
  if (!ATTR_KEYS.every((k) => (script.need[k] ?? 0) <= attrs[k])) return false
  if (script.awardTrack) {
    if (script.roleTier === 'lead') {
      if ((career?.recognition ?? 0) < 80) return false
      if ((career?.fans ?? 0) < 60000) return false
    } else {
      if ((career?.recognition ?? 0) < 32) return false
      if ((career?.fans ?? 0) < 20000) return false
    }
  }
  return true
}

export function hypeLine(script: ScriptDef): string {
  if (script.hype === 'ip') return '原著读者很多，选角消息一直有人关注。'
  if (script.hype === 'award') return '导演和剧本更受业内关注，商业回报未必稳定。'
  if (script.roleTier === 'second' || script.roleTier === 'lead') return '角色戏份较重，试镜会有多轮。'
  if (script.grade === 'S' || script.grade === 'A') return '制作周期较长，主创团队已经确定。'
  return ''
}

const HIGHLIGHT_NAME: Record<ScriptHighlight, string> = {
  fame: '项目讨论度较高',
  director: '导演受业内关注',
  cast: '主要演员阵容已经确定',
  hype: '前期宣传投入较多',
}

export function highlightLine(script: ScriptDef): string {
  if (!script.highlights?.length) return ''
  return `${script.highlights.map((h) => HIGHLIGHT_NAME[h]).join('；')}。`
}

export function roleLine(script: ScriptDef): string {
  if (script.track === 'music') {
    if (script.roleTier === 'second') return '独唱。有名字。'
    return '声音。不一定有名字。'
  }
  if (script.track === 'variety') return script.roleKind
  if (script.roleTier === 'lead') return '女主'
  if (script.roleTier === 'second') return '女二'
  if (script.roleTier === 'third') return '女三'
  if (script.roleTier === 'cameo') return '客串'
  return '配角'
}

export function needGaps(attrs: Attrs, script: ScriptDef): { key: AttrKey; need: number; have: number }[] {
  return ATTR_KEYS.filter((k) => script.need[k])
    .map((k) => ({ key: k, need: script.need[k] ?? 0, have: attrs[k] }))
}

export function needLook(script: ScriptDef): string {
  const names = ATTR_KEYS.filter((k) => script.need[k]).map((k) => NEED_NAME[k])
  if (!names.length) return '通告没有注明特别要求。'
  return `试镜要看${names.join('、')}。`
}

export function scheduleLine(script: ScriptDef): string {
  const pay = script.pay > 0 ? `片酬 ${script.pay >= 10000 ? `${(script.pay / 10000).toFixed(1)}万` : `${script.pay}元`}。` : '没有片酬。'
  const dep = script.deposit > 0 ? `定金 ${script.deposit} 元。` : ''
  return `共拍 ${script.shootNeed} 场，需在 ${script.deadlineDays} 天内完成。杀青后另有 ${script.promoNeed} 场宣传。${pay}${dep}`
}

export function monthIndex(week: number): number {
  return Math.floor((week - 1) / 4)
}

function mulberry32(a: number) {
  return () => {
    let t = (a += 0x6d2b79f5)
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function gradeOpen(script: ScriptDef, recognition: number, fans: number, identity: IdentityId): boolean {
  return gradeUnlocked(script.grade, recognition, fans, identity)
}

export type OfferAccess = {
  flags?: Record<string, boolean>
  favor?: Record<string, number>
  met?: Record<string, boolean>
}

function scriptUnlocked(script: ScriptDef, access?: OfferAccess): boolean {
  if (!script.unlock) return true
  const flags = access?.flags ?? {}
  const favor = access?.favor ?? {}
  const met = access?.met ?? {}
  if (script.unlock === 'broker') return Boolean(flags.brokerSpecial)
  if (script.unlock === 'liangshi') return Boolean(met.liangshi) && (favor.liangshi ?? 0) >= (script.unlockFavor ?? 50)
  if (script.unlock === 'guyan') return Boolean(met.guyan) && (favor.guyan ?? 0) >= (script.unlockFavor ?? 55)
  return false
}

export function monthOfferIds(
  seed: number,
  week: number,
  finished: string[],
  filmingIds: string[],
  recognition: number,
  identity: IdentityId,
  track: Track = 'film',
  fans = 0,
  access?: OfferAccess,
): string[] {
  const m = monthIndex(week)
  const year = playYear(week)
  const rng = mulberry32((seed + (m + 1) * 1315423911 + (track === 'music' ? 17 : track === 'variety' ? 31 : 0)) >>> 0)
  const blocked = new Set([...finished, ...filmingIds])
  const pool = SCRIPTS.filter((s) => {
    if (s.track !== track || blocked.has(s.id) || !scriptUnlocked(s, access)) return false
    if ((s.fromYear ?? 1) > year) return false
    if (year >= 2 && s.grade === 'C') return false
    if (!gradeOpen(s, recognition, fans, identity)) return false
    if (s.roleTier === 'lead' && s.awardTrack && (s.hype === 'award' || /电影/.test(s.type))) {
      if (year < 3 && (recognition < 80 || fans < 60000)) return false
      if (year >= 3 && (recognition < 80 || fans < 90000)) return false
    }
    if (s.unlock) return true
    return roleOffered(s.roleTier, recognition, fans, year)
  })
  const specials = pool.filter((s) => s.unlock)
  const regular = pool.filter((s) => !s.unlock)
  const staples = regular.filter((s) => !s.random)
  const extras = regular.filter((s) => s.random && rng() > 0.42)
  let cand = [...staples, ...extras]
  if (cand.length < 3) cand = regular
  if (year >= 2) {
    const now = cand.filter((s) => (s.fromYear ?? 1) === year)
    const older = cand.filter((s) => (s.fromYear ?? 1) < year)
    cand = now.length >= 3 ? now : [...now, ...older]
  }
  const shuffled = [...cand]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  const forced = [...specials]
  for (let i = forced.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1))
    ;[forced[i], forced[j]] = [forced[j], forced[i]]
  }
  const pickSpecial = forced.slice(0, 2)
  const need = Math.max(0, 3 - pickSpecial.length)
  const ids = [...pickSpecial, ...shuffled.filter((s) => !pickSpecial.includes(s)).slice(0, need)].map((s) => s.id)
  return ids.slice(0, 3)
}

export function monthOffers(week: number, finished: string[], filmingId: string | null): ScriptDef[] {
  return monthOfferIds(1, week, finished, filmingId ? [filmingId] : [], 0, 'college')
    .map((id) => scriptById(id))
    .filter((s): s is ScriptDef => Boolean(s))
}
